### ISSUE TITLE
asterisk-11.x: Could not find required 'Libxml2' development package

### ISSUE THREAD

**Issue by joaochainho** [openwrt/telephony#102]
Hello,

I'm trying to compile asterisk-11-x on **trunk r48624 ar71xx**, but I'm getting the following error, even after running 'make dirclean'.

```
checking for a sed that does not truncate output... /home/OpenWrt/trunk/staging_dir/host/bin/sed
checking for xml2-config... /home/OpenWrt/trunk/staging_dir/target-mips_mips32_musl-1.1.12/host/bin/xml2-config
configure: error: Could not find required 'Libxml2' development package
Makefile:335: recipe for target '/home/OpenWrt/trunk/build_dir/target-mips_mips32_musl-1.1.12/asterisk-11.20.0/.configured_nnnnnnnnnn' failed
make[2]: *** [/home/OpenWrt/trunk/build_dir/target-mips_mips32_musl-1.1.12/asterisk-11.20.0/.configured_nnnnnnnnnn] Error 1
make[2]: Leaving directory '/home/OpenWrt/trunk/feeds/telephony/net/asterisk-11.x'
package/Makefile:192: recipe for target 'package/feeds/telephony/asterisk-11.x/compile' failed
make[1]: *** [package/feeds/telephony/asterisk-11.x/compile] Error 2
make[1]: Leaving directory '/home/OpenWrt/trunk'
/home/OpenWrt/trunk/include/toplevel.mk:192: recipe for target 'package/asterisk-11.x/compile' failed
make: *** [package/asterisk-11.x/compile] Error 2
````

BTW, my system is Ubuntu 15.10 x64. I have the 'libxml2-dev' package installed.

TIA

**Comment by vteccomm** [comment]
hi i am having same problem on Ubuntu 14.04 x64 .
i raised a ticket on openwrt.org they said you don't need to install Libxml2 on OS you need libxml2 development package but i m still confuse.
If you sorted out please help

**Comment by gdudek** [comment]
Same here on a non-openwrt distro

**Comment by jslachta** [comment]
Latest commits fixes asterisk-13.x and asterisk-11.x. Please try asterisk package and let me know. Thank you. If this problem persists, please reopen this issue.

**Comment by joaochainho** [comment]
Tested latest commits. No issues found.
Thank you for solving it.

**Comment by gretel** [comment]
i had to do like in http://lists.infradead.org/pipermail/lede-dev/2017-February/006190.html
