### ISSUE TITLE
Asterisk 1.8 missing from trunk

### ISSUE THREAD

**Issue by matiasrivera** [openwrt/telephony#107]
Hi,
  Yesterday I updated feeds and I found out that asterisk 1.8 is missing from trunk. Is this an error or something that will permanently be removed from openwrt future versions?

Thank you,

Matías

**Comment by jslachta** [comment]
Hi,

asterisk at version 1.8 has met its EOL (End Of Life), thus it is not supported by the upstream. It is not recommended to distribute this package. If you want to use that package, use the [abandoned feed](https://github.com/openwrt/packages-abandoned).

See [Asterisk versions](https://wiki.asterisk.org/wiki/display/AST/Asterisk+Versions).

Jiri

**Comment by matiasrivera** [comment]
Thank you Jiri. I have tried many times to run asterisk 11 in openwrt but haven't succeded to start the process (sqlite.astdb error), I will try with 1.8 as you mention.

The only feeds.conf file I can find is feeds.conf.default. Is this the place where I have to add abandoned feed?

Thanks,

Matías

**Comment by matiasrivera** [comment]
Hi Jiri, I was able to config the abandoned feed. When I try to make the build with asterisk 1.8 in it I get the following error

Collected errors:
 * opkg_install_cmd: Cannot install package 1.8.32.3.
 * opkg_install_cmd: Cannot install package .8.32.3-4_ar71xx.ipk.
 * opkg_install_cmd: Cannot install package net.
 * opkg_install_cmd: Cannot install package libs.
 * opkg_install_cmd: Cannot install package Alex Samorukov <samm@os2.kiev.ua>.
 * opkg_install_cmd: Cannot install package 1.8.32.3.
 * opkg_install_cmd: Cannot install package Jiri Slachta <slachta@cesnet.cz>.
 * opkg_install_cmd: Cannot install package net.
 * opkg_install_cmd: Cannot install package .
 * opkg_install_cmd: Cannot install package Jiri Slachta <slachta@cesnet.cz>.
xargs: /home/matias/openwrt/staging_dir/host/bin/opkg: exited with status 255; aborting


Looks like there's a typo in some file. Can you help me fix it?

Matias

**Comment by jslachta** [comment]
Hello Matias,

I would suggest to use asterisk11 or newer. Please, send me the asterisk output which will help me to find out what is happening. Thank you.

Jiri

**Comment by matiasrivera** [comment]
Jiri,
  I haven't been able to find any walkthrough on how to make asterisk 11
work in openwrt. If I change the package from asterisk18 to asterisk11 I
get a permission error on some files/directories. Asterisk18 is
automatically installed and configured through luci-app-pbx package.  Do I
have to run asterisk11 as root? as another user?

Thanks,

Matías

**Comment by micmac1** [comment]
Hello @matiasrivera 

1.8 is long gone. Please consider closing this issue.

Thanks!
Sebastian
