### ISSUE TITLE
asterisk 11 100% CPU when running shell command (MixMonitor)

### ISSUE THREAD

**Issue by zorxd** [openwrt/telephony#109]
Hi
After upgrading from 15.05 to 15.05.1 (Chaos Calmer, r49220), Asterisk 11.22.0-1 started using 100% CPU when launching an external program. I created a rule to record a call (using MixMonitor), and then move the file after hangup. The recording works, and then Asterisk launches a child process to execute a command to move/copy the file. I tried different commands, as simple as "/bin/ls" and they all never return, with the child asterisk process taking 100% CPU. The main Asterisk process continue to work just fine, but the child process must be killed -9.
device is TP-Link WDR-3600
libc - 0.9.33.2-1
asterisk11 - 11.22.0-1
asterisk11-app-exec - 11.22.0-1
asterisk11-app-mixmonitor - 11.22.0-1
asterisk11-app-system - 11.22.0-1
asterisk11-chan-iax2 - 11.22.0-1
asterisk11-chan-motif - 11.22.0-1
asterisk11-codec-gsm - 11.22.0-1
asterisk11-format-wav-gsm - 11.22.0-1
asterisk11-func-shell - 11.22.0-1
asterisk11-res-clioriginate - 11.22.0-1
asterisk11-res-timing-timerfd - 11.22.0-1
asterisk11-res-xmpp - 11.22.0-1
kernel - 3.18.29-1-566919ede3f1f83e7b6e38a1469d8d8f

**Comment by micmac1** [comment]
Hello @zorxd 

Please try a current LEDE trunk snapshot and check if you can still reproduce. If no please consider closing this issue.

Thanks!
Sebastian

**Comment by jslachta** [comment]
Hi,

asterisk at the version hit its EOL and it is not currently supported in upstream and also is no longer available in this repository. Please use the asterisk-13.x version. If you think this issue persists on newer version, please fill a new ticket.

Thank you.

Kind regards,
Jiri
