### ISSUE TITLE
asterisk-res-srtp: Incoming SRTP calls that specify a key lifetime fail

### ISSUE THREAD

**Issue by jslachta** [openwrt/telephony#11]
An issue was open in package feed for asterisk srtp module (openwrt/packages#811).

**Comment by jslachta** [comment]
Hi @schoerg,

so you were able to compile the srtp or not? Or you were not able to use the compiled module? Please explain further. Thank you so much. 

I succesfully compiled and run tested the module, the functionality itself was not yet tested.

Jiri

**Comment by schoerg** [comment]
It has been some days, I am not really sure how I compiled it.

I got myself a build root of OpenWrt, build_dir with target-mips_34kc_uClibc-0.9.33.2 for my devices. In the menuconfig I selected asterisk11 and within that I compiled nearly all of the modules, including the asterisk11-res-srtp.
At first I got the warning "not from the same compiler", then I changed more, downloading all packages and building all of them, the error message has disappeared since.
I am still not sure if the changes are applied during compilation. I extracted the source file, changed the specific part in the source, repackaged it changed the md5 from the package header and compiled it.

The application which is (presumambly) using the key lifetime (PhonerLite) is however not working with SRTP.

**Comment by jslachta** [comment]
I just compile and "load" tested the srtp module. Can you test the functionality? It should be rebuilt within a day in trunk snapshots, but you can compile it on your own. Should be enough to update the feeds and recompile asterisk.

Thank you.

**Comment by schoerg** [comment]
´´´Applying ./patches/030-srtp-fix-key-lifetime.patch using plaintext:
patching file channels/sip/sdp_crypto.c
Hunk #1 FAILED at 252.
1 out of 1 hunk FAILED -- saving rejects to file channels/sip/sdp_crypto.c.rej
Patch failed!  Please fix ./patches/030-srtp-fix-key-lifetime.patch!
make[3]: *** [/home/fs/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/asterisk-11.15.0/.prepared_775f119d8facc37e97b63e407a75e46f] Error 1
make[3]: Leaving directory `/home/fs/openwrt/feeds/telephony/net/asterisk-11.x'
make[2]: *** [package/feeds/telephony/asterisk-11.x/compile] Error 2
make[2]: Leaving directory `/home/fs/openwrt'
make[1]: *** [/home/fs/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/fs/openwrt'
´´´

**Comment by jslachta** [comment]
That is strange.. On a clean buildroot I am getting this:

```
$ make package/asterisk-11.x/{clean,compile,install} V=99
...
Applying ./patches/030-srtp-fix-key-lifetime.patch using plaintext: 
patching file channels/sip/sdp_crypto.c
...
```

Are you trying it on a clean buildroot?

**Comment by schoerg** [comment]
I am now, there was still some stuff there...

**Comment by jslachta** [comment]
Does the patching perform correctly?

**Comment by schoerg** [comment]
Apparently, but now I get this:

```
utils.o: In function `ast_gethostbyname':
utils.c:(.text+0x8ec): warning: gethostbyname_r is obsolescent, use getnameinfo() instead.
/home/fs/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
dns.o: In function `ast_search_dns':
dns.c:(.text+0x68): undefined reference to `res_nsearch'
collect2: error: ld returned 1 exit status
make[5]: *** [asterisk] Error 1
make[5]: Leaving directory `/home/fs/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/asterisk-11.15.0/main'
make[4]: *** [main] Error 2
make[4]: Leaving directory `/home/fs/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/asterisk-11.15.0'
make[3]: *** [/home/fs/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/asterisk-11.15.0/.built] Error 2
make[3]: Leaving directory `/home/fs/openwrt/feeds/telephony/net/asterisk-11.x'
make[2]: *** [package/feeds/telephony/asterisk-11.x/compile] Error 2
make[2]: Leaving directory `/home/fs/openwrt'
make[1]: *** [/home/fs/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/fs/openwrt'
make: *** [world] Error 2
```

Funny thing is that I didn't get this message a few days ago...

**Comment by jslachta** [comment]
This should not be happening. It has already been fixed before. The fourth release of asterisk at version 11.15.0 was succesfully built at least for x86.xen_domu target (the release containing the fix for srtp). Since the last commit containing the fix there was only one compiled image generated by buildbots (just for this target). I would suggest to wait for upcoming builds or to start from clean buildroot.

**Comment by jslachta** [comment]
Would you please so kind to test whether this issue persists? It should be fixed in current snapshots.

**Comment by schoerg** [comment]
Hi, sorry had a lot to do the last days.
On a short first test it seems to be fixed (encrypted call worked).

**Comment by jslachta** [comment]
ok, thank you for the test. I am closing this issue.
