### ISSUE TITLE
asterisk13: missing motif and xmpp 

### ISSUE THREAD

**Issue by zorxd** [openwrt/telephony#110]
Hi

Could you enable motif and xmpp in Asterisk13? They are in Asterisk11.

thanks

**Comment by zorxd** [comment]
I made a patch
https://github.com/openwrt/telephony/pull/137

**Comment by jslachta** [comment]
This should be fixed by now. Please reopen if the absence persists.

**Comment by wjcarpenter** [comment]
I recently installed asterisk13 on LEDE/OpenWRT 17.01.4. I found res_xmpp in the opkg repository, but I cannot find chan_motif.

Could something have happened? (Or am I just not looking in the right place? I have installed almost all of the asterisk13-* packages.)

**Comment by micmac1** [comment]
Am May 8, 2018 4:31:37 PM UTC schrieb WJCarpenter <notifications@github.com>:
>I recently installed asterisk13 on LEDE/OpenWRT 17.01.4. I found
>res_xmpp in the opkg repository, but I cannot find chan_motif.
>
>Could something have happened? (Or am I just not looking in the right
>place? I have installed almost all of the asterisk13-* packages.)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openwrt/telephony/issues/110#issuecomment-387462853

Hello!

chan-motif support is in the trunk version. There should be a release candidate for openwrt 18.05 shortly, then you can use it. Is that OK for you?

Regards
Seb

**Comment by wjcarpenter** [comment]
Yeah, that sounds great. Timing isn't critical for me. (I'm planning to move my working asterisk13 off a PC and onto a router, but it's not urgent.)

**Comment by micmac1** [comment]
Am May 8, 2018 5:08:41 PM UTC schrieb WJCarpenter <notifications@github.com>:
>Yeah, that sounds great. Timing isn't critical for me. (I'm planning to
>move my working asterisk13 off a PC and onto a router, but it's not
>urgent.)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/openwrt/telephony/issues/110#issuecomment-387473790

OK,

Shouldn't take much longer for the first RC to arrive.

Regards,
Seb

**Comment by wjcarpenter** [comment]
Your mention of 18.05 gave me an idea. I grabbed chan_motif from the 18.x package repo. It seems to be working fine.

**Comment by micmac1** [comment]
lol, whatever works for you ;-)
