### ISSUE TITLE
Add PJSUA on telephony repository

### ISSUE THREAD

**Issue by Moisesbr** [openwrt/telephony#113]
Hi guys,

Maybe add pjsua an command line SIP soft phone, based on official pjsip.
PJSIP has been developed by a small team working exclusively for the project since 2005.

That is a great command line softphone, that could be on telephony repository.

**Comment by micmac1** [comment]
Hello @Moisesbr 

Looks like nobody has felt the need to spend time on this. Please consider sending a Pull Request if this is important to you.

Please consider closing this issue.

Kind regards,
Sebastian

**Comment by micmac1** [comment]
One reason not to add pjsua would be that you'd need to maintain an extra variant for all the various pjproject libs it depends on. Because for Asterisk we can get away with a slimmed-down version. But for pjsua you'd need to add codecs etc.
