### ISSUE TITLE
asterisk11-chan-sccp-b is not working

### ISSUE THREAD

**Issue by evs38** [openwrt/telephony#121]
Using mipself version of asterisk 11. When loading module chan-sccp-b into Asterisk, it stops with following error message:

`ERROR[2771]: sccp_utils.c:2186 __start_iconv: SCCP:conversion from 'UTF-8' to 'ISO8859-1' not available.
`
iconv, libcharset and libiconv-full packages are installed.
Also asked at Entware-ng/Entware-ng#389

**Comment by micmac1** [comment]
Hello @evs38 

I hope this is fixed in trunk. Please try a trunk snapshot (LEDE) and consider closing this issue if it works fine.

Thanks,
Sebastian

**Comment by jslachta** [comment]
Hi,

asterisk at the version 11.x hit its EOL and it is not currently supported in upstream and also is no longer available in this repository. Please use the asterisk-13.x version. Thus we do not provide package asterisk11-chan-sccp-b. If you think this issue persists on newer asterisk version, please fill a new ticket.

Thank you.

Kind regards,
Jiri
