### ISSUE TITLE
sipp compile failed

### ISSUE THREAD

**Issue by taeasy** [openwrt/telephony#125]
make[2]: Leaving directory '/home/main/lede/package/libs/toolchain'
make[2]: Entering directory '/home/main/lede/package/libs/ncurses'
make[2]: Leaving directory '/home/main/lede/package/libs/ncurses'
make[2]: Entering directory '/home/main/lede/package/libs/ncurses'
if [ -f /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/ncurses.default.install.clean ]; then rm -f /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/ncurses.default.install /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/ncurses.default.install.clean; fi
if [ -f /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/ncurses.default.install.clean ]; then rm -f /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/ncurses.default.install /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/ncurses.default.install.clean; fi
make[2]: Leaving directory '/home/main/lede/package/libs/ncurses'
make[2]: Entering directory '/home/main/lede/package/libs/uclibc++'
if [ -f /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/uclibc++.default.install.clean ]; then rm -f /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/uclibc++.default.install /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/pkginfo/uclibc++.default.install.clean; fi
make[2]: Leaving directory '/home/main/lede/package/libs/uclibc++'
make[2]: Entering directory '/home/main/lede/feeds/telephony/net/sipp'
rm -f /home/main/lede/staging_dir/target-x86_64_musl-1.1.15/stamp/.sipp_installed
(cd /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990/./; if [ -x ./configure ]; then find /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990/ -name config.guess | xargs -r chmod u+w; find /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990/ -name config.guess | xargs -r -n1 cp --remove-destination /home/main/lede/scripts/config.guess; find /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990/ -name config.sub | xargs -r chmod u+w; find /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990/ -name config.sub | xargs -r -n1 cp --remove-destination /home/main/lede/scripts/config.sub; AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990:sipp-3.3.990 -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="g++-uc" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990:sipp-3.3.990 -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990:sipp-3.3.990 -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/usr/include -I/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/include -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/usr/include -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/include " LDFLAGS="-L/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/usr/lib -L/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/lib -L/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/usr/lib -L/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/lib -znow -zrelro "   ./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   --build=x86_64-linux-gnu --host=x86_64-openwrt-linux --target=x86_64-openwrt-linux --enable-epoll --without-gsl --without-pcap --with-rtpstream --without-sctp ; fi; )
configure: WARNING: unrecognized options: --disable-nls
configure: loading site script /home/main/lede/include/site/x86_64
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-openwrt-linux-gnu
checking target system type... x86_64-openwrt-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-openwrt-linux-strip... x86_64-openwrt-linux-musl-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for x86_64-openwrt-linux-gcc... x86_64-openwrt-linux-musl-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-openwrt-linux-musl-gcc accepts -g... yes
checking for x86_64-openwrt-linux-musl-gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of x86_64-openwrt-linux-musl-gcc... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether g++-uc accepts -g... yes
checking dependency style of g++-uc... gcc3
checking how to run the C preprocessor... x86_64-openwrt-linux-musl-gcc -E
checking for grep that handles long lines and -e... /home/main/lede/staging_dir/host/bin/grep
checking for egrep... /home/main/lede/staging_dir/host/bin/grep -E
checking for ANSI C header files... yes
checking for initscr in -lcurses... 
no
configure: error: ncurses library missing
Makefile:71: recipe for target '/home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990/.configured_yyyyyyy' failed
make[2]: *** [/home/main/lede/build_dir/target-x86_64_musl-1.1.15/sipp-3.3.990/.configured_yyyyyyy] Error 1
make[2]: Leaving directory '/home/main/lede/feeds/telephony/net/sipp'
package/Makefile:127: recipe for target 'package/feeds/telephony/sipp/compile' failed
make[1]: *** [package/feeds/telephony/sipp/compile] Error 2
make[1]: Leaving directory '/home/main/lede'
/home/main/lede/include/toplevel.mk:194: recipe for target 'package/sipp/compile' failed
make: *** [package/sipp/compile] Error 2
main@debian:~/lede$

**Comment by gmfallon** [comment]
Did you ever get resolution on this? I am having the same problem. I do have have ncurses -
ncurses-libs-5.9-13.20130511.el7.x86_64
ncurses-base-5.9-13.20130511.el7.noarch
ncurses-5.9-13.20130511.el7.x86_64

**Comment by jslachta** [comment]
Hi @taeasy , 

would you be so kind to review this and close the ticket if the issue was resolved? Thank you.

**Comment by jslachta** [comment]
Buildbots builds sipp package at version 3.5.1 and I have run tested the functionality on various targets. Thank you, @micmac1.
