### ISSUE TITLE
asterisk 11 and 13: some packages have wrong description

### ISSUE THREAD

**Issue by bobafetthotmail** [openwrt/telephony#126]
@jslachta 
**It seems like these packages have a wrong description:**
asterisk11-res-realtime, asterisk11-res-timing-dahdi, asterisk11-res-timing-pthread, asterisk11-res-timing-timerfd, asterisk13-res-hep, asterisk13-res-hep-pjsip, asterisk13-res-hep-rtcp, asterisk13-res-http-websocket, asterisk13-res-rtp-asterisk, asterisk13-res-rtp-multicast, asterisk13-res-sorcery, 	asterisk13-res-timing-dahdi, asterisk13-res-timing-pthread, asterisk13-res-timing-timerfd

You can check this yourself from the package lists https://downloads.lede-project.org/snapshots/packages/x86_64/telephony/Packages

**The wrong description is:** 
This package provides support for '' in Asterisk.

**Comment by jslachta** [comment]
Hi Alberto @bobafetthotmail ,

this should be fixed in [this commit](cc38c50aa4b03d427a0d4c0fa3afdad09b25ba2d) and in several other commits. Please reopen this ticket, if you find any other modules now or in the future with the wrong description.

Kind regards,
Jiri
