### ISSUE TITLE
Build error Arcadyan VGV7510KW22(NOR) / o2 6431 - asterisk13

### ISSUE THREAD

**Issue by ds2k5** [openwrt/telephony#133]
Hello,
i downloaded the source with: git clone https://github.com/lede-project/source
after then run the following:
 
./scripts/feeds update -a
./scripts/feeds install -a
 
make defconfig
make prereq
make menuconfig

Select for VGV7510KW22 ( see attach please! .config as _config )

Target System (Lantiq)
Subtarget (XRX200)
Target Profile (o2 Box 6431 / Arcadyan VGV7510KW22 (NOR)

Base system -> block-mount
Base system -> sqm-scripts

Kernel modules -> Filesystems -> kmod-fs-ext4
Kernel modules -> USB Support -> kmod-usb-storage

LuCI -> Collections -> luci
LuCI -> Applications -> luci-app-sqm

Firmware -> dsl-vrx200-firmware-xdsl-b

Network -> Telephony -> asterisk13
Network -> Telephony -> asterisk13 ->asterisk13-app-directed_pickup
Network -> Telephony -> asterisk13 ->asterisk13-app-read
Network -> Telephony -> asterisk13 ->asterisk13-app-stack
Network -> Telephony -> asterisk13 ->asterisk13-app-system
Network -> Telephony -> asterisk13 ->asterisk13-cdr
Network -> Telephony -> asterisk13 ->asterisk13-cdr-csv
Network -> Telephony -> asterisk13 ->asterisk13-chan-sip
Network -> Telephony -> asterisk13 ->asterisk13-codec-a-mu
Network -> Telephony -> asterisk13 ->asterisk13-codec-alaw
Network -> Telephony -> asterisk13 ->asterisk13-codec-g722
Network -> Telephony -> asterisk13 ->asterisk13-codec-g726
Network -> Telephony -> asterisk13 ->asterisk13-codec-gsm
Network -> Telephony -> asterisk13 ->asterisk13-codec-ilbc
Network -> Telephony -> asterisk13 ->asterisk13-codec-resample
Network -> Telephony -> asterisk13 ->asterisk13-codec-ulaw
Network -> Telephony -> asterisk13 ->asterisk13-format-gsm
Network -> Telephony -> asterisk13 ->asterisk13-format-sln
Network -> Telephony -> asterisk13 ->asterisk13-func-blacklist
Network -> Telephony -> asterisk13 ->asterisk13-func-groupcount
Network -> Telephony -> asterisk13 ->asterisk13-pbx-spool
Network -> Telephony -> asterisk13 ->asterisk13-res-rtp-asterisk

Languages -> perl
Languages -> perl -> perl-html-tree
Languages -> perl -> perl-http-message

Mail -> mailsend

But asterisk13 build fail.

checking for strcasestr... yes
checking for strndup... yes
checking for strnlen... yes
checking for strsep... yes
checking for unsetenv... yes
checking for vasprintf... yes
checking for initscr in -lncurses... yes
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking for a sed that does not truncate output... /home/dennis/Downloads/o26431-vmmc_v3/source/staging_dir/host/bin/sed
checking for xml2-config... /home/dennis/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/host/bin/xml2-config
configure: error: Could not find required 'Libxml2' development package
make[3]: *** [Makefile:291: /home/dennis/Downloads/o26431-vmmc_v3/source/build_dir/target-mips_24kc_musl-1.1.16/asterisk-13.9.1/.configured_yyyyyyy] Error 1
make[3]: Leaving directory '/home/dennis/Downloads/o26431-vmmc_v3/source/feeds/telephony/net/asterisk-13.x'
make[2]: *** [package/Makefile:108: package/feeds/telephony/asterisk-13.x/compile] Error 2
make[2]: Leaving directory '/home/dennis/Downloads/o26431-vmmc_v3/source'
make[1]: *** [package/Makefile:102: /home/dennis/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/dennis/Downloads/o26431-vmmc_v3/source'
make: *** [/home/dennis/Downloads/o26431-vmmc_v3/source/include/toplevel.mk:199: world] Error 2

How to fix this ?

Many thanks to Stefan Koch for his helping hand!

Using Manjaro Linux to build the Image
have installed this packages:

pacman -S --needed subversion asciidoc bash bc binutils bzip2 fastjar flex git gcc util-linux gawk intltool zlib make cdrkit ncurses openssl patch perl-extutils-makemaker rsync sdcc unzip wget gettext libxslt boost libusb bin86 sharutils b43-fwcutter findutils

https://wiki.openwrt.org/doc/howto/buildroot.exigence

Thanks

Dennis

[make.txt](https://github.com/openwrt/telephony/files/741542/make.txt)
[_config.txt](https://github.com/openwrt/telephony/files/741543/_config.txt)

[config.zip](https://github.com/openwrt/telephony/files/747441/config.zip)
from source/build_dir/target-mips_24kc_musl-1.1.16/asterisk-13.9.1/menuselect/config.log

configure:4650: checking for xml2-config
configure:4669: found /home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/host/bin/xml2-config
configure:4681: result: /home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/host/bin/xml2-config
configure:4732: gcc -o conftest -O2 -I/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/host/include -I/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/host/usr/include -I
/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/hostpkg/include -I/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/host/include -I/home/schn
eckd/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/host/include/libxml2  -I/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/host/usr/home/schneckd/Downlo
ads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/usr/include/libxml2 -L/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/host/lib -L/home/schneckd/Downloads/o26431
-vmmc_v3/source/staging_dir/host/usr/lib -L/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/hostpkg/lib -L/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24k
c_musl-1.1.16/host/lib -lxml2 conftest.c -L/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/host/usr/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl
-1.1.16/usr/lib -lxml2 -L/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/host/usr/home/schneckd/Downloads/o26431-vmmc_v3/source/staging_dir/target-mips_24kc_musl-1.1.16/usr/lib -l
z -lm >&5
conftest.c:32:27: fatal error: libxml/tree.h: No such file or directory
   #include <libxml/tree.h>
                           ^
compilation terminated.

**Comment by ds2k5** [comment]
i tryed this: cd source

cp -r ./staging_dir/target-mips_24kc_musl-1.1.16/usr/include/libxml staging_dir/host/include

then there is no error

**Comment by ds2k5** [comment]
Looks like this is fixed, now i can compile without copy the libxml directory

**Comment by ds2k5** [comment]
with the 17.01rc2 it is not needed to copy libxml directory

**Comment by ds2k5** [comment]
@gretel : ok i will du a retry, my test was with the tar file

**Comment by ds2k5** [comment]
@gretel : you are right with the Source from: https://github.com/lede-project/source
i had the same problem. Last time i had a tar file.

Can somebody contact the openwrt - telephony team ?

**Comment by 4mig4** [comment]
got the same problem here too with LEDE master

**Comment by jslachta** [comment]
Hi,

I have this issue fixed. I hope during this week you will have an updated package with several more fixes.

**Comment by jpap** [comment]
@jslachta I'm still getting the "Could not find required 'Libxml2' development package" after:

* Updating my `feeds.conf.default` to use this repo for telephony
* Running `./scripts/feeds update telephony && ./scripts/feeds install -a -p telephony`
* Deleting the build directory `build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/asterisk-13.15.0`
* (Re)compile asterisk with `make package/asterisk-13.x/compile V=s`

Am I missing something above?

I am also using LEDE master with the above.

**Comment by musashino205** [comment]
I modified the asterisk-13.x Makefile in master branch as follows and the build succeeded.

- `CFLAGS="$(HOST_CFLAGS) -I$(STAGING_DIR)/../hostpkg/include/libxml2" \` (line 255)
- `CFLAGS="$(HOST_CFLAGS) -I$(STAGING_DIR)/../hostpkg/include/libxml2" \` (line 261)

**Comment by micmac1** [comment]
Hello @ds2k5 @gretel @jpap 

This was fixed in trunk. Please give it a go and close this issue if it works.

Regards,
Seb

**Comment by jslachta** [comment]
Hello @micmac1, @ds2k5, @gretel, @jpap,

asterisk packages for the desired target are available to download from https://downloads.lede-project.org/snapshots/packages/mips_24kc/telephony/

If you have any problem with the build, please reopen this issue.

Thank you.
