### ISSUE TITLE
Asterisk 11: Assertion failed: ../src/pjnath/ice_session.c: pj_ice_sess_create

### ISSUE THREAD

**Issue by rpallai** [openwrt/telephony#140]
Dear maintainers,

Asterisks fails to handle any call on my WRT1200AC due to the following error:
`*CLI> Assertion failed: stun_cfg && cb && p_ice (../src/pjnath/ice_session.c: pj_ice_sess_create: 346)`

Even the most simple echo service is failing. Never seen such error on other platforms with Asterisk 11, seems like an OpenWrt/LEDE specific issue.

mvebu/generic
OpenWrt CC 15.05.1 / LEDE 17.01.0 

The error is exactly same on OpenWrt and LEDE.

root@WRTAC:~# opkg list-installed asterisk11\*
asterisk11 - 11.22.0-2
asterisk11-sounds - 11.22.0-2

```
root@WRTAC:~# asterisk -cd
Parsing /etc/asterisk/asterisk.conf
Seeding global EID 'c2:56:27:73:40:43' from 'eth0' using 'siocgifhwaddr'
Privilege escalation protection disabled!
See https://wiki.asterisk.org/wiki/x/1gKfAQ for more details.
Asterisk 11.22.0, Copyright (C) 1999 - 2013 Digium, Inc. and others.
Created by Mark Spencer <markster@digium.com>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it under
certain conditions. Type 'core show license' for details.
=========================================================================
[ Initializing Custom Configuration Options ]
Parsing /etc/asterisk/extconfig.conf
Resetting translation matrix
Parsing /etc/asterisk/logger.conf
[Apr 15 19:50:19] NOTICE[3884]: loader.c:1244 load_modules: 18 modules will be loaded.
[Apr 15 19:50:19] WARNING[3884]: loader.c:463 load_dynamic_module: Error loading module 'res_musiconhold.so': Error loading shared library /usr/lib/asterisk/modules/res_musiconhold.so: No such file or directory
..[Apr 15 19:50:19] WARNING[3884]: loader.c:463 load_dynamic_module: Error loading module 'res_musiconhold.so': Error loading shared library /usr/lib/asterisk/modules/res_musiconhold.so: No such file or directory
[Apr 15 19:50:19] WARNING[3884]: loader.c:954 load_resource: Module 'res_musiconhold.so' could not be loaded.
...SIP channel loading...
............Asterisk Ready.
*CLI> Assertion failed: stun_cfg && cb && p_ice (../src/pjnath/ice_session.c: pj_ice_sess_create: 346)
Aborted
```
Without "-d" parameter this led to SIGSEGV.

My config is almost default, additions are:

sip.conf:
```
[peer1]
type=peer
host=10.166.71.1
port=5091
;
insecure=invite
```

extensions.conf:
```
[public]
include => demo
```

**Comment by rpallai** [comment]
This issue is reproducible on lede-17.01.0 x86/64 too:
```
root@LEDE:/etc/asterisk# asterisk -cd
Parsing /etc/asterisk/asterisk.conf
[...]
SIP channel loading...
.............Asterisk Ready.
*CLI> [incoming call] Segmentation fault
root@LEDE:/etc/asterisk# uname -a
Linux LEDE 4.4.50 #0 SMP Mon Feb 20 17:13:44 2017 x86_64 GNU/Linux
````
But it ends in SIGSEGV instead of assertion fail even with "-d".

strace output:
```
[...]
[pid  2417] socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 12
[pid  2417] fcntl(12, F_GETFL)          = 0x2 (flags O_RDWR)
[pid  2417] fcntl(12, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid  2417] bind(12, {sa_family=AF_INET, sin_port=htons(16802), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
[pid  2417] brk(0xd5d000)               = 0xd5d000
[pid  2417] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
```

**Comment by micmac1** [comment]
Hello @rpallai @pafels 

Please try a trunk snapshot and check if you still run into the same issue. If yes please let me know how to reproduce.

Thanks,
Sebastian

**Comment by micmac1** [comment]
Hello @rpallai @pafels

And with snapshot I mean a LEDE snapshot. :)

Regards,
Sebastian

**Comment by gemini666** [comment]
Hi. The same error with trunk build.

**Comment by micmac1** [comment]
Please post the version used.

Am 14. August 2017 15:34:44 MESZ schrieb gemini666 <notifications@github.com>:
>Hi. The same error with trunk build.

**Comment by gemini666** [comment]
LEDE Reboot 17.01.2 r3435-65eec8bd5f 
asterisk11 - 11.25.1-2
asterisk11-app-authenticate - 11.25.1-2
asterisk11-app-chanisavail - 11.25.1-2
asterisk11-app-originate - 11.25.1-2
asterisk11-app-sms - 11.25.1-2
asterisk11-app-system - 11.25.1-2
asterisk11-app-verbose - 11.25.1-2
asterisk11-chan-dongle - 1.1r35-6
asterisk11-codec-a-mu - 11.25.1-2
asterisk11-codec-adpcm - 11.25.1-2
asterisk11-codec-alaw - 11.25.1-2
asterisk11-codec-gsm - 11.25.1-2
asterisk11-func-base64 - 11.25.1-2
asterisk11-func-channel - 11.25.1-2

**Comment by micmac1** [comment]
Are you all using chan-dongle? My own test calls with chan-sip were fine.

If this happens only with chan-dongle than I don't think there's an easy fix. The project looks abandoned. See this pull request: https://github.com/bg111/asterisk-chan-dongle/pull/216

There is a lot of proposed fixed for all kinds of versions of asterisk. In there is also an explanation from the author on why the project looks abandoned.

If you can reproduce this _without_ chan-dongle with Asterisk _13_ please let me know how and I'll take a look. Asterisk 11 will be end of life this October, so I don't think too much energy should be spend on it.

Regards,
Sebastian

Am 14. August 2017 17:55:22 MESZ schrieb gemini666 <notifications@github.com>:
>LEDE Reboot 17.01.2 r3435-65eec8bd5f 
>asterisk11 - 11.25.1-2
>asterisk11-app-authenticate - 11.25.1-2
>asterisk11-app-chanisavail - 11.25.1-2
>asterisk11-app-originate - 11.25.1-2
>asterisk11-app-sms - 11.25.1-2
>asterisk11-app-system - 11.25.1-2
>asterisk11-app-verbose - 11.25.1-2
>asterisk11-chan-dongle - 1.1r35-6
>asterisk11-codec-a-mu - 11.25.1-2
>asterisk11-codec-adpcm - 11.25.1-2
>asterisk11-codec-alaw - 11.25.1-2
>asterisk11-codec-gsm - 11.25.1-2
>asterisk11-func-base64 - 11.25.1-2
>asterisk11-func-channel - 11.25.1-2

**Comment by gemini666** [comment]
I am using chan_dongle. But if I try to place a sip call, asterisk ends.

**Comment by pafels** [comment]
The problem is that there is no module chan_dongle for Asterisk 13. I have tried to compile the git hub project you've mentioned with no success. 
About Asterisk 11.. segmentation fault is thrown even on a sip call.

**Comment by micmac1** [comment]
Hi,

Can you provide the config that produces segfaults without chan-dongle loaded, including instructions on how to reproduce?

Am 15. August 2017 16:51:12 MESZ schrieb pafels <notifications@github.com>:
>The problem is that there is no module chan_dongle for Asterisk 13. I
>have tried to compile the git hub project you've mentioned with no
>success. 
>About Asterisk 11.. segmentation fault is thrown even on a sip call.

**Comment by gemini666** [comment]
Hi. New chan_dongle dos not make sense.

**Comment by micmac1** [comment]
Maybe the README over at https://github.com/wdoekes/asterisk-chan-dongle helps

Am 1. September 2017 08:22:59 MESZ schrieb gemini666 <notifications@github.com>:
>Hi. New chan_dongle dos not make sense.

**Comment by MarkChekhovsky** [comment]
I can confirm Asterisk11 falls on simple SIP call(not using chan_dongle) at all(LEDE is 17.01.2)
The same happens with CC15.05.1
but!
asterisk18 works fine on the same CC15.05.1

hope it helps

**Comment by micmac1** [comment]
Hello, tests on snapshots with asterisk 13 would be appreciated. 

Am 6. September 2017 17:51:12 MESZ schrieb MarkChekhovsky <notifications@github.com>:
>I can confirm Asterisk11 falls on simple SIP call(not using
>chan_dongle) at all(LEDE is 17.01.2)
>The same happens with CC15.05.1
>but!
>asterisk18 works fine on the same CC15.05.1
>
>hope it helps

**Comment by ammudaiwik** [comment]
Hi ,

when im trying install luci-app-pbx for make menuconfig, it is failing because of some dependencies ..
Can anyone please tell me how to install luci-app-pbx for LEDE image(architecture is bcm27XX) using asterisk 11/13?.

**Comment by micmac1** [comment]
Hi,

I think that package is not maintained anymore and only worked with asterisk 1.8.

Regards,
Seb

Am 17. Oktober 2017 11:24:36 MESZ schrieb ammudaiwik <notifications@github.com>:
>Hi ,
>
>when im trying install luci-app-pbx for make menuconfig, it is failing
>because of some dependencies ..
>Can anyone please tell me how to install luci-app-pbx for LEDE
>image(architecture is bcm27XX) using asterisk 11/13?.

**Comment by ammudaiwik** [comment]
@micmac1 
but in make menuconfig,only asterisk 11 and 13 are there know..how to add asterisk 1.8 to make menuconfig?
only with asterisk 11/13 i can't install luc-app-pbx?

**Comment by micmac1** [comment]
Well the author doesn't maintain the software anymore. What can you do. If anybody is interested and wants to update this luci app of course they can do so.

Am 17. Oktober 2017 11:36:44 MESZ schrieb ammudaiwik <notifications@github.com>:
>@micmac1 
>but in make menuconfig,only asterisk 11 and 13 are there know..how to
>add asterisk 1.8 to make menuconfig?
>only with asterisk 11/13 i can't install luc-app-pbx?

**Comment by ammudaiwik** [comment]
ok fine..but how to add asterisk 1.8 to make menuconfig in LEDE?

**Comment by micmac1** [comment]
That won't happen. It is completely end of life.

Am 17. Oktober 2017 11:44:02 MESZ schrieb ammudaiwik <notifications@github.com>:
>ok fine..but how to add asterisk 1.8 to make menuconfig in LEDE?

**Comment by ammudaiwik** [comment]
then i can't install luci-app-pbx???

**Comment by micmac1** [comment]
Correct

Am 17. Oktober 2017 11:47:12 MESZ schrieb ammudaiwik <notifications@github.com>:
>then i can't install luci-app-pbx???

**Comment by ammudaiwik** [comment]
ok thanku.

**Comment by jslachta** [comment]
Hi,

asterisk at the version 11.x hit its EOL and it is not currently supported in upstream and also is no longer available in this repository. Please use the asterisk-13.x version. If you think this issue persists on newer version, please fill a new ticket.

Thank you.

Kind regards,
Jiri
