### ISSUE TITLE
LEDE 17.01.1 / asterisk13: res_pjproject.so is missing

### ISSUE THREAD

**Issue by madires** [openwrt/telephony#142]
Hi!

Nearly all PJSIP related modules won't load. Starting with asterisk 13.8.0 res_pjsip depends on res_pjproject, which is unfortunately missing. Please add the missing module!

Cheers

**Comment by jslachta** [comment]
Hello @madires 

I am going to take a look at it during this weekend.

**Comment by madires** [comment]
Hi!

While testing the current LEDE snapshot for #88 I've got an log entry about a missing "pjproject.conf". So res_pjproject was added, but unfortunately not the conf file.

Cheers

**Comment by jslachta** [comment]
Hi @madires 

I have added the missing pjproject.conf to res_pjprojectt module. Would you be so kind to review this?

**Comment by madires** [comment]
Hi!

Thanks for adding the missing file!

Cheers,
 Markus
