### ISSUE TITLE
Asterisk (all versions): missing modules

### ISSUE THREAD

**Issue by fktpa813** [openwrt/telephony#15]
Currently there are several Asterisk modules not included in any of the packages. Although not everybody uses these modules, they still can be useful. Would it be possible to modify the Makefiles for all current Asterisk builds (1.8, 11, 13) to build new packages for the modules listed below?
- func_enum.so (ENUM support, include /etc/asterisk/enum.conf)
- func_env.so (Environment/filesystem dialplan functions)
- func_module.so (Simple module check function)
- func_math.so (Math related dialplan function)
- app_db.so (this is a small module with 2 extra db functions, I'd include it in the same package as func_db.so rather than create a new package)

Thank you!

**Comment by jslachta** [comment]
Should be fixed. Please test.

**Comment by fktpa813** [comment]
Thank you! All looks good in Asterisk 1.8 Makefile, but for version 11 and 13 you duplicated the line for func-db package. The old version of that line needs to be deleted.

**Comment by jslachta** [comment]
This should be fixed.
