### ISSUE TITLE
G.729 codec is built for wrong asterisk version (when making asterisk 13)

### ISSUE THREAD

**Issue by jpap** [openwrt/telephony#150]
I compiled the codec from telephony master (LEDE SDK release 17.01.1) and had trouble loading the resulting package build into asterisk 13.  It turned out that the built package was for asterisk 11; verified in the build log where the `--with-asterisk100` option was incorrectly being passed to `configure`.

When I change the last two lines of the `Makefile` to,
```
####DISABLED####$(eval $(call BuildPackage,asterisk11-codec-g729))
$(eval $(call BuildPackage,asterisk13-codec-g729))
```
then the correct codec package is built and works fine with asterisk 13.

My knowledge of the LEDE/OpenWRT build system is lacking, so I wasn't sure how to fix the issue, and despite a couple of hacky attempts that went nowhere.

I'm happy to craft a PR with some direction; otherwise would love to see it fixed.

**Comment by micmac1** [comment]
Hello Jiri,

I'll have a fix for this in my next PR. Coming very shortly.

Regards,
Seb

**Comment by jslachta** [comment]
Hi @jpap,

this should be fixed in [this commit](https://github.com/openwrt/telephony/commit/a4513b7bd91e8ecd447d94b63f3f52a05f9e5f61). Please review this issue and consider closing the ticket if this was resolved.

**Comment by jslachta** [comment]
G.729 codec was succesfully built for both variants. Please reopen if you think the issue still remains.
