### ISSUE TITLE
pjproject fails to build

### ISSUE THREAD

**Issue by plntyk** [openwrt/telephony#16]
- doing a full build with all packages (checking for fails) on Arch Linux
```
CONFIG_TARGET_omap=y
CONFIG_TARGET_omap_Default=y
CONFIG_TARGET_BOARD="omap"
CONFIG_ALL=y
CONFIG_DEVEL=y
CONFIG_TOOLCHAINOPTS=y
CONFIG_BUILD_LOG=y
```
Build error:
```
arm-openwrt-linux-uclibcgnueabi-ld: cannot find -lgcc
```

complete compile.txt log: https://gist.github.com/plntyk/800721be7f9b9d722376
complete config.log: https://gist.github.com/plntyk/771fb204152e13f8bac5

**Comment by plntyk** [comment]
maybe https://dev.openwrt.org/ticket/9017 is related - looks similar at least

**Comment by plntyk** [comment]
Can somebody with some equipment / testing experience with the package try the following "trivial" fix: https://gist.github.com/plntyk/3bacd65c30931d2f2e5a

So either its some bug in the autoconf/make files or with the linker

**Comment by dangowrt** [comment]
Committed in https://github.com/openwrt/telephony/commit/b503392f2e56a0a3fb4e0ed6964b5885ad37b6e2
Thanks!
Tested on ar71xx and oxnas.
