### ISSUE TITLE
asterisk13-chan-sccp-b - Error relocating /usr/lib/asterisk/modules/chan_sccp.so: ast_codec_pref_append: symbol not found

### ISSUE THREAD

**Issue by mkarpik79** [openwrt/telephony#168]
root@BLACK-LEDE:/etc$ opkg install asterisk13-chan-sccp-b
Installing asterisk13-chan-sccp-b (v4.2.3-r6647-2) to root...
Downloading http://downloads.lede-project.org/releases/17.01.2/packages/mips_24kc/telephony/asterisk13-chan-sccp-b_v4.2.3-r6647-2_mips_24kc.ipk
Installing jansson (2.7-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.2/packages/mips_24kc/packages/jansson_2.7-1_mips_24kc.ipk
Installing libstdcpp (5.4.0-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.2/targets/ar71xx/generic/packages/libstdcpp_5.4.0-1_mips_24kc.ipk
Installing libxml2 (2.9.4-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.2/packages/mips_24kc/packages/libxml2_2.9.4-1_mips_24kc.ipk
Installing libxslt (1.1.28-2) to root...
Downloading http://downloads.lede-project.org/releases/17.01.2/packages/mips_24kc/packages/libxslt_1.1.28-2_mips_24kc.ipk
Installing asterisk13 (13.9.1-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.2/packages/mips_24kc/telephony/asterisk13_13.9.1-1_mips_24kc.ipk
Configuring jansson.
Configuring libstdcpp.
Configuring libxml2.
Configuring libxslt.
Configuring asterisk13.
Configuring asterisk13-chan-sccp-b.

root@BLACK-LEDE:/$ asterisk -vvf
[...]
Asterisk Dynamic Loader Starting:
  == Parsing '/etc/asterisk/modules.conf': Found
[Jul  9 23:03:21] NOTICE[24382]: loader.c:1442 load_modules: 12 modules will be loaded.
[Jul  9 23:03:21] WARNING[24382]: loader.c:556 load_dynamic_module: Error loading module 'chan_sccp.so': Error relocating /usr/lib/asterisk/modules/chan_sccp.so: ast_codec_pref_append: symbol not found
 Loading res_crypto.so.

**Comment by jslachta** [comment]
Asterisk 13.18.0 with module chan-sccp-b currently loads fine. Please, reopen the ticket if the issue still persists. It currently works out of the box, so I am closing this ticket.
