### ISSUE TITLE
asterisk-13.x: func-odbc - symbol not found

### ISSUE THREAD

**Issue by jslachta** [openwrt/telephony#181]
Asterisk cannot load func-odbc module. See log below.

`[Aug 18 10:59:52] WARNING[1523] loader.c: Error loading module 'func_odbc.so': Error relocating /usr/lib/asterisk/modules/func_odbc.so: ast_odbc_retrieve_transaction_obj: symbol not found`

**Comment by micmac1** [comment]
Hi Jiri,

Looks like res_odbc_transaction.so is missing in the Makefile.

Regards,
Seb

**Comment by micmac1** [comment]
I'm working on  a PR for some asterisk13 stuff right now. I hope to push it this evening. I'll add the module into it.

**Comment by jslachta** [comment]
This is fixed in the referenced commit, thank you.
