### ISSUE TITLE
recursive dependencies (still there in Openwrt trunk r44685)

### ISSUE THREAD

**Issue by juanriccio** [openwrt/telephony#19]
$ make defconfig
 tmp/.config-package.in:48619:error: recursive dependency detected!
 tmp/.config-package.in:48619: symbol PACKAGE_freeswitch depends on PACKAGE_freeswitch-mod-perl
 tmp/.config-package.in:49752: symbol PACKAGE_freeswitch-mod-perl is selected by PACKAGE_freeswitch-mod-verto
 tmp/.config-package.in:50494: symbol PACKAGE_freeswitch-mod-verto depends on PACKAGE_freeswitch

Closed on https://dev.openwrt.org/ticket/19166 and reported here as suggested.

**Comment by jslachta** [comment]
This issue does not occur anymore since mod-perl is gone.
