### ISSUE TITLE
asterisk-chan-lantiq will not build

### ISSUE THREAD

**Issue by Bongo79** [openwrt/telephony#190]
`make[1]: Entering directory `/tmp/build/lsdk'
make[2]: Entering directory `/tmp/build/lsdk/feeds/telephony/net/asterisk-chan-lantiq'
cp -fpR feeds/telephony/net/asterisk-chan-lantiq/files/chan_lantiq-asterisk13.c /tmp/build/lsdk/build_dir/target-mips_24kc_musl-1.1.16/chan-lantiq-asterisk13/chan-lantiq-1.0/chan_lantiq.c
cp: cannot stat 'feeds/telephony/net/asterisk-chan-lantiq/files/chan_lantiq-asterisk13.c': No such file or directory
make[2]: *** [/tmp/build/lsdk/build_dir/target-mips_24kc_musl-1.1.16/chan-lantiq-asterisk13/chan-lantiq-1.0/.prepared_23daab2368ee218ebc02ba1660f56685] Error 1
make[2]: Leaving directory `/tmp/build/lsdk/feeds/telephony/net/asterisk-chan-lantiq'
make[1]: *** [package/feeds/telephony/asterisk-chan-lantiq/prepare] Error 2
make[1]: Leaving directory `/tmp/build/lsdk'
make: *** [package/asterisk-chan-lantiq/prepare] Error 2`

it can be fix in net/asterisk-chan-lantiq/Makefile:

` 	$(INSTALL_DIR) $(1)/etc/asterisk`
`-	$(INSTALL_CONF) $(SOURCE)/files/lantiq-$(BUILD_VARIANT).conf.sample \`
`+	$(INSTALL_CONF) ./files/lantiq-$(BUILD_VARIANT).conf.sample \`
 `		$(1)/etc/asterisk/lantiq.conf`

`define Build/Prepare`
`-	$(CP) $(SOURCE)/files/chan_lantiq-$(BUILD_VARIANT).c $(PKG_BUILD_DIR)/chan_lantiq.c`
`-	$(CP) $(SOURCE)/files/default.exports $(PKG_BUILD_DIR)/chan_lantiq.exports`
`+	$(CP) ./files/chan_lantiq-$(BUILD_VARIANT).c $(PKG_BUILD_DIR)/chan_lantiq.c`
`+	$(CP) ./files/default.exports $(PKG_BUILD_DIR)/chan_lantiq.exports`
` endef`

**Comment by micmac1** [comment]
Sorry, my fault. I'll send a pull request.

**Comment by micmac1** [comment]
I think this issue should be closed. #193 is still open for the general buildbot compile issue.

**Comment by dangowrt** [comment]
ACK.
