### ISSUE TITLE
ortp: maintain or remove?

### ISSUE THREAD

**Issue by micmac1** [openwrt/telephony#192]
Hi all,

Not an issue, just a question. ortp was updated to 0.27.0 in 2016 (this repo has 0.23.0 from 2014). To update it a new packet would be needed ("bctoolbox").

I have a Makefile ready for both ortp and bctoolbox. But nothing seems to depend on ortp. As it is a lib this makes it rather useless (when there are no lib users...). @psycho-nico do you know of any users of ortp? Is this still needed? If not I suggest ortp gets removed from the tree.

Kind regards,
Sebastian

**Comment by jslachta** [comment]
I would suggest moving the package to the oldpackages repo, if there is no use for it.

**Comment by micmac1** [comment]
Hello @jslachta 

Seems like nobody objected. Could you please move it to oldpackages?

And while you're at it I suggest to move asterisk11 as well as it received its last rites: http://lists.digium.com/pipermail/asterisk-users/2017-October/292035.html

When asterisk11 is gone some variant packages can be cleaned up a bit by removing asterisk11 there, too. If you want I can send a PR for that. For the move of the two packages to oldpackages I don't think I could send a PR that makes sense.

Best regards,
Sebastian

**Comment by jslachta** [comment]
Hi Sebastian @micmac1,

I am going to handle that. Thank you for mentioning that.

Kind regards,
Jiri

**Comment by jslachta** [comment]
Hi @micmac1,

asterisk-11.x and package variants of several other modules along with the ortp are no longer in telephony repository. Asterisk-11.x and ortp library are available in the abandoned repository.

I am marking this issue as resolved.

**Comment by micmac1** [comment]
Thank you very much! Have a nice Sunday evening!

Am 29. Oktober 2017 18:34:50 MEZ schrieb Jiri Slachta <notifications@github.com>:
>Hi @micmac1,
>
>asterisk-11.x and package variants of several other modules along with
>the ortp are no longer in telephony repository. Asterisk-11.x and ortp
>library are available in the abandoned repository.
>
>I am marking this issue as resolved.

**Comment by jslachta** [comment]
Nice Sunday evening to you too! :-)
