### ISSUE TITLE
Asterisk 13.18

### ISSUE THREAD

**Issue by Bongo79** [openwrt/telephony#194]
It is important for me to have alway the current version, because for older Versions exist in many cases a CVE.

I wait for the 13.18.0 final, for this reason this: https://forum.openwrt.org/viewtopic.php?pid=367056#p367056 is untested yet.
Required changed for the version 13.18.0-rc1 are:

- delete the 054-pjsip_unresolved_symbol.patch, because res/res_pjsip/pjsip_message_ip_updater.c does not exist.
- the main/http.c was changed, for this reason the 055-ASTERISK-24517.patch does not work and split into:
055-ASTERISK-24517-for13.18.patch and 056-ASTERISK-24517-http.c-for13.18.patch
- an other problem was that the codec g726 not work on 13.17.2:
the call stops after a Minute, the loadavm are extremly high and the asterisk message are:
...
[Oct  3 11:50:41] WARNING[2537][C-00000000]: channel.c:1145 __ast_queue_frame: Exceptionally long voice queue length queuing to IAX2/peer55xx-12016
...
for this reason exist patch 057-AST_PBX_MAX_STACK_set_to_512.patch
see: https://issues.freepbx.org/browse/FREEPBX-15656
Now g726 is working, but not g729 (the same Failure messages)

**Comment by jslachta** [comment]
NACK, the release cycle is quite frequent, please wait for the final 13.18.0. It is going to be released soon within several days.

**Comment by jslachta** [comment]
Asterisk was updated to 13.18.0
