### ISSUE TITLE
removed patches from Asterisk-13.18.0

### ISSUE THREAD

**Issue by Bongo79** [openwrt/telephony#195]
Hi
removing of 054-pjsip_unresolved_symbol.patch is presumably usefull because the file that should patched are not exist in 13.18.0
but is removing of 055-ASTERISK-24517.patch usefull ?
What was the reason for this patch ?

I split the 055 patch in 055/056 and adding a new patch 057 that solve a problem with the g726 codec in 13.17.2
see: https://issues.freepbx.org/browse/FREEPBX-15656

And i insert all asteriskmodules and config files

patch are inside here:
https://forum.openwrt.org/viewtopic.php?pid=367723#p367723

**Comment by jslachta** [comment]
055-ASTERISK-24517.patch was removed because the patch was either not applicable and also it contained changes that were made to version 13.18.0. I have gone through the patch and the changes were the same as the source in the upstream.

As for the asterisk modules, the current set is the mostly needed one, it does not contain all modules. Maintaining the complete set of asterisk modules is a time consuming task, since the modules changes over time. However even if I implicitly do not add the rest of the modules, I accept pull requests for that. It is more important to have fully working asterisk in telephony repository, than to have all modules.

Thank you for your proposal and if you need to add any module to asterisk, please create a pull request. There are only several modules left I am planning to add by myself.

**Comment by Bongo79** [comment]
patch 055
I find this:
TLS support for Solaris, Ming and non-glibc Linux systems
https://issues.asterisk.org/jira/browse/ASTERISK-24517


> it contained changes that were made to version 13.18.0. I have gone through the patch and the changes were the same as the source in the upstream.

really ? I equal the patch with the asterisk-13.18.0/channels/chan_sip.c and found the unchanged code.
Can you confirm that chan_sip TLS is working ?
I can confirm that on my solution the chan_sip server are working, but i have not test a connection.

> As for the asterisk modules, the current set is the mostly needed one, it does not contain all modules. Maintaining the complete set of asterisk modules is a time consuming task, since the modules changes over time. However even if I implicitly do not add the rest of the modules, I accept pull requests for that. It is more important to have fully working asterisk in telephony repository, than to have all modules.

I agree in the other hand it is very bad when i play with it and some modules are missed, because i need 5h to recompile via SDK.
For this reason i write the script add-ast-modules.sh which is inside the link to.
It equals ipkg-install ipkg-mips_24kc and all config files and modules that are not installed will be add to the Makefile.
`./add-ast-modules.sh info`
shows all config and module files that are not installed.
`./add-ast-modules.sh add`
add the result to the makefile
(I have done in my Makefile)

It isnt a perfect solution and in some of the packages presumably errors but in my opinium it is better the missed module exist on any place but i need to recompile.

On 13.17.2 codec g726 was only working for few minuts them the load gets etreme high and the connection stops.
i solve this with https://issues.freepbx.org/browse/FREEPBX-15656
But i haved the same problem on codec g729 and this wasn,t solved with this.
On 13.18.0 i have not tested.

**Comment by jslachta** [comment]
You are right! I have looked over sources in wrong branch that already has the changes. I am going to fix that on Saturday morning.

**Comment by sebastianertz** [comment]
I have adapted the patch for version 13.18.0:
https://pastebin.com/mV0613E4

**Comment by jslachta** [comment]
Path added, thank you @sebastianertz and @Bongo79 .

**Comment by jslachta** [comment]
You can also try asterisk-15.x which should have those issues fixed in upstream.

**Comment by Bongo79** [comment]
Thanks too for fast updates,
But version 15 is not actraktiv for me, the reasons are:
1.) Version 13 have a longer lifetime
2.) i use them on Lantiq devices with channel-lantiq, these devices have not much flash

**Comment by jslachta** [comment]
Asterisk15 is a transition package before the next LTS release will be released.
