### ISSUE TITLE
dahdi-linux with Kernel 3.19 , 4.0

### ISSUE THREAD

**Issue by plntyk** [openwrt/telephony#22]
There are several issues with the deprecation of certain macros in Kernel 3.19 and 4.0:

see the last commits upstream for fixes:
https://github.com/asterisk/dahdi-linux/commit/1559db9d1ae03780788788c07334ca54cdd1253a -  dahdi: strnicmp() -> strncasecmp() 
https://github.com/asterisk/dahdi-linux/commit/4d86a8f3f690ee9bb9429e17cc03856c6c2dc760 -  dahdi: struct file.f_dentry macro was removed in kernel 3.19 
https://github.com/asterisk/dahdi-linux/commit/1cc0ad510acd404e63923ed3062b9302d53580da -  dahdi: Fix "void value not ignored..." error when compiling against kernel 4.0.

**Comment by dangowrt** [comment]
Fixed in https://github.com/openwrt/telephony/commit/d7e56822d72bb69f07ad00b225e0971566783913
