### ISSUE TITLE
almost the entire feed fails to build in the SDK

### ISSUE THREAD

**Issue by blogic** [openwrt/telephony#26]
here is the list of packages that fail to build inside the SDK. they need to be fixed in the next week or two to be part of RC1

   ERROR: package/feeds/telephony/dahdi-linux failed to build.
   ERROR: package/feeds/telephony/bcg729 failed to build.
   ERROR: package/feeds/telephony/dahdi-tools failed to build.
   ERROR: package/feeds/telephony/asterisk-11.x failed to build.
   ERROR: package/feeds/telephony/chan-sccp-b failed to build (build variant: asterisk11).
   ERROR: package/feeds/telephony/asterisk-11.x-chan-dongle failed to build.
   ERROR: package/feeds/telephony/asterisk-g72x failed to build (build variant: asterisk11).
   ERROR: package/feeds/telephony/asterisk-g72x failed to build (build variant: asterisk13).
   ERROR: package/feeds/telephony/asterisk-g72x failed to build (build variant: asterisk18).
   ERROR: package/feeds/telephony/freeswitch failed to build.

**Comment by jslachta** [comment]
Any chance to get a verbose log? If not, I will do the test and try to resolve the package issues.

**Comment by blogic** [comment]
dhadi breaks due to including kernel folders. the rest is most likely followup breakage.

**Comment by jslachta** [comment]
This might be the reason. I will fix the asterisk packages within a week (dahdi, bcg, sccp) and the freeswitch should be fixed soon.

**Comment by blogic** [comment]
bcg broke due tot he bad md5sum. should be fixed now.

**Comment by dangowrt** [comment]
the pjproject is also still behavi-ng weirdly on some platforms, see
http://buildbot.openwrt.org:8010/broken_packages/mvebu/pjproject/compile.txt
that causes asterisk-13.x to fail.

**Comment by dangowrt** [comment]
See https://github.com/openwrt/telephony/issues/16

**Comment by jslachta** [comment]
@blogic What is the status of build breakage?

**Comment by jslachta** [comment]
@blogic ping

**Comment by dangowrt** [comment]
I checked the most recent buildbot results on different targets:

Still major breakage on arm64:
http://buildbot.openwrt.org:8010/broken_packages/arm64/

Freeswitch is broken at least on
http://buildbot.openwrt.org:8010/broken_packages/mpc85xx/
and maybe others...

Besides that thinks look good, at least on the surface :)

http://buildbot.openwrt.org:8010/broken_packages/ar71xx/
http://buildbot.openwrt.org:8010/broken_packages/ramips.mt7628/
http://buildbot.openwrt.org:8010/broken_packages/brcm63xx/
...
http://buildbot.openwrt.org:8010/broken_packages/kirkwood/
http://buildbot.openwrt.org:8010/broken_packages/netlogic/
...
http://buildbot.openwrt.org:8010/broken_packages/x86/

**Comment by plntyk** [comment]
- many arm64 breakage is because of PostgreSQL 9.0.x not supporting aarch64 / arm64 ( afaik some google suggested that 9.2 started support )

PostgreSQL 9.4(.1) is available and supports aarch64/arm64
BUT 9.0.x still is maintained and gets security updates

all affected packages:
- asterisk-1.8.x/	-> postgresql
- asterisk-11.x/	-> postgresql
- asterisk-13.x/	-> postgresql
- asterisk-g72x/	-> asterisk error -> pgsql
- chan-sccp-b		-> asterisk -> pgsql
- collectd		-> postgresql
- freeeradius2		-> postgresql
- kamaillo		-> postgresql
- libdbi-drivers	-> postgresql
- php5			-> postgresql
- ulogd			-> postgresql

with 9.4 pgsql asterisk does seem to compile fine

**Comment by plntyk** [comment]
feel free to test the patch for postgresql 9.4 in that referenced ticket

**Comment by micmac1** [comment]
Hello @blogic 

Fixes have been put in trunk and the the mentioned packages compile fine again (freeswitch has freeswitch-stable as drop-in replacement). Can you please consider closing this issue?

Regards,
Sebastian

**Comment by micmac1** [comment]
I think the telephony feed is in pretty good state today and this issue should be closed.
