### ISSUE TITLE
freeswitch fails to build

### ISSUE THREAD

**Issue by blogic** [openwrt/telephony#28]
checking for libmemcached >= 0.31... no
checking openssl/tls1.h usability... no
checking openssl/tls1.h presence... yes
configure: WARNING: openssl/tls1.h: present but cannot be compiled
configure: WARNING: openssl/tls1.h:     check for missing prerequisite headers?
configure: WARNING: openssl/tls1.h: see the Autoconf documentation
configure: WARNING: openssl/tls1.h:     section "Present But Cannot Be Compiled"
configure: WARNING: openssl/tls1.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------- ##
configure: WARNING:     ## Report this to bugs@freeswitch.org ##
configure: WARNING:     ## ---------------------------------- ##
checking for openssl/tls1.h... no
configure: WARNING: OpenSSL include files were not found
configure: error: OpenSSL >= 1.0.1e and associated developement headers required

**Comment by moonman** [comment]
Posted in the wrong feed about this too https://github.com/openwrt/packages/issues/1122 just confirming the issue here.

**Comment by BlueMax** [comment]
Freeswitch feed package has been updated to new HEAD (thx Mazi Lo) and the above bug has been patched upstream. But there are more issues. Now i get: `checking whether TCP_NODELAY and TCP_CORK can both be enabled... configure: error: in '/home/bluemax/openwrt/trunk/build_dir/target-i386_i486_uClibc-0.9.33.2/freeswitch-1.5.14/libs/apr':
configure: error: cannot run test program while cross compiling`.

**Comment by BlueMax** [comment]
I've created two patches and now it builds properly here. Someone validate them please.
http://pastebin.com/J2vHstzW
http://pastebin.com/N5LTgh0n

**Comment by dangowrt** [comment]
@BlueMax : :+1: . give meaningful filenames to both patches and add them to net/freeswitch/patches/ in a single commit (including description and SoB line), then pull request. thanks!

**Comment by BlueMax** [comment]
Sent in 2 pull requests. It builds again.
I will test it tomorrow with FusionPBX.

**Comment by jslachta** [comment]
This should be fixed. @BlueMax thank you for the PR.

**Comment by jslachta** [comment]
@blogic Please reopen if the issue persists.
