### ISSUE TITLE
FreeSWITCH: Optional packages do not build

### ISSUE THREAD

**Issue by BlueMax** [openwrt/telephony#31]
The standard configuration can be built but optional packages are still incomplete. I've quickly seen 'celt' needs 'ogg.h'. Probably more.

**Comment by micmac1** [comment]
Hello @BlueMax 

Please try freeswitch-stable and consider closing this issue. Thanks!

Regards,
Sebastian

**Comment by jslachta** [comment]
Hi @BlueMax ,

the freeswitch package is currently available as freeswitch and freeswitch-stable package in telephony repository. If you are still experiencing this issue, please create a new ticket. I am closing this issue as it is obsolete.

Thank you.
