### ISSUE TITLE
freeswitch error

### ISSUE THREAD

**Issue by taeasy** [openwrt/telephony#35]
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/bin/i486-openwrt-linux-uclibc-gcc accepts -g... yes
checking for /home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/bin/i486-openwrt-linux-uclibc-gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/bin/i486-openwrt-linux-uclibc-gcc -E
checking for grep that handles long lines and -e... /home/main/x86/staging_dir/host/bin/grep
checking for egrep... /home/main/x86/staging_dir/host/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for ldap support...
checking for default DBM... sdbm (default)
checking for dbd/apr_dbd_mysql.c... configure: error: cannot check for file existence when cross compiling
configure: error: ./configure.gnu failed for libs/apr-util
make[3]: **\* [/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/freeswitch-1.5.14/.configured_yyyyyynnyynnnynnyynynnnyyynynyyyyyyyyyyyyynyynyyyyyyyyyyyyyyyyynyyyyyyynyynyyyynynynyyyynyyyyyyynnnnyyyyynnnynnyyyyynyyyyyyyyyyyyyyyyynyyyyyyyyynnnnnnyyyyyyynynyyyyyyyynynyyyyyyyyn] Error 1
make[3]: Leaving directory `/home/main/x86/feeds/telephony/net/freeswitch'
make[2]: *** [package/feeds/telephony/freeswitch/compile] Error 2
make[2]: Leaving directory`/home/main/x86'
make[1]: **\* [/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/x86'
make: **\* [world]  Error 2

**Comment by micmac1** [comment]
Hello @taeasy 

Can you please consider closing this issue with freeswitch-stable now in trunk?

Kind regards,
Sebastian

**Comment by jslachta** [comment]
Hi @taeasy ,

the freeswitch package is currently available as freeswitch and freeswitch-stable package in telephony repository. If you are still experiencing this issue, please create a new ticket. I am closing this issue as it is obsolete.

Thank you.
