### ISSUE TITLE
[openwrt-18.06] freeswitch: Package update errors

### ISSUE THREAD

**Issue by NickSchaf** [openwrt/telephony#364]
Maintainer: Unknown
Environment: OpenWrt 18.06

Description:
When updating feeds (`./scripts/feeds/update -a`) on a clean (fresh clone) build environment, the freeswitch and freeswitch-stable package Makefiles cause errors:

```
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git;openwrt-18.06' ...
Cloning into './feeds/telephony'...
remote: Counting objects: 259, done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 259 (delta 21), reused 29 (delta 0)
Receiving objects: 100% (259/259), 169.49 KiB | 0 bytes/s, done.
Resolving deltas: 100% (21/21), done.
Checking connectivity... done.
Create index file './feeds/telephony.index' 
ERROR: please fix feeds/telephony/net/freeswitch/Makefile - see logs/feeds/telephony/net/freeswitch/dump.txt for details
ERROR: please fix feeds/telephony/net/freeswitch-stable/Makefile - see logs/feeds/telephony/net/freeswitch-stable/dump.txt for details
Collecting package info: done
Collecting target info: done
```

First line of logs/feeds/telephony/net/freeswitch/dump.txt:
```
Makefile:243: /projects/openwrt-18.06/feeds/packages/lang/perl/perlmod.mk:4: ../perl/perlver.mk: No such file or directory
```
(logs/feeds/telephony/net/freeswitch/dump.txt has the same)

fec346da37ce27b4a27f751425980126114bd3ca added the include for perlmod.mk.

As a test, I removed the telephony feed (deleted all telephony files/dirs in feeds) and updated again, knowing that the other feeds were still up-to-date and perlmod.mk and perlver.mk were present.  The same errors were observed again.

**Comment by micmac1** [comment]
I think that's actually due to the recent perl commit and resolves itself when you update again.

Regards,
Seb

**Comment by micmac1** [comment]
Little bit of explanation: the version mk is new and won't be available until it's actually installed after you update.

**Comment by micmac1** [comment]
Am August 15, 2018 9:56:16 PM UTC schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>Little bit of explanation: the version mk is new and won't be available
>until it's actually installed after you update.

No, you're correct. Something goes wrong now. I'll check it out tonight.

Regards,
Seb

**Comment by NickSchaf** [comment]
> Little bit of explanation: the version mk is new and won't be available until it's actually installed after you update.

To test that, I followed the same steps as previously, except I installed all packages after updating.  Then I blew away everything telephony in feeds and updated it again, only to get the same errors again.

**Comment by Dirtylife** [comment]
Hello micmac1,

Sorry for writing in a closed issue.
But on my machine i have the same problem.

If i hit "./scripts/feeds update telephony" i get:
`Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
Klone nach './feeds/telephony' ...
remote: Enumerating objects: 256, done.
remote: Counting objects: 100% (256/256), done.
remote: Compressing objects: 100% (244/244), done.
remote: Total 256 (delta 21), reused 29 (delta 0)
Empfange Objekte: 100% (256/256), 165.08 KiB | 3.93 MiB/s, Fertig.
Löse Unterschiede auf: 100% (21/21), Fertig.
Create index file './feeds/telephony.index' 
ERROR: please fix feeds/telephony/net/freeswitch/Makefile - see logs/feeds/telephony/net/freeswitch/dump.txt for details
Collecting package info: done
Collecting target info: done`

I think the "error" lies in the file "perlmod.mk"

if i switch the line
`include ../perl/perlver.mk`
to a static link:
`include /home/mario/OpenWRT/openwrt/feeds/packages/lang/perl/perlver.mk`

it works without failure...

or am i too noob and the fault is elsewhere :-)

Greetings,
Dirtylife

**Comment by micmac1** [comment]
Hello Dirtylife,

I think it's fair to say that the freeswitch package is unmaintained. I'll raise an issue and see if we can remove it from the tree.

Regards,
Seb

**Comment by jslachta** [comment]
Hi @micmac1,

I am going to contact Mazi Lo. I would also suggest removing this unmaintained package.

Jiri

**Comment by Dirtylife** [comment]
Hi,

No problem, thank you.
My intention was to draw attention to the mistake.
I dont need the freeswitch package...

Greetings,
Dirtylife

**Comment by zaraijamel** [comment]
Hi i faced the same issue. 
`/openWisp2/openwrt$ ./scripts/feeds install -a
ERROR: please fix package/feeds/telephony/freeswitch/Makefile - see logs/package/feeds/telephony/freeswitch/dump.txt for details
Collecting package info: done
`
It was fixed just uninstall freeswitch after i have got the error
` ./scripts/feeds uninstall  freeswitch
Uninstalling package 'freeswitch'
`
 and reinstall once again.
`./scripts/feeds install -a
Collecting package info: done
Installing all packages from feed openwisp.
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
`

**Comment by arvati** [comment]
Error in file:
feeds/packages/lang/perl/perlmod.mk

It is:
include ../perl/perlver.mk

Should be:
include ./perlver.mk

**Comment by zhangguanzhang** [comment]
```
sed -ri 's#\.\./perl/perlver.mk#../perlver.mk#' feeds/packages/lang/perl/perlmod.mk
```
