### ISSUE TITLE
asterisk fills up rootfs

### ISSUE THREAD

**Issue by dangowrt** [openwrt/telephony#38]
/var/lib/asterisk being a symlink to /usr/lib/asterisk which is usually located on the jffs2 overlay is probably not such a good idea. on my systems this ends up with astdb growing until the flash is full and the system first becomes unresponsive and (sometimes after days) ends up doing a firstboot/factory-reset...
Probably we should have /var/lib/asterisk in tmpfs and explicitely decide if anything should be stored permanently (such as /var/lib/asterisk/keys/*)

**Comment by dangowrt** [comment]
From my observation it could be that OpenWrt's Out-Of-Memory behaviour is falling back to swap onto the SPI flash (!).

**Comment by micmac1** [comment]
Hello @dangowrt 

with /var now pointing to /tmp in LEDE, can you please consider closing this issue?

Kind regards,
Sebastian

**Comment by micmac1** [comment]
I think this is fixed and this issue should be closed.
