### ISSUE TITLE
siproxd-mod-regex UCI list vs entry processing

### ISSUE THREAD

**Issue by biuklija** [openwrt/telephony#384]
-------------------------------

Maintainer: @guidosarducci 
Environment: OpenWrt 18.06.1 r7258-5eb055306f

Description: UCI processes siproxd regex entries as a list, they should be processed as entries

siproxd expects regex replace entries as follows: 
```
plugin_regex_desc    = A
plugin_regex_pattern = ^(sips?:)00
plugin_regex_replace = \1+

plugin_regex_desc    = B
plugin_regex_pattern = ^(sips?:)0
plugin_regex_replace = \1+385

plugin_regex_desc    = C
plugin_regex_pattern = ^(sips?:)
plugin_regex_replace = \1+38531
```

However, since there is no entry support for the plugins, the following blocks in /etc/config/siproxd:

```
list plugin_regex_desc  A
list plugin_regex_pattern ^(sips?:)00
list plugin_regex_replace \1+

list plugin_regex_desc B
list plugin_regex_pattern ^(sips?:)0
list plugin_regex_replace \1+385

list plugin_regex_desc  C
list plugin_regex_pattern  ^(sips?:)
list plugin_regex_replace \1+38531	
```
get sorted in /var/etc/siproxd/siproxd-general.conf

```
plugin_regex_desc = A B C
plugin_regex_pattern = ^(sips?:)00
plugin_regex_pattern = ^(sips?:)0
plugin_regex_pattern = ^(sips?:)
plugin_regex_replace = 1+
plugin_regex_replace = 1+385
plugin_regex_replace = 1+38531
```

**Comment by micmac1** [comment]
Hello Ivan,

I think this is a long-standing issue. I tried oldest init script in github from commit 100f27f3bb693522e8f2617f865e6a13aa406cb4 and it wrote
```
plugin_regex_desc = A
plugin_regex_desc = B
plugin_regex_desc = C
plugin_regex_pattern = ^(sips?:)00
plugin_regex_pattern = ^(sips?:)0
plugin_regex_pattern = ^(sips?:)
plugin_regex_replace = \1+
plugin_regex_replace = \1+385
plugin_regex_replace = \1+38531
```
into /var/etc/siproxd-general. With current init script I get the same in in /var/etc/siproxd/siproxd-general.conf.

When I trace the init script it's visible that

`config_load 'siproxd'`

is causing the wrong order.

```
config siproxd '"'"'general'"'"'              
        option interface_inbound '"'"'lan'"'"'
        option interface_outbound '"'"'wan'"'"'
        list plugin_regex_desc '"'"'A'"'"'     
        list plugin_regex_desc '"'"'B'"'"'     
        list plugin_regex_desc '"'"'C'"'"'     
        list plugin_regex_pattern '"'"'^(sips?:)00'"'"'
        list plugin_regex_pattern '"'"'^(sips?:)0'"'"' 
        list plugin_regex_pattern '"'"'^(sips?:)'"'"'  
        list plugin_regex_replace '"'"'\1+'"'"'        
        list plugin_regex_replace '"'"'\1+385'"'"'     
        list plugin_regex_replace '"'"'\1+38531'"'"
```

So I reckon it doesn't matter how you order the lines in /etc/config/siproxd, they'll always end up like this. And we can't blame config_load() for this - the uci entries are line based, nothing is saying that it needs to treat all lines in the order presented.

I think there are three options:

1) update init script to somehow make these more complicated (multi-line) config entries work
2) add a mechanism to include certain user config verbatim in the generated config file (like, a check in the init script that inserts content of /etc/siproxd.local.cfg if the file exists)
3)  get rid of the UCI calls that generate the config file and instead just install a standard config file for siproxd and just use the uci settings only for startup params

I think @guidosarducci wouldn't like option 3, so let's just assume I didn't write the third option down ;-)

Kind regards,
Seb

**Comment by biuklija** [comment]
You are right, this is a long-standing issue (i.e. it never worked properly), which is why, for practical purposes, I use a flat .conf file for siproxd and completely do away with UCI (I run siproxd from rc.local with the static config file). However, for the sake of unifying the configuration, which is the whole point of UCI, I believe the first option you suggested would be preferable as UCI already has the necessary mechanisms to deal with this. mod-regex plugin configuration entries should be treated the same as firewall rules, for example. 

Sincerely,
Ivan

**Comment by micmac1** [comment]
Hi Ivan,

Do you know if there is a use case where one would run multiple instances of siproxd on the same router?

Regards,
Seb

**Comment by biuklija** [comment]
Hi Seb,

I can imagine such a case, but it would be have to be **extremely** specific, for example if someone required different configurations for different IP phones and/or VOIP providers (e.g. if a certain SIP account functioned only on a specific outbound interface), 
My own case is is fairly specific to begin with - I am forced to use the regex replace plugin because my VOIP phone lacks a dial plan option which would ensure that local and domestic numbers without area/country code are dialled properly.  

Sincerely,
Ivan

**Comment by micmac1** [comment]
Morning Ivan,

Thanks for your feedback. I'll take a swing at trying to make it work.

Kind regards,
Seb

**Comment by micmac1** [comment]
Hello @biuklija and @guidosarducci 

Thanks for clarifying this. I've raised a pull request to add the comments for the regex plugin to the existing UCI config file as suggested.

Please consider closing this issue if you're OK with this.

Best regards,
Sebastian

**Comment by guidosarducci** [comment]
@biuklija Thanks very much for the clear and systematic testing! It really helps in troubleshooting things.

Kind regards,
Tony
