### ISSUE TITLE
iksemel fails with gnutls 3.4.0

### ISSUE THREAD

**Issue by plntyk** [openwrt/telephony#39]
packages repo updated gnutls to 3.4.0 this leads to a build error:

```
../src/.libs/libiksemel.so: undefined reference to `gnutls_kx_set_priority'
../src/.libs/libiksemel.so: undefined reference to `gnutls_compression_set_priority'
../src/.libs/libiksemel.so: undefined reference to `gnutls_protocol_set_priority'
../src/.libs/libiksemel.so: undefined reference to `gnutls_cipher_set_priority'
../src/.libs/libiksemel.so: undefined reference to `gnutls_mac_set_priority'
```

These functions were marked as deprecated in gnutls 2.12
and removed now in 3.4.

the same bug is filed in debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782820

**Comment by jslachta** [comment]
Iksemel package is marked as broken. I disabled all asterisk modules depending on it to prevent build breakage.

**Comment by jpap** [comment]
I've created a pull request that fixes this issue and restores Google Voice trunks in Asterisk; see #83.

**Comment by jslachta** [comment]
Closing this ticket since it is out of date, see #83
