### ISSUE TITLE
Asterisk-11.x fails to compile

### ISSUE THREAD

**Issue by enigmagroup** [openwrt/telephony#41]
```
configure.ac:104: the top level
configure.ac:111: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:111: the top level
configure: loading site script /home/x/openwrt-banana/include/site/arm
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/x/openwrt-banana/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/asterisk-11.17.1/menuselect':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:320: recipe for target '/home/x/openwrt-banana/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/asterisk-11.17.1/.configured_yyyyyyyyyy' failed
make[2]: *** [/home/x/openwrt-banana/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/asterisk-11.17.1/.configured_yyyyyyyyyy] Error 77
make[2]: Leaving directory '/home/x/openwrt-banana/feeds/telephony/net/asterisk-11.x'
package/Makefile:183: recipe for target 'package/feeds/telephony/asterisk-11.x/compile' failed
make[1]: *** [package/feeds/telephony/asterisk-11.x/compile] Error 2
make[1]: Leaving directory '/home/x/openwrt-banana'
/home/x/openwrt-banana/include/toplevel.mk:181: recipe for target 'package/asterisk-11.x/compile' failed
make: *** [package/asterisk-11.x/compile] Error 2
```

Tested with raspi, banana pi and x86.

**Comment by jslachta** [comment]
I have not been able to replicate your issue. Would you be so kind to paste your .config and your distro?

**Comment by enigmagroup** [comment]
Yes: https://ezcrypt.it/AsAn#XLN0mYpFGI9KKXCtDwTBRQBe

Architecture of my build system is:  Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux

**Comment by enigmagroup** [comment]
My OS Version is Debian 8 (Jessie). I have this build error even with a fresh ```git clone git.openwrt.org``` (no custom feeds).

Maybe you can set up a VM with that Debian version to replicate the issue?

**Comment by jslachta** [comment]
Since there are several more problems with ast11, I reverted the update to 11.17.1 and fixed the open CVE for 11.16.0. It should be currently fixed.

**Comment by jslachta** [comment]
Please reopen if the issue persists.

**Comment by enigmagroup** [comment]
Thanks a lot! I was afk this weekend and will test it soon(ish).

**Comment by vteccomm** [comment]
hi 
 i am newbie to building openwrt. My Os is ubuntu 14.04 Desktop 64bit 
git clone git.openwrt.org
trying to build asterisk 11
 
checking for a sed that does not truncate output... /home/uadmin/openwrt/staging_dir/host/bin/sed
checking for xml2-config... /home/uadmin/openwrt/staging_dir/target-mips_34kc_musl-1.1.12/host/bin/xml2-config
configure: error: Could not find required 'Libxml2' development package
make[3]: *** [/home/uadmin/openwrt/build_dir/target-mips_34kc_musl-1.1.12/asterisk-11.20.0/.configured_yyyyyyyy] Error 1
make[3]: Leaving directory `/home/uadmin/openwrt/feeds/telephony/net/asterisk-11.x'
make[2]: *** [package/feeds/telephony/asterisk-11.x/compile] Error 2
make[2]: Leaving directory `/home/uadmin/openwrt'
make[1]: *** [/home/uadmin/openwrt/staging_dir/target-mips_34kc_musl-1.1.12/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/uadmin/openwrt'
make: *** [world] Error 2


i don't know how to build libxml2 development package 
can u plz help
