### ISSUE TITLE
freeswitch-stable: add mod_signalwire

### ISSUE THREAD

**Issue by skyblaster** [openwrt/telephony#413]
Hello @micmac1,
Just checking to see if it is possible to add mod_signalwire?
I see it requires the libks package found here: https://github.com/signalwire/libks

**Comment by micmac1** [comment]
On Sat, Mar 09, 2019 at 08:10:35PM -0800, skyblaster wrote:
> Hello @micmac1,
> Just checking to see if it is possible to add mod_signalwire?
> I see it requires the libks package found here: https://github.com/signalwire/libks

Hello,

Possibly. It also requires signalwire-client-c. Likely none of them are
in OpenWrt yet.

I'm not against adding this in general. But this would add more workload
to maintain and I think the demand for all of this in the OpenWrt crowd
is likely negligible.

Kind regards,
Seb

**Comment by skyblaster** [comment]
Yes, definitely a low priority task if you choose to take it on.
I was only looking to test out the service.

I attempted to compile libks but ran into the following error:
```
CMake Error at CMakeLists.txt:239 (add_library):
  Target "ks" links to target "LIBM::LIBM" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```
Thanks!

**Comment by micmac1** [comment]
Added to master and 19.07. I'll watch the build bots in the coming days if there's anything unexpected happening. If yes I'll fix.

This issue I'll close. Thanks!

Seb
