### ISSUE TITLE
dahdi-linux: build fail in kernel 4.19

### ISSUE THREAD

**Issue by EXSERENS** [openwrt/telephony#427]
Maintainer: Vittorio Gambaletta <openwrt@vittgam.net>
Environment: armv7-a WRT3200ACM snapshot kernel-4.19

Description:
dahdi-linux will build fail in any kernel 4.19 compile. maybe upgrade to 3.0.0 will solve the problem?

**Comment by micmac1** [comment]
It probably would. But I think we can't right now. We need to wait until kernels >=4,15 are built by default on (all?) our target. See [DAHLIN-366](https://issues.asterisk.org/jira/browse/DAHLIN-366). Quote: "DAHDI 3.0 will only compile on kernels 4.15 or newer."

Right now the highest default kernel is 4.14 in OpenWrt and I think OpenWrt is planning a release this year. If we'd upgrade to dahdi-linux 3.0.0 now all default builds would fail.

**Comment by micmac1** [comment]
If you want to build dahdi-linux against 4.19 right now I suggest that you upgrade to 3.0.0 locally.
