### ISSUE TITLE
asterisk16-pbx-lua is missing dependency for liblua5.3.

### ISSUE THREAD

**Issue by BKPepe** [openwrt/telephony#441]
Hi guys,

`asterisk16-pbx-lua` is failing on master builds.

Faillog from buildbot:
```
Package asterisk16-pbx-lua is missing dependencies for the following libraries:
liblua5.3.so.0.0.0
Makefile:923: recipe for target '/builder/arm_cortex-a9_vfpv3/build/sdk/bin/packages/arm_cortex-a9_vfpv3/telephony/asterisk16-pbx-lua_16.3.0-4_arm_cortex-a9_vfpv3.ipk' failed
make[3]: *** [/builder/arm_cortex-a9_vfpv3/build/sdk/bin/packages/arm_cortex-a9_vfpv3/telephony/asterisk16-pbx-lua_16.3.0-4_arm_cortex-a9_vfpv3.ipk] Error 1
time: package/feeds/telephony/asterisk-16.x/compile#479.90#104.89#863.82
```

The full compile logs can be found here:
https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9_vfpv3/telephony/asterisk-16.x/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a72/telephony/asterisk-16.x/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/powerpc_8540/telephony/asterisk-16.x/compile.txt

**Comment by micmac1** [comment]
lua now has multiple versions, liblua and liblua5.3. Asterisk seems to support 5.3. I think we need to upgrade the dep to the latter in master.
