### ISSUE TITLE
freeswitch: build on Mac OS X

### ISSUE THREAD

**Issue by sageahn** [openwrt/telephony#47]
Hi,

I am trying to build OpenWrt on my macbookpro (Mac OS X 10.10.3). the openwrt itself is ok to build it However, when I enable FreeSwitch, the perl for target cannot be built. I know it is not the telephony related. However, I don't know other channel to report this.
Please let me know the right place to discuss if this repo/github is not.

Thanks in advance.

**Comment by jslachta** [comment]
This is the right place to discuss it. I am not maintaining freeswitch package, but I can inform the maintainer about the package breakage. Please, provide the build log on pastebin or github gists.

**Comment by sageahn** [comment]
Thanks,

the logs are attached below. the target is x86 and clone the upstream repo then just enable to build FreeSwitch alone. that's the only change from the upstream repo. (also enable to build VirtualBox image creation)

----------------
i486-openwrt-linux-uclibc-gcc -c -DPERL_CORE -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -I/Volumes/OpenWrt/owrt_upstream/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/Volumes/OpenWrt/owrt_upstream/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/Volumes/OpenWrt/owrt_upstream/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/Volumes/OpenWrt/owrt_upstream/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include -O2 -Wall -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings -fPIC caretx.c
rm: miniperl: No such file or directory
make[4]: [lib/buildcustomize.pl] Error 1 (ignored)
/bin/ln -s /Volumes/OpenWrt/owrt_upstream/staging_dir/host/usr/bin/perl miniperl
LD_LIBRARY_PATH=/Volumes/OpenWrt/owrt_upstream/build_dir/target\-i386_i486_uClibc\-0.9.33.2/perl/perl\-5.20.2:/lib ./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Please run make minitest; exit 1'
Can't load module File::Glob, dynamic loading not available in this perl.
  (You may need to build a new perl executable which either supports
  dynamic loading or has the File::Glob module statically linked into it.)
at -e line 1.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
Failed to build miniperl. Please run make minitest
make[4]: *** [lib/buildcustomize.pl] Error 1
make[3]: *** [/Volumes/OpenWrt/owrt_upstream/build_dir/target-i386_i486_uClibc-0.9.33.2/perl/perl-5.20.2/.built] Error 2
make[3]: Leaving directory `/Volumes/OpenWrt/owrt_upstream/feeds/packages/lang/perl'
make[2]: *** [package/feeds/packages/perl/compile] Error 2
make[2]: Leaving directory `/Volumes/OpenWrt/owrt_upstream'
make[1]: *** [/Volumes/OpenWrt/owrt_upstream/staging_dir/target-i386_i486_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/Volumes/OpenWrt/owrt_upstream'
make: *** [world] Error 2
MacBook-Pro:owrt_upstream sage$ cd feeds/packages/lang/perl

**Comment by micmac1** [comment]
Hello @sageahn 

Can you please try trunk and try to build freeswitch-stable on MAC? If it works please consider closing this issue. If it fails I'd be interested in the logs.

Thanks!
Sebastian

**Comment by jslachta** [comment]
Hi @sageahn,

the freeswitch package is currently available as freeswitch and freeswitch-stable package in telephony repository. If you are still experiencing this issue, please fill a new ticket. I am closing this issue as it is obsolete.

Thank you.
