### ISSUE TITLE
freeswitch-stable does not compile without deprecated OpenSSL APIs

### ISSUE THREAD

**Issue by neheb** [openwrt/telephony#484]
It errors with

```
OpenSSL >= 1.0.1e and associated developement headers required
```

From looking at the configure script, it checks DTLSv1_2_method and DTLSv1_method, which are both deprecated.

It also checks SSL_CTX_set_tlsext_use_srtp , which I see to have disabled in my libssl config. The code in openssl/srtp.h is:

```
# ifndef OPENSSL_NO_SRTP

__owur int SSL_CTX_set_tlsext_use_srtp(SSL_CTX *ctx, const char *profiles);
```

Looks like it needs an @OPENSSL_WITH_SRP dependency.

Maintainer: @micmac1 
Environment: master

**Comment by micmac1** [comment]
Hello Rosen,

Thanks for the report. Indeed this doesn't work without the deprecated symbols. I've updated the depends to reflect that.

This is not an OpenWrt specific issue, though, it's a general upstream issue, and one that requires the skills and some bigger effort to address. As such other than updating our depends I don't have a Todo here.

I'm not suggesting that somebody raises this issue upstream. I don't think that would speed anything up. I'm sure upstream will fix this when they see the need arise, sooner or later.

Regarding SEP, it's not the same as SRTP.

Kind regards,
Seb

**Comment by micmac1** [comment]
I raised an issue upstream [here](https://github.com/signalwire/freeswitch/issues/105). If anybody wants to they can subscribe to that issue.
