### ISSUE TITLE
asterisk16-pjsip: ERROR: res_pjsip/config_system.c:261 system_create_resolver_and_set_nameservers: There are no local system nameservers configured, resorting to system resolution

### ISSUE THREAD

**Issue by 532910** [openwrt/telephony#516]
Maintainer: @jslachta
Environment: 19.07.2 / sunxi / cortexa53 / sun50i-h5-nanopi-neo2
Description:
`CLI> core restart now` gives:
```
 Loading res_pjsip.so.
    -- Local IPv4 address determined to be: <IP>
    -- Local IPv6 address determined to be: <IP>
ERROR: res_pjsip/config_system.c:261 system_create_resolver_and_set_nameservers: There are no local system nameservers configured, resorting to system resolution
  == Manager registered action PJSIPShowEndpoints
  == Manager registered action PJSIPShowEndpoint
  == Manager registered action PJSIPShowAuths
  == Manager registered action PJSIPShowAors
  == 'UDP+IPv4' is an available SIP transport
  == 'TCP+IPv4' is an available SIP transport
  == 'TLS+IPv4' is not an available SIP transport, disabling resolver support for it
  == 'UDP+IPv6' is not an available SIP transport, disabling resolver support for it
  == 'TCP+IPv6' is not an available SIP transport, disabling resolver support for it
  == 'TLS+IPv6' is not an available SIP transport, disabling resolver support for it
ERROR: res_pjsip/config_system.c:261 system_create_resolver_and_set_nameservers: There are no local system nameservers configured, resorting to system resolution
```

But the same asterisk config works without errors on debian buster.

`/etc/asterisk/modules.conf`:
```
[modules] 
autoload=no 
...
load => func_sorcery
load => res_sorcery_astdb
load => res_sorcery_config
load => res_sorcery_memory
load => res_sorcery_memory_cache
load => res_sorcery_realtime

load => chan_pjsip
load => func_pjsip_aor
load => func_pjsip_contact
load => func_pjsip_endpoint
load => res_pjproject
load => res_pjsip
load => res_pjsip_acl
load => res_pjsip_authenticator_digest
load => res_pjsip_caller_id
load => res_pjsip_config_wizard
load => res_pjsip_dialog_info_body_generator
load => res_pjsip_diversion
load => res_pjsip_dlg_options
load => res_pjsip_dtmf_info
load => res_pjsip_empty_info
;load => res_pjsip_endpoint_identifier_anonymous
load => res_pjsip_endpoint_identifier_ip
load => res_pjsip_endpoint_identifier_user
load => res_pjsip_exten_state
load => res_pjsip_header_funcs
load => res_pjsip_history
load => res_pjsip_logger
load => res_pjsip_messaging
load => res_pjsip_mwi
load => res_pjsip_mwi_body_generator
load => res_pjsip_nat
load => res_pjsip_one_touch_record_info
load => res_pjsip_outbound_authenticator_digest
load => res_pjsip_outbound_publish
load => res_pjsip_outbound_registration
load => res_pjsip_path
load => res_pjsip_pidf_body_generator
load => res_pjsip_pidf_digium_body_supplement
load => res_pjsip_pidf_eyebeam_body_supplement
load => res_pjsip_publish_asterisk
load => res_pjsip_pubsub
load => res_pjsip_refer
load => res_pjsip_registrar
load => res_pjsip_rfc3326
load => res_pjsip_sdp_rtp
load => res_pjsip_send_to_voicemail
load => res_pjsip_session
load => res_pjsip_sips_contact
load => res_pjsip_xpidf_body_generator
```

**Comment by 532910** [comment]
Enabling dnsmgr changes nothing.

```
# cat /etc/asterisk/dnsmgr.conf 
[general]
enable=yes
```

**Comment by micmac1** [comment]
musl doesn't provide this functionality, which is why asterisk cannot retrieve the name servers. If you want this to work you need to select a different libc that supports this. This is not a packaging bug.

**Comment by 532910** [comment]
Installing libc package will not solve this, right?
OK, really I don't need resolver and IP addresses are used in pjsip.conf, why this error is shown and is there a way to load res_pjsip.so without errors? Is asterisk should be compiled or patches so to not use this call?

**Comment by micmac1** [comment]
>Installing libc package will not solve this, right?

No, you would have to select a different libc in menuconfig and compile your firmware and all packages with it.

>OK, really I don't need resolver and IP addresses are used in
>pjsip.conf, why this error is shown and is there a way to load
>res_pjsip.so without errors? Is asterisk should be compiled or patches
>so to not use this call?

Patching this out would remove it for the people who choose a different libc. So no, not possible.

After the error pjsip just keeps on using A and AAAA records from system resolver.

**Comment by micmac1** [comment]
> >OK, really I don't need resolver and IP addresses are used in
> >pjsip.conf, why this error is shown and is there a way to load
> >res_pjsip.so without errors? Is asterisk should be compiled or patches
> >so to not use this call?
>
> Patching this out would remove it for the people who choose a different libc. So no, not possible.
>
> After the error pjsip just keeps on using A and AAAA records from system resolver.

Also, the people using musl (or any other libc that doesn't support
this) and want to use this feature would wonder why it doesn't work
although everything seems OK (no error because patched out). That would
complicate it for them.

**Comment by jslachta** [comment]
Thank you, Sebastian, for your explanation. This is not a packaging bug.
