### ISSUE TITLE
asterisk: add more sounds encodings and languages

### ISSUE THREAD

**Issue by 532910** [openwrt/telephony#517]
Maintainer: @jslachta
Environment: 19.07.2
Description:
Right now there is only asterisk16-sounds that provides gsm encoded english voice files.
Please add more encodings (g722, and possibly wav) and languages.

Debian's [asterisk-core-sounds](https://tracker.debian.org/pkg/asterisk-core-sounds) provides en, es, fr, it and ru in g722, gsm and wav.

https://downloads.asterisk.org/pub/telephony/sounds/
As I see there are also en-gb, en-au, en-nz, ja and sv in alaw, ulaw, g729, siren7, siren14.
Not sure about all encodings, but having all available languages in also alaw and ulaw will be nice.

**Comment by micmac1** [comment]
I can only offer my personal opinion here. I think sound packages are just a waste of space and bandwidth. Basically you have sound files, binaries. These files don't need to be compiled, unlike source code. The files can be used as they are. So there is no added benefit of packaging them (again) for OpenWrt. If anybody wants the sound files they can just grab the packages from upstream and extract the sound files to where they want them.

For the same reasons I also removed the freeswitch sound packs a while ago, in commit 4326f5c.

Kind regards,
Seb

**Comment by jslachta** [comment]
Hi Sergio @532910,

I understand that more sound packages might be useful, but as Sebastian said, it is just a waste of space and bandwith. This might be more useful on a full blown linux distribution, but not on OpenWrt.
