### ISSUE TITLE
Asterisk 16.6.1 problems running Asterisk as user "asterisk" , chan_lantiq.c:2116 load_module: lantiq TAPI device open function failed

### ISSUE THREAD

**Issue by jospezial** [openwrt/telephony#520]
Maintainer: @jslachta 
Environment: MIPS lantiq, VGV7510KW22 (o2 Box 6431), OpenWrt SNAPSHOT, r12903-c30220d458 built from openwrt git master

Works with root/root in /etc/config/asterisk .
Which device is used? Should the all vmmc devices have dialout as group?

```
# If you have problems running Asterisk as user "asterisk" we'd
        # like to hear from you. Please raise an issue at:
        # https://github.com/openwrt/telephony/issues
        option user 'asterisk'
#       option user 'root'
        option group 'asterisk'
#       option group 'root'
```
```
cat /etc/group 
root:x:0:
daemon:x:1:
adm:x:4:
mail:x:8:
dialout:x:20:asterisk
audio:x:29:
www-data:x:33:
ftp:x:55:
users:x:100:
network:x:101:
nogroup:x:65534:
asterisk:x:385:asterisk
dnsmasq:x:453:dnsmasq
lp:x:7:p910nd
```

```Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip.so => (Basic SIP resource)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_authenticator_digest.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_authenticator_digest.so => (PJSIP authentication resource)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_endpoint_identifier_ip.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_endpoint_identifier_ip.so => (PJSIP IP endpoint identifier)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_endpoint_identifier_user.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_endpoint_identifier_user.so => (PJSIP username endpoint identifier)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_registrar.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Manager registered action PJSIPShowRegistrationsInbound
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Manager registered action PJSIPShowRegistrationInboundContactStatuses
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_registrar.so => (PJSIP Registrar Support)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_crypto.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_crypto.so => (Cryptographic Digital Signatures)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_http_websocket.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == WebSocket registered sub-protocol 'echo'
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_http_websocket.so => (HTTP WebSocket Support)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_outbound_authenticator_digest.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_outbound_authenticator_digest.so => (PJSIP authentication resource)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_outbound_publish.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_outbound_publish.so => (PJSIP Outbound Publish Support)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_pubsub.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Manager registered action PJSIPShowSubscriptionsInbound
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Manager registered action PJSIPShowSubscriptionsOutbound
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Manager registered action PJSIPShowResourceLists
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_pubsub.so => (PJSIP event resource)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_xpidf_body_generator.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_xpidf_body_generator.so => (PJSIP Extension State PIDF Provider)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_rtp_asterisk.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Registered RTP engine 'asterisk'
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == RTP Allocating from port range 10000 -> 20000
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_rtp_asterisk.so => (Asterisk RTP Stack)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_dialog_info_body_generator.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_dialog_info_body_generator.so => (PJSIP Extension State Dialog Info+XML Provider)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_mwi_body_generator.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_mwi_body_generator.so => (PJSIP MWI resource)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_pidf_body_generator.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_pidf_body_generator.so => (PJSIP Extension State PIDF Provider)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_pidf_digium_body_supplement.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_pidf_digium_body_supplement.so => (PJSIP PIDF Digium presence supplement)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_pidf_eyebeam_body_supplement.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_pidf_eyebeam_body_supplement.so => (PJSIP PIDF Eyebeam supplement)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_exten_state.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_exten_state.so => (PJSIP Extension State Notifications)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_mwi.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_mwi.so => (PJSIP MWI resource)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading res_pjsip_publish_asterisk.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == res_pjsip_publish_asterisk.so => (PJSIP Asterisk Event PUBLISH Support)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:  Loading chan_lantiq.so.
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Registered channel type 'TAPI' (Lantiq TAPI Telephony API Driver)
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]: [Apr 10 13:26:01] ERROR[2257]: chan_lantiq.c:2116 load_module: lantiq TAPI device open function failed
Fri Apr 10 15:26:01 2020 daemon.info asterisk[2257]:   == Unregistered channel type 'TAPI'
```
```root@OpenWrt6431:~# ls -l /dev/
drwxr-xr-x    3 root     root            60 Jan  1  1970 bus
crw-------    1 root     root        5,   1 Jan  1  1970 console
crw-------    1 root     root       10,  62 Jan  1  1970 cpu_dma_latency
crw-------    1 root     root      109,   0 Apr 10 15:25 dsl_cpe_api0
crw-rw-rw-    1 root     root        1,   7 Jan  1  1970 full
crw-------    1 root     root       10, 229 Apr 10 15:25 fuse
crw-------    1 root     root      254,   0 Jan  1  1970 gpiochip0
crw-------    1 root     root       10,  63 Jan  1  1970 gptu
crw-------    1 root     root       10, 183 Jan  1  1970 hwrng
crw-------    1 root     root        1,  11 Jan  1  1970 kmsg
srw-rw-rw-    1 root     root             0 Apr 10 15:25 log
crw-------    1 root     root       10, 237 Apr 10 15:25 loop-control
brw-------    1 root     root        7,   0 Apr 10 15:25 loop0
brw-------    1 root     root        7,   1 Apr 10 15:25 loop1
brw-------    1 root     root        7,   2 Apr 10 15:25 loop2
brw-------    1 root     root        7,   3 Apr 10 15:25 loop3
brw-------    1 root     root        7,   4 Apr 10 15:25 loop4
brw-------    1 root     root        7,   5 Apr 10 15:25 loop5
brw-------    1 root     root        7,   6 Apr 10 15:25 loop6
brw-------    1 root     root        7,   7 Apr 10 15:25 loop7
drwxr-xr-x    2 root     root            60 Apr 10 15:25 mei_cpe
crw-------    1 root     root       90,   0 Jan  1  1970 mtd0
crw-------    1 root     root       90,   1 Jan  1  1970 mtd0ro
crw-------    1 root     root       90,   2 Jan  1  1970 mtd1
crw-------    1 root     root       90,   3 Jan  1  1970 mtd1ro
crw-------    1 root     root       90,   4 Jan  1  1970 mtd2
crw-------    1 root     root       90,   5 Jan  1  1970 mtd2ro
crw-------    1 root     root       90,   6 Jan  1  1970 mtd3
crw-------    1 root     root       90,   7 Jan  1  1970 mtd3ro
crw-------    1 root     root       90,   8 Jan  1  1970 mtd4
crw-------    1 root     root       90,   9 Jan  1  1970 mtd4ro
crw-------    1 root     root       90,  10 Jan  1  1970 mtd5
crw-------    1 root     root       90,  11 Jan  1  1970 mtd5ro
crw-------    1 root     root       90,  12 Jan  1  1970 mtd6
crw-------    1 root     root       90,  13 Jan  1  1970 mtd6ro
brw-------    1 root     root       31,   0 Jan  1  1970 mtdblock0
brw-------    1 root     root       31,   1 Jan  1  1970 mtdblock1
brw-------    1 root     root       31,   2 Jan  1  1970 mtdblock2
brw-------    1 root     root       31,   3 Jan  1  1970 mtdblock3
brw-------    1 root     root       31,   4 Jan  1  1970 mtdblock4
brw-------    1 root     root       31,   5 Jan  1  1970 mtdblock5
brw-------    1 root     root       31,   6 Jan  1  1970 mtdblock6
crw-rw-rw-    1 root     root        1,   3 Jan  1  1970 null
crw-------    1 root     root        1,   4 Jan  1  1970 port
crw-------    1 root     root      108,   0 Apr 10 15:25 ppp
crw-rw-rw-    1 root     root        5,   2 Apr 12 11:38 ptmx
drwxr-xr-x    2 root     root             0 Jan  1  1970 pts
crw-rw-rw-    1 root     root        1,   8 Jan  1  1970 random
crw-------    1 root     root      251,   0 Jan  1  1970 rtlx0
crw-------    1 root     root      251,   1 Jan  1  1970 rtlx1
crw-------    1 root     root      251,   2 Jan  1  1970 rtlx2
crw-------    1 root     root      251,   3 Jan  1  1970 rtlx3
crw-------    1 root     root      251,   4 Jan  1  1970 rtlx4
crw-------    1 root     root      251,   5 Jan  1  1970 rtlx5
crw-------    1 root     root      251,   6 Jan  1  1970 rtlx6
crw-------    1 root     root      251,   7 Jan  1  1970 rtlx7
lrwxrwxrwx    1 root     root             8 Jan  1  1970 shm -> /tmp/shm
crw-rw-rw-    1 root     root        5,   0 Jan  1  1970 tty
crw-rw----    1 root     dialout   250,   0 Apr 11 12:51 ttyLTQ0
crw-------    1 root     root       10,  61 Jan  1  1970 ubi_ctrl
crw-rw-rw-    1 root     root        1,   9 Jan  1  1970 urandom
crw-r--r--    1 root     root      122,  10 Apr 10 15:25 vmmc10
crw-r--r--    1 root     root      122,  11 Apr 10 15:25 vmmc11
crw-r--r--    1 root     root      122,  12 Apr 10 15:25 vmmc12
crw-r--r--    1 root     root      122,  13 Apr 10 15:25 vmmc13
crw-r--r--    1 root     root      122,  14 Apr 10 15:25 vmmc14
crw-r--r--    1 root     root      122,  15 Apr 10 15:25 vmmc15
crw-r--r--    1 root     root      122,  16 Apr 10 15:25 vmmc16
crw-r--r--    1 root     root      122,  17 Apr 10 15:25 vmmc17
crw-r--r--    1 root     root      122,  18 Apr 10 15:25 vmmc18
crw-------    1 root     root      252,   1 Jan  1  1970 vpe1
crw-------    1 root     root       10, 130 Jan  1  1970 watchdog
crw-------    1 root     root      253,   0 Jan  1  1970 watchdog0
crw-rw-rw-    1 root     root        1,   5 Jan  1  1970 zero```

**Comment by micmac1** [comment]
> Works with root/root in /etc/config/asterisk .
> Which device is used? Should the all vmmc devices have dialout as group?

I think this might work. The asterisk init script in master adds the
asterisk user to the dialout group already, as is visible in your
pastes.

/etc/init.d/vmmc sets up the device nodes.

start() {
	[ ! -c /dev/vmmc10 ] && {
		mknod /dev/vmmc10 c 122 10
		mknod /dev/vmmc11 c 122 11
		mknod /dev/vmmc12 c 122 12
		mknod /dev/vmmc13 c 122 13
		mknod /dev/vmmc14 c 122 14
		mknod /dev/vmmc15 c 122 15
		mknod /dev/vmmc16 c 122 16
		mknod /dev/vmmc17 c 122 17
		mknod /dev/vmmc18 c 122 18
	}
}

Maybe extending it to change the group to dialout is enough.

start() {
	[ ! -c /dev/vmmc10 ] && {
		mknod /dev/vmmc10 c 122 10
		mknod /dev/vmmc11 c 122 11
		mknod /dev/vmmc12 c 122 12
		mknod /dev/vmmc13 c 122 13
		mknod /dev/vmmc14 c 122 14
		mknod /dev/vmmc15 c 122 15
		mknod /dev/vmmc16 c 122 16
		mknod /dev/vmmc17 c 122 17
		mknod /dev/vmmc18 c 122 18
		group_exists dialout && \
			chown :dialout /dev/vmmc1{0,1,2,3,4,5,6,7,8}
	}
}

Can you confirm?

**Comment by micmac1** [comment]
That's probably not enough. According to your paste the permissions on the nodes are 644, so the dialout group doesn't have write permissions. It probably needs them. In case it doesn't work please try:

```
start() {
	[ ! -c /dev/vmmc10 ] && {
		mknod /dev/vmmc10 c 122 10
		mknod /dev/vmmc11 c 122 11
		mknod /dev/vmmc12 c 122 12
		mknod /dev/vmmc13 c 122 13
		mknod /dev/vmmc14 c 122 14
		mknod /dev/vmmc15 c 122 15
		mknod /dev/vmmc16 c 122 16
		mknod /dev/vmmc17 c 122 17
		mknod /dev/vmmc18 c 122 18
		if group_exists dialout; then
			chown :dialout /dev/vmmc1{0,1,2,3,4,5,6,7,8}
			chmod 664 /dev/vmmc1{0,1,2,3,4,5,6,7,8}
		fi
	}
}
```

**Comment by jospezial** [comment]
This does not change anything on the dev files even when remove the if and fi lines.
After disabling the service and
```
root@OpenWrt6431:~# /etc/init.d/vmmc start
chown: /dev/vmmc1{0,1,2,3,4,5,6,7,8}: No such file or directory
chmod: /dev/vmmc1{0,1,2,3,4,5,6,7,8}: No such file or directory
```
looks as wrong syntax

**Comment by jospezial** [comment]
After applying the chown and chmod to every vmmc file I still get the same error in asterisk.
```
crw-rw-r--    1 root     dialout   122,  10 Apr 12 14:54 vmmc10
crw-rw-r--    1 root     dialout   122,  11 Apr 12 14:54 vmmc11
crw-rw-r--    1 root     dialout   122,  12 Apr 12 14:54 vmmc12
crw-rw-r--    1 root     dialout   122,  13 Apr 12 14:54 vmmc13
crw-rw-r--    1 root     dialout   122,  14 Apr 12 14:54 vmmc14
crw-rw-r--    1 root     dialout   122,  15 Apr 12 14:54 vmmc15
crw-rw-r--    1 root     dialout   122,  16 Apr 12 14:54 vmmc16
crw-rw-r--    1 root     dialout   122,  17 Apr 12 14:54 vmmc17
crw-rw-r--    1 root     dialout   122,  18 Apr 12 14:54 vmmc18
```
```
Sun Apr 12 15:08:11 2020 daemon.info asterisk[3574]:   == Registered channel type 'TAPI' (Lantiq TAPI Telephony API Driver)
Sun Apr 12 15:08:11 2020 daemon.info asterisk[3574]: [Apr 12 13:08:11] ERROR[3574]: chan_lantiq.c:2116 load_module: lantiq TAPI device open function failed
Sun Apr 12 15:08:11 2020 daemon.info asterisk[3574]:   == Unregistered channel type 'TAPI'
```

**Comment by micmac1** [comment]
> Sun Apr 12 15:08:11 2020 daemon.info asterisk[3574]:   == Registered channel type 'TAPI' (Lantiq TAPI Telephony API Driver)
> Sun Apr 12 15:08:11 2020 daemon.info asterisk[3574]: [Apr 12 13:08:11] ERROR[3574]: chan_lantiq.c:2116 load_module: lantiq TAPI device open function failed
> Sun Apr 12 15:08:11 2020 daemon.info asterisk[3574]:   == Unregistered channel type 'TAPI'

Any other clue? Something in dmesg maybe?

**Comment by micmac1** [comment]
Here a description from another user how he made it  work: [link](https://forum.openwrt.org/t/solved-asterisk13-or-15-sqlite3-database-problem/36856/8)

The first obvious difference is that he made asterisk both owner and group of /dev/vmmc* devices.

Can you check this post and see if you can make it work for yourself?

**Comment by jospezial** [comment]
updated.
This is working /etc/init.d/vmmc for chan_lantiq:
```#!/bin/sh /etc/rc.common
#
# Activate Voice CPE TAPI subsystem LL driver for VMMC

START=31

start() {
        [ ! -c /dev/vmmc10 ] && {
                mknod -m 664 /dev/vmmc10 c 122 10
                mknod -m 664 /dev/vmmc11 c 122 11
                mknod -m 664 /dev/vmmc12 c 122 12
                mknod -m 664 /dev/vmmc13 c 122 13
                mknod -m 664 /dev/vmmc14 c 122 14
                mknod -m 664 /dev/vmmc15 c 122 15
                mknod -m 664 /dev/vmmc16 c 122 16
                mknod -m 664 /dev/vmmc17 c 122 17
                mknod -m 664 /dev/vmmc18 c 122 18
        }
        chown :asterisk /dev/vmmc1[0,1,2,3,4,5,6,7,8]
}```

**Comment by jospezial** [comment]
But next problem:
Sat May 30 20:50:41 2020 daemon.info asterisk[2097]:  Loading chan_lantiq.so.
Sat May 30 20:50:41 2020 daemon.info asterisk[2097]:   == Registered channel type 'TAPI' (Lantiq TAPI Telephony API Driver)
Sat May 30 20:50:41 2020 daemon.info asterisk[2097]: [May 30 18:50:41] ERROR[2097]: chan_lantiq.c:556 lantiq_dev_binary_buffer_create: binary file /lib/firmware/ifx_firmware.bin open failed
Sat May 30 20:50:41 2020 daemon.info asterisk[2097]: [May 30 18:50:41] ERROR[2097]: chan_lantiq.c:2132 load_module: voice firmware download failed
Sat May 30 20:50:41 2020 daemon.info asterisk[2097]:   == Unregistered channel type 'TAPI'

wrong permissions
-rw-------    1 root     root        533152 May 30 12:01 voice_ar9_firmware.bin
ls -l  /lib/firmware/e_ar9_firmware.b
lrwxrwxrwx    1 root     root            29 May 30 12:01 ifx_bbd_fxs.bin -> /lib/firmware/vr9_bbd_fxs.bin
lrwxrwxrwx    1 root     root            36 May 30 12:01 ifx_firmware.bin -> /lib/firmware/voice_ar9_firmware.bin
-rw-r--r--    1 root     root          3748 May 30 12:01 regulatory.db
-rw-r--r--    1 root     root          8192 May 30 12:01 rt2860.bin
-rw-r--r--    1 root     root          4096 May 30 12:01 rt3290.bin
-rw-------    1 root     root        533152 May 30 12:01 voice_ar9_firmware.bin
-r-xr-xr-x    1 root     root        908380 May 30 12:01 vr9-B-dsl.bin
-r--r--r--    1 root     root           300 May 30 12:01 vr9_bbd.bin
-r--r--r--    1 root     root           388 May 30 12:01 vr9_bbd_fxs.bin

**Comment by micmac1** [comment]
Does it work when you

`chmod 644 voice_ar9_firmware.bin`

?

Maybe on top of that instead of

`chown :asterisk /dev/vmmc1[0,1,2,3,4,5,6,7,8]`

use

`chown asterisk:asterisk /dev/vmmc1[0,1,2,3,4,5,6,7,8]`

?

If that works then we can send a patch to vmmc package maintainer. The firmware permission fix needs no justification IMHO. And making the user asterisk the owner of the devices would make sense if asterisk chan-lantiq is the only of these device nodes anyway. Which is the case as far as I understand. Nothing else will ever use these device nodes, I think.

**Comment by micmac1** [comment]
But I think the thing with the brackets won't work. Like, when I do this:

`mkdir vmmc1[0,1,2,3,4,5,6,7,8]`

I get this:

```
sk@darth ~ $ ls -lh|grep vmmc
drwxr-xr-x  2 sk   sk    4,0K 31. Mai 10:26 vmmc1[0,1,2,3,4,5,6,7,8]
sk@darth ~ $
```

Maybe use this instead:

```
#
# Activate Voice CPE TAPI subsystem LL driver for VMMC

START=31

start() {
	for i in 10 11 12 13 14 15 16 17 18; do
		if ! [ -e /dev/vmmc$i ]; then
			mknod -m 664 /dev/vmmc$i c 122 $i
			[ -c /dev/vmmc$i ] && \
				chown asterisk:asterisk /dev/vmmc$i
		fi
	done
}
```

**Comment by micmac1** [comment]
Anyway, please try if
`
chown :asterisk /dev/vmmc$i`

is enough or if 

`chown asterisk:asterisk /dev/vmmc$i`

is required. Also, please paste 

`ls -lh /dev/vmmc*`

**Comment by jospezial** [comment]
> Does it work when you
> 
> `chmod 644 voice_ar9_firmware.bin`
> 
> ?

Asterisk works after that. 

> Maybe on top of that instead of
> 
> `chown :asterisk /dev/vmmc1[0,1,2,3,4,5,6,7,8]`
> 
> use
> 
> `chown asterisk:asterisk /dev/vmmc1[0,1,2,3,4,5,6,7,8]`
> 
> ?

Should work the same. For chown it works with that brackets
Sad that the user and group is not configurable in mknod.

> If that works then we can send a patch to vmmc package maintainer.

That would be nice.

**Comment by jospezial** [comment]
I now tried the same with dialout but 
rungroup = dialout              ; The group to run as.
in /etc/asterisk/asterisk.conf is somehow ignored:
```
Sun May 31 13:34:10 2020 daemon.info asterisk[2090]: Running as user 'asterisk'
Sun May 31 13:34:10 2020 daemon.info asterisk[2090]: Running under group 'asterisk'
...
Sun May 31 13:34:22 2020 daemon.info asterisk[2090]:  Loading chan_lantiq.so.
Sun May 31 13:34:22 2020 daemon.info asterisk[2090]:   == Registered channel type 'TAPI' (Lantiq TAPI Telephony API Driver)
Sun May 31 13:34:22 2020 daemon.info asterisk[2090]: [May 31 11:34:22] ERROR[2090]: chan_lantiq.c:2116 load_module: lantiq TAPI device open function failed
Sun May 31 13:34:22 2020 daemon.info asterisk[2090]:   == Unregistered channel type 'TAPI'
```

**Comment by micmac1** [comment]
> > Does it work when you
> > `chmod 644 voice_ar9_firmware.bin`
> > ?
> 
> Asterisk works after that.
> 
> > Maybe on top of that instead of
> > `chown :asterisk /dev/vmmc1[0,1,2,3,4,5,6,7,8]`
> > use
> > `chown asterisk:asterisk /dev/vmmc1[0,1,2,3,4,5,6,7,8]`
> > ?
> 
> Should work the same. For chown it works with that brackets
> Sad that the user and group is not configurable in mknod.
>

Please clarify if it is enough for the group to be asterisk or if it is needed that asterisk is also the owner of the device nodes.

Regarding configuration. As this is an init script we can provide /etc/config/vmmc and make the ownership configurable there.
 
> > If that works then we can send a patch to vmmc package maintainer.
> 
> That would be nice.

Once you clarified the above query I can send a patch to openwrt-devel. I would like to CC you on that mail and ask you to provide your Tested-by: line. I would need your mail address for. Please let me know if that's OK for you.

**Comment by jospezial** [comment]
>Please clarify if it is enough for the group to be asterisk or if it is needed that asterisk is also the owner of the device nodes.

asterisk as group of /dev/vmmc* was enough because 664. we should keep the owner (root).

**Comment by jospezial** [comment]
I think to use dialout instead of asterisk as group would be better but I don't know the entry in the config is ignored.

**Comment by micmac1** [comment]
> I think to use dialout instead of asterisk as group would be better
> but I don't know the entry in the config is ignored.

I don't know either. Asterisk is started as root and then switches to
user/group asterisk itself. It might have something to do with that.
Maybe like this any additional groups the user is part of (like dialout)
are ignored.

**Comment by jospezial** [comment]
> I think to use dialout instead of asterisk as group would be better but I don't know why the entry in the config is ignored.

/etc/init.d/asterisk sets
NAME=asterisk
and then uses
 -G "$NAME" \
  -U "$NAME" \
could we respect the setting in /etc/asterisk/asterisk.conf?

**Comment by micmac1** [comment]
On Sun, May 31, 2020 at 05:10:25AM -0700, jospezial wrote:
> > I think to use dialout instead of asterisk as group would be better but I don't know why the entry in the config is ignored.
>
> /etc/init.d/asterisk sets
> NAME=asterisk
> and then uses
>  -G "$NAME" \
>   -U "$NAME" \
> could we respect the setting in /etc/asterisk/asterisk.conf?

We don't. And honestly I don't want to parse asterisk configuration from
the users. We start asterisk with user asterisk and group asterisk. If
the users want to play with different users/groups then they need to fix
the permissions on their own.

**Comment by jospezial** [comment]
when I remove 
 -G "$NAME" \
   -U "$NAME" \
/etc/init.d/asterisk then the setting in /etc/asterisk/asterisk.conf is used.
If not set then it is started as root:root

Sun May 31 14:26:28 2020 daemon.info asterisk[3183]: Running as user 'asterisk'
Sun May 31 14:26:28 2020 daemon.info asterisk[3183]: Running under group 'dialout'

**Comment by micmac1** [comment]
On Sun, May 31, 2020 at 05:32:25AM -0700, jospezial wrote:
> when I remove
>  -G "$NAME" \
>    -U "$NAME" \
> /etc/init.d/asterisk then the setting in /etc/asterisk/asterisk.conf is used.
> If not set then it is started as root:root
>
> Sun May 31 14:26:28 2020 daemon.info asterisk[3183]: Running as user 'asterisk'
> Sun May 31 14:26:28 2020 daemon.info asterisk[3183]: Running under group 'dialout'

But the init script sets up various dirs for user/group asterisk. Now
you need to manually fix your permissions :)

**Comment by jospezial** [comment]
> But the init script sets up various dirs for user/group asterisk. Now you need to manually fix your permissions :)

It works because asterisk is started as user "asterisk". Started as root:root it would work anyway but should not be used.

**Comment by jospezial** [comment]
another idea:
remove group asterisk
give user asterisk the dialout as primary group

**Comment by micmac1** [comment]
On Sun, May 31, 2020 at 06:00:52AM -0700, jospezial wrote:
> another idea:
> remove group asterisk
> give user asterisk the dialout as primary group

Feel free to send a pull request for that. Personally I don't really
like it, as I associate dialout with PPP, not with telephony, really.

And then ltq-vmmc package would need to be changed again.

I'll hold of with the mail to openwrt-devel for now. Let's wait a few
weeks with that until this settles down.

**Comment by jospezial** [comment]
The group on /dev/vmmc* has not been fixed in closed
ltq-vmmc: update permission handling openwrt/openwrt#3124

crw-rw-r--    1 root     root      122,  10 Nov  7 02:31 /dev/vmmc10
crw-rw-r--    1 root     root      122,  11 Nov  7 02:31 /dev/vmmc11
crw-rw-r--    1 root     root      122,  12 Nov  7 02:31 /dev/vmmc12
crw-rw-r--    1 root     root      122,  13 Nov  7 02:31 /dev/vmmc13
crw-rw-r--    1 root     root      122,  14 Nov  7 02:31 /dev/vmmc14
crw-rw-r--    1 root     root      122,  15 Nov  7 02:31 /dev/vmmc15
crw-rw-r--    1 root     root      122,  16 Nov  7 02:31 /dev/vmmc16
crw-rw-r--    1 root     root      122,  17 Nov  7 02:31 /dev/vmmc17
crw-rw-r--    1 root     root      122,  18 Nov  7 02:31 /dev/vmmc18

We still need to add
chown :asterisk /dev/vmmc$i
in /etc/init.d/vmmc to if asterisk running under group "asterisk".
That would be the simplest fix. I would not like another extra config file.

otherwise with the default:
Sat Nov  7 02:32:04 2020 daemon.info asterisk[2754]: Running as user 'asterisk'
Sat Nov  7 02:32:04 2020 daemon.info asterisk[2754]: Running under group 'asterisk'
...
Sat Nov  7 02:32:17 2020 daemon.info asterisk[2754]:  Loading chan_lantiq.so.
Sat Nov  7 02:32:17 2020 daemon.info asterisk[2754]:   == Registered channel type 'TAPI' (Lantiq TAPI Telephony API Driver)
Sat Nov  7 02:32:17 2020 daemon.info asterisk[2754]: [Nov  7 01:32:17] ERROR[2754]: chan_lantiq.c:2116 load_module: lantiq TAPI device open function failed
Sat Nov  7 02:32:17 2020 daemon.info asterisk[2754]:   == Unregistered channel type 'TAPI'

**Comment by micmac1** [comment]
Hi, the problem is not in asterisk, so raising this to OpenWrt makes sense. Like [here](https://github.com/openwrt/openwrt/pull/3124) or [here](https://bugs.openwrt.org/).

**Comment by jospezial** [comment]
vmmc is not part of telephony repo.
