### ISSUE TITLE
Regarding use of chown and chmod in Makefiles and init scripts

### ISSUE THREAD

**Issue by micmac1** [openwrt/telephony#527]
Hi @jslachta, all,

Yesterday somebody from Suse posted to oss-security about making sure that pre/post install scripts in packages are sane ([link](https://www.openwall.com/lists/oss-security/2020/04/30/1)). Later somebody involved in Gentoo replied and added more details.

TL;DR: Lax use of chmod/chown has serious security implications. A local user can setup symbolic links and hard links in a directory where he/she has write access and if root calls chown/chmod (either manually, in init scripts or in pre/post install scripts) these may follow the links and alter the permissions of the target, providing access to it to the local user. Local privilege escalation. Owned.

So summarize the suggestions that can be found when following the links in the mail threat:

- don't use chown/chmod
- use "su -" to switch to the user before running commands altering permissions/ownership where possible
- use special tools like "checkpath" and "fowners" when possible

Well, the two tools mentioned are Gentoo and OpenRC specific and we don't have them in OpenWrt as far as I know. I think we have no special tools at hand, really.

But I think we can come up with a list of best practices that we can follow. I'm talking about best practices for packages that set up a user so that a daemon does not need to run as root.

My list would be this:

1. **Never** change permissions/ownership on live filesystem on files that the user may have edited.
2. **Never** change permissions/ownership of any file
3. To limit access to a certain user, a directory may be created and ownership of this directory handed to the user. But this shall only be done when the directory does not exist yet. **No** changes to existing directories.
4. During package installation a "preinst" script can be used to create non-existing directories on non-volatile storage and hand ownership to a user. This way the directory already exists before the package creates it with the default ownership/permissions. **EDIT: I think this doesn't work because the user is probably not installed at this stage**
5. Use umask to avoid calling chmod.
6. The macro "$(INSTALL_CONF)" should not be used in case the files need to be readable by the daemon when it runs non-root. Instead use "$(INSTALL_DATA)" in this case and set up the directory that will contain these files as mentioned above in points 3, 4 and 5.

I would be happy for other opinions. It would be great to write a short list of best practices together.

Best regards,
Seb

**Comment by micmac1** [comment]
Updated point 4. I doubt this would work.

**Comment by jslachta** [comment]
Hi Sebastian (@micmac1),

IMHO this is a wide packaging issue. It would be better to raise this on packages repo to get more feedback. The best practices which comes out as a result of this issue should be applied to all openwrt-related repositories. 

Thank you for taking a look at this issue. 

Kind regards,
Jiri

**Comment by micmac1** [comment]
Hi Jiri,

That's alright. I didn't scan the packages repo for issues. Honestly I don't have time for that. I'll just be more careful with the packages I maintain myself.

Kind regards,
Seb

**Comment by jslachta** [comment]
Hi Sebastian,

I did not want to bury this issue and I did not want you to scan the packages repo for issues. I just wanted to start a discussion about it to _write a short list of best practices together_. The telephony repository is just a really small place to discuss that.

As far as I know, there are no such best practices. The packages repo is the right place to join the forces together.

Kind regards,
Jiri

**Comment by micmac1** [comment]
Hi Jiri,

And I didn't understand your reply like that. I just honestly thought this would take too much of my time.

I'll raise an issue in packages. The text is already more or less available (from here), so my lazy self should be alright :)

Kind regards,
Seb
