### ISSUE TITLE
Asterisk13.3.2-2 PJSIP configuration user_agent doesn't go into effect

### ISSUE THREAD

**Issue by Hobb** [openwrt/telephony#53]
Provided a pjsip.conf file properly configurated with a global section like the following:

[global]
user_agent=Technicolor TG784n v3 Build 8.G.D.4
default_outbound_endpoint=OutEndpoint

Or with the user_agent variable set inside an endpoint:

[endpoint]
100rel=yes
rtp_engine=asterisk
user_agent=Technicolor TG784n v3 Build 8.G.D.4
sdp_session=Technicolor TG784n

It doesn't change the user agent when sending the REGISTER messages to the SIP as seen in this message:

REGISTER sip:111.111.111.111:5060 SIP/2.0
Via: SIP/2.0/UDP 222.222.222.222:5060;rport;branch=z9hGabKPj84b86ce5-d65b-4149-8210-37d1g5d2e49e
From: <sip:+34917722311@sip.domain.net>;tag=ea7fd10c-b891-44ec-b9c6-373f6b077eff
To: <sip:+34917722311@sip.domain.net>
Call-ID: ae95faf2-c8ad-4a4a-88fd-08a3a07151c7
CSeq: 19574 REGISTER
Contact: <sip:s@222.222.222.222:5060>
Expires: 3600
Allow: OPTIONS, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, REGISTER, MESSAGE, REFER
Supported: path
Max-Forwards: 70
User-Agent: Asterisk PBX 13.3.2
Content-Length:  0

This was working fine in the previous version, it is causing my VoIP provider filter out the packages and not allowing me to register.

PD: /paranoid mode on, personal information already modified both in packet info and ip/info

**Comment by jslachta** [comment]
Hi @Hobb,

are you compiling it yourself or have you used the snapshots? Does this happen on pjsip in version 2.4 or 2.3? Let me know about the versions, it should be tested. It seems to be an upstream issue.

Thank you

**Comment by Hobb** [comment]
Hi, @jslachta,

I am using the CC snapshots (I'm on r45557), the versions are the following:

Pjsip related:

asterisk13-pjsip - 13.3.2-2
libpjsip - 2.3-1
libpjsip-simple - 2.3-1
libpjsip-ua - 2.3-1

And on the asterisk side:

asterisk13 - 13.3.2-2
asterisk13-app-confbridge - 13.3.2-2
asterisk13-codec-a-mu - 13.3.2-2
asterisk13-codec-alaw - 13.3.2-2
asterisk13-codec-g722 - 13.3.2-2
asterisk13-codec-g726 - 13.3.2-2
asterisk13-codec-gsm - 13.3.2-2
asterisk13-codec-ulaw - 13.3.2-2
asterisk13-format-g726 - 13.3.2-2
asterisk13-format-g729 - 13.3.2-2
asterisk13-pjsip - 13.3.2-2
asterisk13-res-rtp-asterisk - 13.3.2-2
asterisk13-res-sorcery - 13.3.2-2

Thank you

**Comment by jslachta** [comment]
Could you test it with pjsip 2.4? If it does not work, I will consider changing the version to the previous one.

**Comment by Hobb** [comment]
Just upgraded to pjsip 2.4.1 snapshots and problem persists.

I do not have a build environment setup so I cannot build my own packages (working on it but will take a while), so I was wondering if you can give me the packages for the previous version (through dropbox,mail,etc...) and then I can do a test in my environment to fully confirm that the previous version did not show the bug before taking the decision of reverting trunk to the previous version (as a developer myself I know how frustrating that decision feels).

Just to narrow the target, my device is a wrt1900ac (mvebu/mamba).

**Comment by jslachta** [comment]
Please send me an email to slachta<at>cesnet<dot>cz. I will make an "unofficial image" with asterisk for you during the weekend.

**Comment by Hobb** [comment]
Hi Jiri,

Been playing around with the version of Asterisk you compiled for me (13.2.0) and I have been able to setup my scenario without problems and without changing the configuration that failed in the 13.3.2 version.

Seems like that version had a bug but I have not been able to find any mention of it in the Asterisk JIRA ( I think is this one: https://issues.asterisk.org/jira/browse/ASTERISK-25073?jql=project%20%3D%20ASTERISK%20ORDER%20BY%20created%20DESC)

I can see they fixed an issue affecting the handling of the user agent in the 13.3.0 version (https://reviewboard.asterisk.org/r/4467/), perhaps the user agent bug was added when this change was made, it is beyond my ability to determine that much.

Perhaps the sensible thing to do is to escalate this problem to asterisk.org and downgrade the OpenWRT packages as it has been suggested to the last known good version we can identify (13.2.0 probably).

Thanks a lot for your help.

**Comment by jslachta** [comment]
I reverted asterisk to version 13.2.0. AST-2015-003 should be fixed too.

Would you be so kind to place this issue on issues.asterisk.org or should I do it myself?

**Comment by Hobb** [comment]
I am receiving a raspberry pi this week and I am going to run a few tests with debian and different versions of asterisk 13 in it to fully confirm the problem happening in a different device/distro before going to asterisk.org to open the issue.

**Comment by jslachta** [comment]
ACK, I also downversioned asterisk for the 15.05 release.

**Comment by Hobb** [comment]
https://issues.asterisk.org/jira/browse/ASTERISK-25097

Will be following and notify if they fix the issue, I have succesfuly verified the issue happening in a second system (raspbian) proving the failure to be external to our packages/distro/hardware.

**Comment by Hobb** [comment]
Answer from asterisk:

>This is a configuration problem. You are missing the type=global line in your global section.

>[global]
>type=global
>user_agent=My technicolor

>Also user_agent is not valid inside an endpoint section and you should get a diagnostic about it.

>All sections in pjsip.conf need a type= line to identify what type of section the configuration information is for. Otherwise the untyped sections are ignored.

The relevant bit from the answer is the need in this version to start typing every single section (strangely I did not get a diagnostic about the user agent in the endpoint, that was just an experiment anyway). This is a change in the way configuration works afaik.

Perhaps is the moment to try again the packages...
