### ISSUE TITLE
asterisk-11.x error

### ISSUE THREAD

**Issue by taeasy** [openwrt/telephony#54]
checking for getifaddrs() support... yes
checking for timerfd support... yes
checking for LIBEDIT... no
checking for iconv_open in -liconv... no
checking for libiconv_open in -liconv... no
checking for iconv_close in -lc... no
checking for icaltimezone_get_utc_timezone in -lical... yes
checking libical/ical.h usability... yes
checking libical/ical.h presence... yes
checking for libical/ical.h... yes
checking for UW IMAP Toolkit c-client library... no
checking for system c-client library...... no
checking for SQLConnect in -liodbc... no
checking for inotify_init in -lc... yes
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking for jack_activate in -ljack... no
checking for kqueue in -lc... no
checking for kevent64... no
checking for lt_dlinit in -lltdl... yes
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for ldap_initialize in -lldap... yes
checking ldap.h usability... yes
checking ldap.h presence... yes
checking for ldap.h... yes
checking for x86_64-openwrt-linux-mysql_config... no
checking for mysql_config... (cached) /home/main/main/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/bin/mysql_config
checking for x86_64-openwrt-linux-neon-config... no
checking for neon-config... no
checking for x86_64-openwrt-linux-neon-config... no
checking for neon-config... no
checking for SQLConnect in -lodbc... yes
checking sql.h usability... yes
checking sql.h presence... yes
checking for sql.h... yes
checking for backtrace in -lexecinfo... no
checking for backtrace in -lc... no
checking linux/soundcard.h usability... yes
checking linux/soundcard.h presence... yes
checking for linux/soundcard.h... yes
checking for x86_64-openwrt-linux-pg_config... no
checking for pg_config... /home/main/main/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/bin/pg_config
checking for PQescapeStringConn in -lpq... yes
checking for pg_encoding_to_char within Postgres headers... yes
checking for poptStrerror in -lpopt... yes
checking popt.h usability... yes
checking popt.h presence... yes
checking for popt.h... yes
checking for Pa_GetDeviceCount in -lportaudio... yes
checking portaudio.h usability... yes
checking portaudio.h presence... yes
checking for portaudio.h... yes
checking for pri_setup_ack in -lpri... no
checking for pri_persistent_layer2_option in -lpri... no
checking for pri_date_time_send_option in -lpri... no
checking for pri_mwi_indicate_v2 in -lpri... no
checking for pri_display_text in -lpri... no
checking for pri_mwi_indicate in -lpri... no
checking for pri_mcid_enable in -lpri... no
checking for pri_connect_ack_enable in -lpri... no
checking for pri_aoc_events_enable in -lpri... no
checking for pri_transfer_enable in -lpri... no
checking for pri_cc_enable in -lpri... no
checking for pri_hangup_fix_enable in -lpri... no
checking for pri_sr_set_called_subaddress in -lpri... no
checking for pri_hold_enable in -lpri... no
checking for pri_reroute_enable in -lpri... no
checking for pri_sr_set_keypad_digits in -lpri... no
checking for pri_progress_with_cause in -lpri... no
checking for pri_set_inbanddisconnect in -lpri... no
checking for pri_maintenance_service in -lpri... no
checking for pri_sr_set_reversecharge in -lpri... no
checking for resample_open in -lresample... no
checking for minimum version of SpanDSP... yes
checking for span_set_message_handler in -lspandsp... yes
checking spandsp.h usability... yes
checking spandsp.h presence... yes
checking for spandsp.h... yes
checking for t38_terminal_init in -lspandsp... yes
checking for spandsp.h... (cached) yes
checking for ss7_set_adjpc in -lss7... no
checking for openr2_chan_new in -lopenr2... no
checking for luaL_newstate in -llua5.2... no
checking for luaL_newstate in -llua5.1... no
checking for luaL_openlib in -llua... yes
checking lua.h usability... yes
checking lua.h presence... yes
checking for lua.h... yes
checking for cpg_join in -lcpg... no
checking for corosync_cfg_state_track in -lcfg... no
checking for speex_encode in -lspeex... no
checking for speex_preprocess_ctl in -lspeex... no
checking for speex_preprocess_ctl in -lspeexdsp... yes
checking speex/speex.h usability... yes
checking speex/speex.h presence... yes
checking for speex/speex.h... yes
checking for sqlite3_open in -lsqlite3... yes
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
checking for AES_encrypt in -lcrypto... yes
checking openssl/aes.h usability... yes
checking openssl/aes.h presence... yes
checking for openssl/aes.h... yes
checking for SSL_connect in -lssl... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for SSL_CTX_set_tlsext_use_srtp in -lssl... yes
checking for openssl/ssl.h... (cached) yes
checking for srtp_init in -lsrtp... yes
checking srtp/srtp.h usability... yes
checking srtp/srtp.h presence... yes
checking for srtp/srtp.h... yes
checking for the ability of -lsrtp to be linked in a shared object... yes
checking for srtp_shutdown in -lsrtp... no
checking for GMIME... no
checking for GMIME... no
checking for GMIME... no
checking for GMIME... no
checking for malloc in -lhoard... no
checking for tone_zone_find_by_num in -ltonezone... yes
checking for tone_zone_find in -ltonezone... yes
checking dahdi/tonezone.h usability... yes
checking dahdi/tonezone.h presence... yes
checking for dahdi/tonezone.h... yes
checking for uuid_generate_random in -luuid... yes
checking uuid/uuid.h usability... yes
checking uuid/uuid.h presence... yes
checking for uuid/uuid.h... yes
checking for OV_CALLBACKS_NOCLOSE declared in vorbis/vorbisfile.h... yes
checking for compress in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking whether ODBC has support for Unicode types... yes
checking h323.h usability... no
checking h323.h presence... no
checking for h323.h... no
checking linux/compiler.h usability... no
checking linux/compiler.h presence... no
checking for linux/compiler.h... no
checking for linux/ixjuser.h... yes
checking for MSG_NOSIGNAL in sys/socket.h... yes
checking for SO_NOSIGPIPE in sys/socket.h... no
checking for IMG_Load in -lSDL_image... no
checking for sws_getContext in -lavcodec... no
checking linux/videodev.h usability... no
checking linux/videodev.h presence... no
checking for linux/videodev.h... no
checking for XOpenDisplay in -lX11... no
checking for XOpenDisplay in -lX11... (cached) no
checking for LOG_AUTH in syslog.h... yes
checking for LOG_AUTHPRIV in syslog.h... yes
checking for LOG_CRON in syslog.h... yes
checking for LOG_DAEMON in syslog.h... yes
checking for LOG_FTP in syslog.h... yes
checking for LOG_KERN in syslog.h... yes
checking for LOG_LPR in syslog.h... yes
checking for LOG_MAIL in syslog.h... yes
checking for LOG_NEWS in syslog.h... yes
checking for LOG_SYSLOG in syslog.h... yes
checking for LOG_UUCP in syslog.h... yes
checking for mandatory modules:  DAHDI GSM ILBC LUA MYSQLCLIENT NCURSES PGSQL POPT SPANDSP SQLITE3 SRTP TONEZONE UUID ZLIB... ok
configure: creating ./config.status
config.status: creating build_tools/menuselect-deps
config.status: creating makeopts
config.status: creating channels/h323/Makefile
config.status: creating include/asterisk/autoconfig.h
configure: WARNING: unrecognized options: --disable-nls
configure: loading site script /home/main/main/include/site/x86_64
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... x86_64-openwrt-linux-uclibc-gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... configure: error: in `/home/main/main/build_dir/target-x86_64_uClibc-0.9.33.2/asterisk-11.17.1/menuselect':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.

               .$$$$$$$$$$$$$$$=..      
            .$7$7..          .7$$7:.    
          .$$:.                 ,$7.7   
        .$7.     7$$$$           .$$77  
     ..$$.       $$$$$            .$$$7 
    ..7$   .?.   $$$$$   .?.       7$$$.
   $.$.   .$$$7. $$$$7 .7$$$.      .$$$.
 .777.   .$$$$$$77$$$77$$$$$7.      $$$,
 $$$~      .7$$$$$$$$$$$$$7.       .$$$.
.$$7          .7$$$$$$$7:          ?$$$.
$$$          ?7$$$$$$$$$$I        .$$$7 
$$$       .7$$$$$$$$$$$$$$$$      :$$$. 
$$$       $$$$$$7$$$$$$$$$$$$    .$$$.  
$$$        $$$   7$$$7  .$$$    .$$$.   
$$$$             $$$$7         .$$$.    
7$$$7            7$$$$        7$$$      
 $$$$$                        $$$       
  $$$$7.                       $$  (TM)     
   $$$$$$$.           .7$$$$$$  $$      
     $$$$$$$$$$$$7$$$$$$$$$.$$$$$$      
       $$$$$$$$$$$$$$$$.                

configure: Package configured for: 
configure: OS type  : linux-gnu
configure: Host CPU : x86_64
configure: build-cpu:vendor:os: x86_64 : pc : linux-gnu :
configure: host-cpu:vendor:os: x86_64 : openwrt : linux-gnu :
configure: Cross Compilation = YES
(cd /home/main/main/build_dir/target-x86_64_uClibc-0.9.33.2/asterisk-11.17.1/menuselect; ./bootstrap.sh; ./configure  --without-newt --without-ncurses --with-libxml2="/home/main/main/staging_dir/host/usr" LDFLAGS="-L/home/main/main/staging_dir/host/lib -L/home/main/main/staging_dir/host/usr/lib -lxml2" CFLAGS="-O2 -I/home/main/main/staging_dir/host/include -I/home/main/main/staging_dir/host/usr/include -I/home/main/main/staging_dir/host/include/libxml2" );
Generating the configure script ...
configure.ac:94: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:94: the top level
configure.ac:99: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:99: the top level
configure.ac:104: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:104: the top level
configure.ac:111: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:111: the top level
configure.ac:94: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:94: the top level
configure.ac:99: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:99: the top level
configure.ac:104: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:104: the top level
configure.ac:111: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
acinclude.m4:4: AST_GCC_ATTRIBUTE is expanded from...
configure.ac:111: the top level
configure: loading site script /home/main/main/include/site/x86_64
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/main/main/build_dir/target-x86_64_uClibc-0.9.33.2/asterisk-11.17.1/menuselect':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[3]: *** [/home/main/main/build_dir/target-x86_64_uClibc-0.9.33.2/asterisk-11.17.1/.configured_yyyyyyyy] Error 77
make[3]: Leaving directory `/home/main/main/feeds/telephony/net/asterisk-11.x'
make[2]: *** [package/feeds/telephony/asterisk-11.x/compile] Error 2
make[2]: Leaving directory `/home/main/main'
make[1]: *** [/home/main/main/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main

**Comment by jslachta** [comment]
This should be currently fixed by reverting the update to 11.17.1.
