### ISSUE TITLE
Cannot satisfy the following dependencies for freeswitch: shadow-su

### ISSUE THREAD

**Issue by stintel** [openwrt/telephony#550]
Maintainer: @micmac1
Environment: OpenWrt master r14002-1bff9f5b78

Description:
Build fails due to missing dependency:

```
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for freeswitch:
 *      shadow-su
 * opkg_install_cmd: Cannot install package freeswitch.
```

**Comment by micmac1** [comment]
Hi there, why is shadow-su not available in your builds? It works fine for me and the build bots.

**Comment by stintel** [comment]
Probably because the build bots build all packages. I never had shadow-su enabled before, and I'm using freeswitch on OpenWrt for years. The fact the freeswitch now needs it is fine, but there should be a dependency so that `make {def,menu,old}config` enables it.

**Comment by micmac1** [comment]
The dependency is there, though: +!BUSYBOX_DEFAULT_SU:shadow-su

**Comment by micmac1** [comment]
Just grabbing for straws here. Did you run make menuconfig and save the config so shadow-su gets selected?

**Comment by stintel** [comment]
Hmm. I cloned the repo earlier today and `git grep shadow` didn't show anything. Guess I did something wrong.

Either way, I had to manually enable shadow in `make menuconfig` to fix the problem. Not sure why the dependency isn't working.

**Comment by micmac1** [comment]
Works for me. Plesse provide all necessary steps to replicate, from scratch.

**Comment by neheb** [comment]
shadow-utils must be selected before any applets. See: https://github.com/openwrt/packages/blob/master/utils/lxc/Makefile#L78

**Comment by micmac1** [comment]
> shadow-utils must be selected before any applets. See: https://github.com/openwrt/packages/blob/master/utils/lxc/Makefile#L78

Hello Rosen,

Thanks for the insight. I added the dep in #562. 

@stintel, please confirm whether this fixes your issue, as I still cannot reproduce it.

Regards,
Seb

**Comment by micmac1** [comment]
I hope this is fixed in trunk now. If not feel free to reopen and provide requested details. Thanks!
