### ISSUE TITLE
freeswitch and asterisk-16.x do not compile under musl 1.2.0

### ISSUE THREAD

**Issue by neheb** [openwrt/telephony#565]
I have this PR in base: https://github.com/openwrt/openwrt/pull/3004

Under it, there are issues.

Asterisk-16.x does not compile as it relies on the completely deprecated sys/cdefs.h header that does not come with musl. The patch I have for it is:

```
--- a/main/ast_expr2.c
+++ b/main/ast_expr2.c
@@ -94,7 +94,6 @@
 #define ASTMM_LIBC ASTMM_REDIRECT
 #include "asterisk.h"

-#include <sys/cdefs.h>
 #include <sys/types.h>
 #include <stdio.h>

--- a/main/ast_expr2.y
+++ b/main/ast_expr2.y
@@ -15,10 +15,11 @@
 #define ASTMM_LIBC ASTMM_REDIRECT
 #include "asterisk.h"

-#include <sys/cdefs.h>
 #include <sys/types.h>
 #include <stdio.h>

+#define __P(x) x
+
 #if defined(STANDALONE) || defined(STANDALONE2)
 #ifndef __USE_ISOC99
 #define __USE_ISOC99 1
--- a/utils/db1-ast/include/db.h
+++ b/utils/db1-ast/include/db.h
@@ -37,7 +37,6 @@
 #define        _DB_H 1

 #include <sys/types.h>
-#include <sys/cdefs.h>

 #include <limits.h>

@@ -69,11 +68,9 @@ typedef	unsigned long long	u_int64_t;
 #endif /* __FreeBSD__ */
 #endif

-#ifdef SOLARIS
 #define        __P(p) p
 #define __BEGIN_DECLS
 #define __END_DECLS
-#endif

 #define        MAX_PAGE_NUMBER 0xffffffff	/* >= # of pages in a file */
 typedef u_int32_t	pgno_t;
```

I'm not sure how correct this is.

Freeswitch has a problem where it passes -Werror thereby throwing an error on a time_t string. The patch I have for it is:

```
--- a/src/include/switch_platform.h
+++ b/src/include/switch_platform.h
@@ -270,7 +270,7 @@ typedef intptr_t switch_ssize_t;
 #if defined(__FreeBSD__) && SIZEOF_VOIDP == 4
 #define TIME_T_FMT "d"
 #else
-#define TIME_T_FMT "ld"
+#define TIME_T_FMT "lld"
 #endif
 #endif

```

This is totally incorrect but works for 32-bit. I assume the definition would need to be changed.

Maintainer: @micmac1 
Environment: musl 1.2.0

**Comment by micmac1** [comment]
Thanks for headsup. Will think about FS and musl 1.2 when I get around to it. Would be nice to have musl 1.2 in OpenWrt first. But I guess that might take a while (2020 release first if they still want to do it?) :)

Kind regards,
Seb

**Comment by neheb** [comment]
I've posted PRs. Might as well close.
