### ISSUE TITLE
Asterisk11: Missing app_directory

### ISSUE THREAD

**Issue by mrzaphodb** [openwrt/telephony#57]
Voicemail working well in Asterisk11 and dial-by-name would be very valuable.

**Comment by jslachta** [comment]
Module app_directory was added in e6f05a9e0a71df8cabc9bb5e1f3e0101f3011f13.

**Comment by mrzaphodb** [comment]
Hi Jiri,

Thank you for adding the app_directory module!

Unfortunately, I have encountered issues with the new Asterisk 11.18.0 in a
fresh build of CC (r46160). Asterisk doesn't visibly load any modules and
posts the following error messages in /var/log/asterisk/messages:

[Jul  2 19:24:37] Asterisk 11.18.0 built by keith @ WildernetsXPS on a
x86_64 running Linux on 2015-07-02 18:08:19 UTC
[Jul  2 19:24:38] WARNING[2400] cel.c: Could not load cel.conf
[Jul  2 19:24:38] NOTICE[2400] loader.c: 57 modules will be loaded.
[Jul  2 19:24:38] WARNING[2400] loader.c: Error loading module
'res_musiconhold.so': Error loading shared library
/usr/lib/asterisk/modules/res_musiconhold.so: No such file or directory
[Jul  2 19:24:38] WARNING[2400] loader.c: Error loading module
'chan_sip.so': Error relocating /usr/lib/asterisk/modules/chan_sip.so:
ast_websocket_read: symbol not found
[Jul  2 19:24:39] WARNING[2400] loader.c: Error loading module
'chan_dahdi.so': Error relocating /usr/lib/asterisk/modules/chan_dahdi.so:
ast_smdi_interface_unref: symbol not found

I copied cel.conf out of the build directory and updated modules.conf so
that it doesn't attempt to load res_musiconhold.so (since I don't have that
selected in .config. This fixes the first two error messages but I can't
fix the missing symbols preventing chan_sip.so and chan_dahdi.so from
loading.

Let me know if there is something I need to change in my .config to fix
these issues and if I can help with debug.

Cheers,

Keith (mrzaphodb)

**Comment by jslachta** [comment]
Hi @mrzaphodb ,

make sure you have loaded res_smdi for the chan_dahdi module and res_http_websocket for chan_sip.

Would you be so kind to start a new issue describing your problem? Please, assign the new issue to me.

Thank you for the report, I will test it again today.

Cheers,
Jiri

**Comment by mrzaphodb** [comment]
Hi Jiri,

I have opened a new issue as requested. However, I don't know how to assign
it to you.

Also, I already have res_smdi selected in the config. I don't have a
visible config selection for res_http_websocket.

Cheers,

Keith

**Comment by mrzaphodb** [comment]
Hi Jiri,

For your reference, attached is the asterisk11 section of my .config.

Cheers,

Keith
