### ISSUE TITLE
yate-mod-regexroute: Package not found on aarch64_cortex-a72

### ISSUE THREAD

**Issue by akshay1994** [openwrt/telephony#589]
Maintainer: @jslachta
Environment: aarch64_cortex-a72 Raspberry Pi Snapshot

Description: Package yate-mod-regexroute is not available on aarch64_cortex-a72: https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a72/telephony/

**Comment by micmac1** [comment]
Hi there,

This isn't an issue in telephony repo. Right now there are lots of failures on the build bots. I.e. cryptodev isn't building -> openssl isn't building -> follow-up breakage.

Once this is resolved yate will be complete again.

Regards,
Seb

**Comment by akshay1994** [comment]
Ah! I see. Makes sense. Thank you for the quick response. I'll close this issue for now.

**Comment by micmac1** [comment]
Hello Felix (@nbd168),

Might the failure on the build bots be related to [1]? It looks like the symvers files can't be found.

[1] https://github.com/openwrt/openwrt/commit/5d7606562940b52206712bb4bc274ad39521c3e1

**Comment by akshay1994** [comment]
@nbd168 Polite ping. Please take a look.

**Comment by micmac1** [comment]
Closing as not a telephony repo issue. For discussion see [1] and for patch see [2].

[1] https://lists.openwrt.org/pipermail/openwrt-devel/2020-November/032113.html
[2] https://lists.openwrt.org/pipermail/openwrt-devel/2020-November/032181.html
