### ISSUE TITLE
asterisk 18.1.0 crashes when a number is pressed (DTMF) when remote end is ringing or has picked up

### ISSUE THREAD

**Issue by jospezial** [openwrt/telephony#597]
Maintainer: @jslachta
Environment:
MIPS lantiq, VGV7510KW22 (o2 Box 6431) built from openwrt git master,Gigaset DECT on analog phoneports,chan_lantiq, pjsip,
Linux version 5.4.83 (joerg@jlgentoo) (gcc version 10.2.0 (OpenWrt GCC 10.2.0 r15241-3ab695368a)) #0 SMP Fri Dec 18 22:05:50 2020

Description:
I was having a call where I was prompted to input a number on the phone. After that the phone was quiet.
Reproducable also after reboot.

```Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013240, ts 121920, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019457, ts 3025006985, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013241, ts 122080, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019458, ts 3025007145, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013242, ts 122240, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019459, ts 3025007305, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013243, ts 122400, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019460, ts 3025007465, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013244, ts 122560, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019461, ts 3025007625, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013245, ts 122720, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019462, ts 3025007785, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013246, ts 122880, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019463, ts 3025007945, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Sent RTP packet to      62.52.130.135:41992 (type 08, seq 013247, ts 123040, len 000160)
Thu Dec 24 12:22:12 2020 kern.info kernel: [  303.831821] do_page_fault(): sending SIGSEGV to asterisk for invalid read access from 00000004
Thu Dec 24 12:22:12 2020 kern.info kernel: [  303.839382] epc = 004e2129 in asterisk[400000+16b000]
Thu Dec 24 12:22:12 2020 kern.info kernel: [  303.844216] ra  = 00469517 in asterisk[400000+16b000]
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019464, ts 3025008105, len 000160)
Thu Dec 24 12:22:12 2020 daemon.info asterisk[2648]: Got  RTP packet from    62.52.130.135:41992 (type 08, seq 019465, ts 3025008265, len 000160)
Thu Dec 24 12:22:13 2020 kern.warn kernel: [  304.344579] INFO: Upstream packet fifo full[ch(0)]!
Thu Dec 24 12:22:23 2020 kern.warn kernel: [  314.344591] INFO: Upstream packet fifo full[ch(0)]!
Thu Dec 24 12:22:33 2020 kern.warn kernel: [  324.344577] INFO: Upstream packet fifo full[ch(0)]!
Thu Dec 24 12:22:43 2020 kern.warn kernel: [  334.344579] INFO: Upstream packet fifo full[ch(0)]!
Thu Dec 24 12:22:53 2020 kern.warn kernel: [  344.344590] INFO: Upstream packet fifo full[ch(0)]!
Thu Dec 24 12:22:58 2020 daemon.err odhcp6c[3690]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Thu Dec 24 12:23:03 2020 kern.warn kernel: [  354.344579] INFO: Upstream packet fifo full[ch(0)]!
Thu Dec 24 12:23:13 2020 kern.warn kernel: [  364.344579] INFO: Upstream packet fifo full[ch(0)]!
```

**Comment by micmac1** [comment]
Merry Christmas,

See upstream bug: [Link](https://issues.asterisk.org/jira/browse/ASTERISK-28800)

Loading the module res_timing_timerfd should make the segfault go away. Somebody posted a patch, but no feedback from upstream yet.

I suggest leaving this issue open as others may run into the same.

Kind regards,
Seb

**Comment by jospezial** [comment]
> Merry Christmas,
> 
> See upstream bug: [Link](https://issues.asterisk.org/jira/browse/ASTERISK-28800)
> 
> Loading the module res_timing_timerfd should make the segfault go away. Somebody posted a patch, but no feedback from upstream yet.
> 
> I suggest leaving this issue open as others may run into the same.
> 
> Kind regards,
> Seb

Happy hollydays!
Thank you for the upstream bug action with backtrace.
So, what would be better? Loading the module or using the no-timer patch?
Do I need the module for anything else than to circumvent this bug?
When using the patch and not the module, will I have any disadvantages?
I hope upstream will fix this soon. The upstream bug is 8 months old.

**Comment by micmac1** [comment]
All I know is upstream suggested to load the timerfd module. They didn't say anything about the patch yet.

**Comment by micmac1** [comment]
Hello @jslachta :-)

I'm thinking that maybe it would be a good idea to include the timerfd module in the base asterisk package. [1] mentions that the timing modules are used for iax2 and also (maybe) when playing files. Now we know that they're also used for DTMF, which is basic functionality that doesn't come with a module.

We have some modules that depend on timing modules. chan-iax2 depends on timerfd. res-fax on pthread. I checked AST_MODULE_INFO of these modules and there is no mention of any dependency on any timing modules. So it's not readily apparent what functionality depends on any of the timing modules.

Adding a timing module to the base asterisk package seems to make sense to me. Like app_dial for instance, which is also in the base asterisk package.

In [2] there is some more info from upstream on this topic. All in all we can say that we can't use kqueue, as it is meant for BSDs and Mac. pthread uses a userspace thread which is said to be not very efficient. timerfd looks like the best choice, it's timing comes from the kernel. All our kernels support it as far as I know. DAHDI doesn't seem like a good choice for obvious reasons.

The timerfd ipk weighs in at a little under 4KB (IPK). So it's not big. I could add a commit to the 18.1.1 pull request that adds it to the base package. What do you think?

Kind regards,
Seb

[1] https://wiki.asterisk.org/wiki/display/AST/Timing+Interfaces
[2] http://lists.digium.com/pipermail/asterisk-users/2015-February/285804.html

**Comment by jospezial** [comment]
I can't find any information about the "Upstream packet fifo full[ch(0)]" message.
After the asterisk crash I only cat get it away with a reboot. Where is this "Upstream packet fifo" ? On my device or at my provider?
Is that a lantiq thing only? Is it in vmmc* or in the VDSL driver?
If I try to restart the asterisk service after the crash, then the router reboots.
```Fri Dec 25 13:46:06 2020 daemon.info asterisk[4834]:   == res_pjsip_publish_asterisk.so => (PJSIP Asterisk Event PUBLISH Support)
Fri Dec 25 13:46:06 2020 daemon.info asterisk[4834]:  Loading chan_lantiq.so.
Fri Dec 25 13:46:07 2020 daemon.info asterisk[4834]:   == Registered channel type 'TAPI' (Lantiq TAPI Telephony API Driver)
Fri Dec 25 13:46:07 2020 kern.warn kernel: [91733.571802] MPS cmd_err interrupt!
Fri Dec 25 13:46:07 2020 kern.warn kernel: [91733.573806] MPS cmd_err interrupt!
Fri Dec 25 13:46:07 2020 kern.warn kernel: [91733.577290] MPS cmd_err interrupt!
Fri Dec 25 13:46:07 2020 kern.warn kernel: [91733.583290] ifx_mps_mbx_cmd_upstream() - wheee, unmaintained command message...
Fri Dec 25 13:46:07 2020 kern.warn kernel: [91733.596355]
Fri Dec 25 13:46:07 2020 kern.warn kernel: [91733.596355] !!! cErrHdlr cause 0x0025, cHdr 0x0600E000```

I am building a new image now with res_timing_timerfd enabled in menuconfig. As I have read, the module should be loaded automatically by asterisk.

**Comment by micmac1** [comment]
> Where is this "Upstream packet fifo" ?

It's from kmod-ltq-vmmc (src/drv_vmmc_int.c).

**Comment by jospezial** [comment]
with my new image res_timing_timerfd is now loaded automatically and dtmf works.

**Comment by dhewg** [comment]
> I'm thinking that maybe it would be a good idea to include the timerfd module in the base asterisk package

Please do!

I too wasted hours on this, including an upstream report and a successful bisect [0], only to get slapped with a insta-close as duplicate. The issue is known for >8 months now, and people are obviously still running into this for no good reason, it's basically just a missing dependency.

Upstream doesn't seem to care about the user experience here. OpenWRT can and really should do better than that.

[0] https://issues.asterisk.org/jira/browse/ASTERISK-29068

**Comment by jslachta** [comment]
Hello Sebastian (@micmac1),

having the timerfd module in the base asterisk package totally makes sense. Would you be so kind to update the pull request - drop the module and place it to the base package? 

Thank you so much.
Jiri

**Comment by micmac1** [comment]
> having the timerfd module in the base asterisk package totally makes sense. Would you be so kind to update the pull request - drop the module and place it to the base package?

Hello Jiri, it's done.

Thanks!
Seb

**Comment by jospezial** [comment]
> with my new image res_timing_timerfd is now loaded automatically and dtmf works.
I have to take it back.
Now asterisk does not crash but the call will be canceld on dtmf send.
Could you please check it on your system?
I removed all phone numbers in the log.
You will notice the "Anonymous", I can't get my configuration set up to send my phone number.
If you could give me a hint, it would be nice.

```
Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Got  RTP packet from    62.52.130.147:15194 (type 08, seq 002275, ts 364000, len 000160)
Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Sent RTP packet to      62.52.130.147:15194 (type 08, seq 034999, ts 362880, len 000160)
Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Got  RTP packet from    62.52.130.147:15194 (type 08, seq 002276, ts 364160, len 000160)
Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035000, ts 363120, len 000004)
Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035001, ts 363120, len 000004)
Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Got  RTP packet from    62.52.130.147:15194 (type 08, seq 002277, ts 364320, len 000160)
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035002, ts 363120, len 000004)
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:     -- Channel TAPI/1 left 'simple_bridge' basic-bridge <dee53ccb-5039-47c7-aee3-48c4baf455bd>
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:     -- Channel PJSIP/out_o2-00000002 left 'simple_bridge' basic-bridge <dee53ccb-5039-47c7-aee3-48c4baf455bd>
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035003, ts 363120, len 000004)
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035004, ts 363120, len 000004)
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035005, ts 363120, len 000004)
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:   == Spawn extension (lantiq1, removed, 1) exited non-zero on 'TAPI/1'
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: <--- Transmitting SIP request (481 bytes) to UDP:213.20.127.47:5060 --->
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: BYE sip:sgc_c@213.20.127.47;transport=udp SIP/2.0
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Via: SIP/2.0/UDP 77.0.49.60:5060;rport;branch=z9hG4bKPj6f4b25c7-f1b6-4828-a5d3-cf87f25bbbd1
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: From: "Anonymous" <sip:removed@sip.alice-voip.de>;tag=35a3495b-d7cd-4b08-9916-9d90537d1190
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: To: <sip:removed@sip.alice-voip.de>;tag=h7g4Esbg_1513726570-1609182978389
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Call-ID: 0d2aa243-bc41-4b03-83e8-c4a3ec6a759d
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: CSeq: 27706 BYE
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Reason: Q.850;cause=16
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Max-Forwards: 70
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: User-Agent: Asterisk PBX 18.1.1
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Content-Length:  0
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: <--- Received SIP response (395 bytes) from UDP:213.20.127.47:5060 --->
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: SIP/2.0 200 OK
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Via: SIP/2.0/UDP 77.0.49.60:5060;received=77.0.49.60;rport=5060;branch=z9hG4bKPj6f4b25c7-f1b6-4828-a5d3-cf87f25bbbd1
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: To: <sip:removed@sip.alice-voip.de>;tag=h7g4Esbg_1513726570-1609182978389
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: From: "Anonymous" <sip:removed@sip.alice-voip.de>;tag=35a3495b-d7cd-4b08-9916-9d90537d1190
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Call-ID: 0d2aa243-bc41-4b03-83e8-c4a3ec6a759d
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: CSeq: 27706 BYE
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Content-Length: 0
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
```

**Comment by micmac1** [comment]
Maybe your router is too slow for the logging you chose? For me it works fine, the call is not disconnected after DTMF, it continues till I hang up. Regarding CLI issue maybe ask in some Asterisk forum if you have config issues.

**Comment by jospezial** [comment]
> Maybe your router is too slow for the logging you chose?

I don't see a problem with logging speed? Why do you think it could be to slow for logging?
Output is from logread -f . Connection to the router over ssh.
But yes, it could be more informative about == Spawn extension (lantiq1, removed, 1) exited non-zero on 'TAPI/1' .

Are these lines normal after pressing a number on the phone?:
k[2649]:     -- Channel TAPI/1 left 'simple_bridge' basic-bridge <dee53ccb-5039-47c7-aee3-48c4baf455bd>
Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:     -- Channel PJSIP/out_o2-00000002 left 'simple_bridge' basic-bridge <dee53ccb-5039-47c7-aee3-48c4baf455bd>

**Comment by micmac1** [comment]
I don't know. I don't have a lantiq device, can't help you

**Comment by jospezial** [comment]
> Now asterisk does not crash but the call will be canceld on dtmf send.

> ```
> Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Got  RTP packet from    62.52.130.147:15194 (type 08, seq 002275, ts 364000, len 000160)
> Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Sent RTP packet to      62.52.130.147:15194 (type 08, seq 034999, ts 362880, len 000160)
> Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Got  RTP packet from    62.52.130.147:15194 (type 08, seq 002276, ts 364160, len 000160)
> Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035000, ts 363120, len 000004)
> Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035001, ts 363120, len 000004)
> Mon Dec 28 20:17:11 2020 daemon.info asterisk[2649]: Got  RTP packet from    62.52.130.147:15194 (type 08, seq 002277, ts 364320, len 000160)
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035002, ts 363120, len 000004)
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:     -- Channel TAPI/1 left 'simple_bridge' basic-bridge <dee53ccb-5039-47c7-aee3-48c4baf455bd>
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:     -- Channel PJSIP/out_o2-00000002 left 'simple_bridge' basic-bridge <dee53ccb-5039-47c7-aee3-48c4baf455bd>
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035003, ts 363120, len 000004)
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035004, ts 363120, len 000004)
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Sent RTP DTMF packet to 62.52.130.147:15194 (type 101, seq 035005, ts 363120, len 000004)
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:   == Spawn extension (lantiq1, removed, 1) exited non-zero on 'TAPI/1'
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: <--- Transmitting SIP request (481 bytes) to UDP:213.20.127.47:5060 --->
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: BYE sip:sgc_c@213.20.127.47;transport=udp SIP/2.0
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Via: SIP/2.0/UDP 77.0.49.60:5060;rport;branch=z9hG4bKPj6f4b25c7-f1b6-4828-a5d3-cf87f25bbbd1
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: From: "Anonymous" <sip:removed@sip.alice-voip.de>;tag=35a3495b-d7cd-4b08-9916-9d90537d1190
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: To: <sip:removed@sip.alice-voip.de>;tag=h7g4Esbg_1513726570-1609182978389
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Call-ID: 0d2aa243-bc41-4b03-83e8-c4a3ec6a759d
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: CSeq: 27706 BYE
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Reason: Q.850;cause=16
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Max-Forwards: 70
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: User-Agent: Asterisk PBX 18.1.1
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Content-Length:  0
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: <--- Received SIP response (395 bytes) from UDP:213.20.127.47:5060 --->
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: SIP/2.0 200 OK
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Via: SIP/2.0/UDP 77.0.49.60:5060;received=77.0.49.60;rport=5060;branch=z9hG4bKPj6f4b25c7-f1b6-4828-a5d3-cf87f25bbbd1
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: To: <sip:removed@sip.alice-voip.de>;tag=h7g4Esbg_1513726570-1609182978389
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: From: "Anonymous" <sip:removed@sip.alice-voip.de>;tag=35a3495b-d7cd-4b08-9916-9d90537d1190
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Call-ID: 0d2aa243-bc41-4b03-83e8-c4a3ec6a759d
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: CSeq: 27706 BYE
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]: Content-Length: 0
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
> Mon Dec 28 20:17:12 2020 daemon.info asterisk[2649]:
> ```

Asterisk 18.2.0 does not change this.
I have noticed since some weeks my phone number is now sent. I did not change configuration files. Maybe my provider O2 did change something on their servers.

**Comment by jospezial** [comment]
asterisk-18.3.0-rc1 does not fix the situation.
Here some debug output. Looks as asterisk is trying to use code that is not implemented in channel_lantiq.
```
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Got  RTP packet from    62.53.175.136:12104 (type 08, seq 000171, ts 027360, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP packet to      62.53.175.136:12104 (type 08, seq 019624, ts 024480, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Got  RTP packet from    62.53.175.136:12104 (type 08, seq 000172, ts 027520, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP packet to      62.53.175.136:12104 (type 08, seq 019625, ts 024640, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[3599]: chan_lantiq.c:1517 lantiq_dev_event_digit: on port 0 detected digit "1"
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[3599]: chan_lantiq.c:1505 lantiq_send_digit: Port 0 transmitting digit "1"
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DTMF[4961][C-00000003]: channel.c:3866 __ast_read: DTMF end '1' received on TAPI/1, duration 0 ms
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DTMF[4961][C-00000003]: channel.c:3893 __ast_read: DTMF begin emulation of '1' with duration 100 queued on TAPI/1
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP DTMF packet to 62.53.175.136:12104 (type 101, seq 019626, ts 024968, len 000004)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP DTMF packet to 62.53.175.136:12104 (type 101, seq 019627, ts 024968, len 000004)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Got  RTP packet from    62.53.175.136:12104 (type 08, seq 000173, ts 027680, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP DTMF packet to 62.53.175.136:12104 (type 101, seq 019628, ts 024968, len 000004)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: chan_lantiq.c:817 ast_lantiq_read: entering... no code here...
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge_channel.c:298 ast_bridge_channel_leave_bridge_nolock: Setting 0x205b348(TAPI/1) state from:0 to:1
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge_channel.c:2183 bridge_channel_internal_pull: Bridge 3590b02a-dbbd-4e96-8f04-0702cc115b7f: pulling 0x205b348(TAPI/1)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]:     -- Channel TAPI/1 left 'simple_bridge' basic-bridge <3590b02a-dbbd-4e96-8f04-0702cc115b7f>
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge_channel.c:2194 bridge_channel_internal_pull: Bridge 3590b02a-dbbd-4e96-8f04-0702cc115b7f: 0x205b348(TAPI/1) is leaving simple_bridge technology
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge.c:337 bridge_dissolve: Bridge 3590b02a-dbbd-4e96-8f04-0702cc115b7f: dissolving bridge with cause 16(Normal Clearing)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 
```

**Comment by jospezial** [comment]
asterisk-18.3.0-rc1 does not fix the situation.
Here some debug output. Looks as asterisk is trying to use code that is not implemented in channel_lantiq.

```
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Got  RTP packet from    62.53.175.136:12104 (type 08, seq 000171, ts 027360, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP packet to      62.53.175.136:12104 (type 08, seq 019624, ts 024480, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Got  RTP packet from    62.53.175.136:12104 (type 08, seq 000172, ts 027520, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP packet to      62.53.175.136:12104 (type 08, seq 019625, ts 024640, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[3599]: chan_lantiq.c:1517 lantiq_dev_event_digit: on port 0 detected digit "1"
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[3599]: chan_lantiq.c:1505 lantiq_send_digit: Port 0 transmitting digit "1"
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DTMF[4961][C-00000003]: channel.c:3866 __ast_read: DTMF end '1' received on TAPI/1, duration 0 ms
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DTMF[4961][C-00000003]: channel.c:3893 __ast_read: DTMF begin emulation of '1' with duration 100 queued on TAPI/1
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP DTMF packet to 62.53.175.136:12104 (type 101, seq 019626, ts 024968, len 000004)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP DTMF packet to 62.53.175.136:12104 (type 101, seq 019627, ts 024968, len 000004)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Got  RTP packet from    62.53.175.136:12104 (type 08, seq 000173, ts 027680, len 000160)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: Sent RTP DTMF packet to 62.53.175.136:12104 (type 101, seq 019628, ts 024968, len 000004)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: chan_lantiq.c:817 ast_lantiq_read: entering... no code here...
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge_channel.c:298 ast_bridge_channel_leave_bridge_nolock: Setting 0x205b348(TAPI/1) state from:0 to:1
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge_channel.c:2183 bridge_channel_internal_pull: Bridge 3590b02a-dbbd-4e96-8f04-0702cc115b7f: pulling 0x205b348(TAPI/1)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]:     -- Channel TAPI/1 left 'simple_bridge' basic-bridge <3590b02a-dbbd-4e96-8f04-0702cc115b7f>
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge_channel.c:2194 bridge_channel_internal_pull: Bridge 3590b02a-dbbd-4e96-8f04-0702cc115b7f: 0x205b348(TAPI/1) is leaving simple_bridge technology
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 18:14:44] DEBUG[4961][C-00000003]: bridge.c:337 bridge_dissolve: Bridge 3590b02a-dbbd-4e96-8f04-0702cc115b7f: dissolving bridge with cause 16(Normal Clearing)
Fri Mar 12 19:14:44 2021 daemon.info asterisk[2964]: [Mar 12 
```

**Comment by jospezial** [comment]
github said You can't comment at this time. and had error on rendering the text.

**Comment by jospezial** [comment]
Why? What does that mean? And is that why Channel TAPI/1 left the bridge after DTMF is sent?
https://github.com/kochstefan/asterisk_channel_lantiq/blob/1d940b38cde0348dfe129d2b764e6faee440c45b/src/channels/chan_lantiq.c#L815
```
static struct ast_frame * ast_lantiq_read(struct ast_channel *ast)
{
	ast_log(LOG_DEBUG, "entering... no code here...\n");
	return NULL;
}

**Comment by micmac1** [comment]
Please close this issue and raise a new one. What you're looking at now is not a crash. The initial crash was already looked at. I suggest to open a separate issue for the call disconnects. Normally I'd recommend to open this upstream. But seeing that upstream doesn't have an issue tracker you can try your luck here. I suggest that in the new issue you ping kochstefan and arnysch and ask them for help.

**Comment by jospezial** [comment]
> Please close this issue and raise a new one. What you're looking at now is not a crash. The initial crash was already looked at. I suggest to open a separate issue for the call disconnects. Normally I'd recommend to open this upstream. But seeing that upstream doesn't have an issue tracker you can try your luck here. I suggest that in the new issue you ping kochstefan and arnysch and ask them for help.

Will do so. Thank you for your help.
