### ISSUE TITLE
asterisk-chan-lantiq not available

### ISSUE THREAD

**Issue by AndyX90** [openwrt/telephony#616]
Maintainer: @jslachta
Environment: tp-link vr200v (xrx200) on OpenWrt SNAPSHOT, r15878-9dc84018ee

Description:
The package openwrt-chan-lantiq is not available anymore on latest snapshots.

**Comment by micmac1** [comment]
Thanks for letting us now. It seems to be caused by a build bot issue. I've pinged openwrt-devel about it [here](https://lists.openwrt.org/pipermail/openwrt-devel/2021-February/033966.html).

Kind regards,
Seb

**Comment by AndyX90** [comment]
Seems to be resolved now. Thanks!
