### ISSUE TITLE
Use GitHub CI?

### ISSUE THREAD

**Issue by aparcar** [openwrt/telephony#617]
Hi, packages.git uses GitHub actions, any interest to use this here as well?

**Comment by jslachta** [comment]
Hi @aparcar,

telephony repository should go the same way as the packages repository. The answer is yes.

I am currently out of time, so any help would be appreciated.

Kind regards
Jiri

**Comment by aparcar** [comment]
I'm happy to enable the CI here, but for best results I'd even suggest to move all packages here over to packages.git, not?

**Comment by micmac1** [comment]
Not a fan of the idea of moving this to packages. Packages is way noisier than telephony. I don't want to have to follow that repo.

**Comment by jslachta** [comment]
I am also against the idea of moving all packages to packages.git repository.

**Comment by aparcar** [comment]
Fine with me. I'll extend the packages.git ci and then add it here

**Comment by micmac1** [comment]
Thanks Paul!
