### ISSUE TITLE
asterisk13: symlinks for several libs

### ISSUE THREAD

**Issue by madires** [openwrt/telephony#62]
No symlinks for libs installed in /usr/lib:

ls -l /usr/lib/libasteriskssl*
-rwxr-xr-x 1 root root 5256 May 10 03:20 /usr/lib/libasteriskssl.so
-rwxr-xr-x 1 root root 5256 May 10 03:20 /usr/lib/libasteriskssl.so.1

To reduce disk usage:
libasteriskssl.so -> libasteriskssl.so.1

Also for other libs installed by some asterisk13 packages:
-rwxr-xr-x 1 root root 96032 May 10 02:06 libpj.so
-rwxr-xr-x 1 root root 96032 May 10 02:06 libpj.so.2
-rwxr-xr-x 1 root root 112292 May 10 02:06 libpjlib-util.so
-rwxr-xr-x 1 root root 112292 May 10 02:06 libpjlib-util.so.2
-rwxr-xr-x 1 root root 12692 May 10 02:06 libpjmedia-audiodev.so
-rwxr-xr-x 1 root root 12692 May 10 02:06 libpjmedia-audiodev.so.2
-rwxr-xr-x 1 root root 4992 May 10 02:06 libpjmedia-codec.so
-rwxr-xr-x 1 root root 4992 May 10 02:06 libpjmedia-codec.so.2
-rwxr-xr-x 1 root root 2176 May 10 02:06 libpjmedia-videodev.so
-rwxr-xr-x 1 root root 2176 May 10 02:06 libpjmedia-videodev.so.2
-rwxr-xr-x 1 root root 241092 May 10 02:06 libpjmedia.so
-rwxr-xr-x 1 root root 241092 May 10 02:06 libpjmedia.so.2
-rwxr-xr-x 1 root root 109908 May 10 02:06 libpjnath.so
-rwxr-xr-x 1 root root 109908 May 10 02:06 libpjnath.so.2
-rwxr-xr-x 1 root root 55304 May 10 02:06 libpjsip-simple.so
-rwxr-xr-x 1 root root 55304 May 10 02:06 libpjsip-simple.so.2
-rwxr-xr-x 1 root root 75328 May 10 02:06 libpjsip-ua.so
-rwxr-xr-x 1 root root 75328 May 10 02:06 libpjsip-ua.so.2
-rwxr-xr-x 1 root root 193836 May 10 02:06 libpjsip.so
-rwxr-xr-x 1 root root 193836 May 10 02:06 libpjsip.so.2
-rwxr-xr-x 1 root root 184108 May 10 02:06 libpjsua.so
-rwxr-xr-x 1 root root 184108 May 10 02:06 libpjsua.so.2
-rwxr-xr-x 1 root root 293788 May 10 02:06 libpjsua2.so
-rwxr-xr-x 1 root root 293788 May 10 02:06 libpjsua2.so.2
-rwxr-xr-x 1 root root 46996 May 10 02:06 libresample.so
-rwxr-xr-x 1 root root 46996 May 10 02:06 libresample.so.2

**Comment by jslachta** [comment]
This should be fixed for asterisk and pjproject packages. Thank you.
