### ISSUE TITLE
meta: if commit acces -> enable 2FA

### ISSUE THREAD

**Issue by aparcar** [openwrt/telephony#622]
Please see the following meta issue over at packages.git: https://github.com/openwrt/packages/issues/14936

tl;dr: Enable 2FA if you have commit access now.

While at it, does anyone around here know the user @olizam ? The account got commit rights but I can't find any email address for contact or any contributions. If the person is unknown to any members here, I'll temporarily suspend the commit access.

**Comment by jslachta** [comment]
Hi @aparcar, 

Mazi Lo (@olizam) was the package maintainer of the former FreeSWITCH package. Currently, he does not maintain any package in the telephony repository. He usually used random email addresses, so contacting him is quite complicated.

Until he comes with a new package he would maintain, I would drop his commit access.

**Comment by micmac1** [comment]
I have 2FA.

**Comment by aparcar** [comment]
Everyone enabled 2FA by now or lost it's commit access (due to not enabling it and not responding to emails). I'll close this issue and kindly request anyone who grants commit access to future contributors to make sure 2FA is enabled.

**Comment by micmac1** [comment]
Thanks Paul!
