### ISSUE TITLE
asterisk-18.4.0 released

### ISSUE THREAD

**Issue by jospezial** [openwrt/telephony#629]
Maintainer: @jslachta
Description:
https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-18.4.0-summary.html

Will compile and run test it the next days.

**Comment by jospezial** [comment]
compiles and runs
Environment: MIPS lantiq, VGV7510KW22 (o2 Box 6431)

```
-PKG_VERSION:=18.2.2
+PKG_VERSION:=18.3.0

-PKG_HASH:=c7a3da64e30d1ac428ae2cf4723d3a2b799ae88768341084ce8a2e3e424ae163
+PKG_HASH:=cb9566bbe0f29c01af8f5281f0b66657db5e5a2bf147b41bdb027995e22869f5
```

Still need to a fix for #631

**Comment by zuzia-dev** [comment]
Asterisk-18.4.0 released:
[https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-18.4.0-summary.html](url)

Tested with MIPS Lantiq, Easybox 904xDSL (VGV952CJW33-E-IR), built from openwrt git master.

```
-PKG_VERSION:=18.2.2
+PKG_VERSION:=18.4.0

-PKG_HASH:=c7a3da64e30d1ac428ae2cf4723d3a2b799ae88768341084ce8a2e3e424ae163
+PKG_HASH:=91c0c35a0c53097647ab3e7b29d34dd0861fed0a8d52e3617408e9eced404db1
```

I have a problem with DMTF: [#631](url)

**Comment by dhewg** [comment]
A diff in a github comment won't get this in, could you guys please open a MR for this?

**Comment by jslachta** [comment]
@dhewg, I am going to create a MR today for asterisk version update.

**Comment by dhewg** [comment]
Alright, nice! I'll testdrive that then :)

**Comment by jslachta** [comment]
@dhewg, when CI passes, you can go on. Please see #643.

**Comment by jslachta** [comment]
#643 is failing on dahdi, I need to take a look at it closer.

**Comment by jslachta** [comment]
The build was failing on kernel related issues not related to asterisk. Very likely related to dahdi. I merged the changes and the asterisk is currently at version 18.4.0 - in master branch.

The issue #631 is still open.
