### ISSUE TITLE
asterisk13: missing bridge modules

### ISSUE THREAD

**Issue by madires** [openwrt/telephony#63]
Following modules are missing:

    bridge_native_rtp
    bridge_holding
    bridge_builtin_interval_feature

**Comment by madires** [comment]
Following modules are missing:
- bridge_native_rtp
- bridge_holding 
- bridge_builtin_interval_feature

**Comment by jslachta** [comment]
This issue has been resolved in 8c02ae43d0220cc4e249c75d2d591cb52c32aaa2.
