### ISSUE TITLE
freeswitch-mod-bcg729 - compile warning

### ISSUE THREAD

**Issue by ByteEnable** [openwrt/telephony#651]
cc1: warning: switch '-mcpu=cortex-a9' conflicts with '-march=armv5t' switch

**Comment by micmac1** [comment]
Hello,

How can we reproduce this? Are you using an SDK? Share some details
please.

**Comment by ByteEnable** [comment]
Using the latest clone from github and feeds per the wiki.

CONFIG_TARGET_OPTIMIZATION="-O3 -pipe -mcpu=cortex-a9 -mfloat-abi=hard -mfpu=neon -funsafe-math-optimizations"

**Comment by micmac1** [comment]
What target did you select?

**Comment by ByteEnable** [comment]
WRT3200ACM

**Comment by micmac1** [comment]
I don't see how this can be the package's making. It just takes whatever
is in $(TARGET_CFLAGS).

**Comment by ByteEnable** [comment]
The makefile looks like its for x86:

################################
### FreeSwitch headers files found in libfreeswitch-dev ###
FS_INCLUDES=/usr/include/freeswitch
FS_MODULES=/usr/lib/freeswitch/mod
################################

### END OF CUSTOMIZATION ###
SHELL := /bin/bash
PROC?=$(shell uname -m)

CC=gcc 
CFLAGS=-fPIC -O3 -fomit-frame-pointer -fno-exceptions -Wall -std=c99 -pedantic

ifeq (${PROC},x86_64)
        CFLAGS+=-m64 -mtune=generic
else
        CFLAGS+=-m32 -march=i686
endif

INCLUDES=-I/usr/include -Ibcg729/include -I$(FS_INCLUDES)
LDFLAGS=-lm -Wl,-static -Lbcg729/src/.libs -lbcg729 -Wl,-Bdynamic 

all : mod_bcg729.o
        $(CC) $(CFLAGS) $(INCLUDES) -shared -Xlinker -x -o mod_bcg729.so mod_bcg729.o $(LDFLAGS)

mod_bcg729.o: bcg729 mod_bcg729.c
        $(CC) $(CFLAGS) $(INCLUDES) -c mod_bcg729.c

clone_bcg729:
        if [ ! -d bcg729 ]; then \
                git clone git://git.linphone.org/bcg729.git; pushd bcg729 ; git checkout 1.0.3; popd; \
        fi

bcg729: clone_bcg729
        cd bcg729 && sh autogen.sh && CFLAGS=-fPIC ./configure && make && cd ..
        
clean:
        rm -f *.o *.so *.a *.la; cd bcg729 && make clean; cd ..

distclean: clean
        rm -fR bcg729

install: all
        /usr/bin/install -c mod_bcg729.so $(INSTALL_PREFIX)/$(FS_MODULES)/mod_bcg729.so

**Comment by micmac1** [comment]
This Makefile is not used by the package.

**Comment by ByteEnable** [comment]
What makefile does it use?

**Comment by micmac1** [comment]
Morning! Just this one: https://github.com/openwrt/telephony/blob/master/net/freeswitch-mod-bcg729/Makefile

**Comment by ByteEnable** [comment]
Running a new build and capturing output with -j1 vs make args.

**Comment by ByteEnable** [comment]
I did a make clean and I don't see this error anymore.  Can close.
