### ISSUE TITLE
asterisk11-chan-dongle compile problem with musl on openwrt and git changed

### ISSUE THREAD

**Issue by Himan2001** [openwrt/telephony#66]
The asterisk-chan_dongle does no longer compile with musl on openwrt

By the way: the git-repository is changed to: 
https://github.com/bg111/asterisk-chan-dongle
This repository is newer.

**Comment by dangowrt** [comment]
Build with musl should be fixed by f01cea41279912f131f554aa85f6b64299f0690d.
Please try if it works.

**Comment by Himan2001** [comment]
Will test laster. Question: Can you update to the new/latest git version r46 ?
https://github.com/bg111/asterisk-chan-dongle

For me, this version is working for 1.8 and Asterisk 11 by using the existing makefile

**Comment by dangowrt** [comment]
The diff between https://github.com/jstasiak/asterisk-chan-dongle and https://github.com/bg111/asterisk-chan-dongle is here: https://gist.github.com/dangowrt/4803578dbeefa6f3183c
Doesn't look like we'd want all that...
Maybe we'll just cherry-pick the adding of E1752 and leave the rest as-is unless someone comes up with a good reason?

**Comment by dangowrt** [comment]
I cherry-picked https://github.com/bg111/asterisk-chan-dongle/commit/da5cd41e8554eaf1133f85282c253da2c74ff7eb into eb9adfd95d7780cd5e5d0a415c5bd0b6d888e275 where I added it split into two patches:

https://github.com/openwrt/telephony/blob/master/net/asterisk-11.x-chan-dongle/patches/050-add-E1752-to-seven_bit_modems.patch
https://github.com/openwrt/telephony/blob/master/net/asterisk-11.x-chan-dongle/patches/051-bump-package-revision.patch

Feel free to suggest more patches for cherry-picking.

**Comment by Himan2001** [comment]
I sugest the same package for asterisk 1.8, too ;-)

In the makefile you need to change only the include-paths and one definition for "version=11000" must be deleted. This package for the 1.8er Version makes sense, because this asterisk package is smaller as the 11er version.
