### ISSUE TITLE
unnesassary build of 3 different asterisk versions every time ?

### ISSUE THREAD

**Issue by Himan2001** [openwrt/telephony#68]
When only one asterisk-version is selected, why always all 3 versions 1,8 / 11 and 13
are build ?

I see no real dependancys, when one selected version is build with success.

**Comment by jslachta** [comment]
This is caused by package variants of chan-sccp-b and codec-g729 package. If you do not select those packages, all asterisk packages does not get compiled. Only the selected one.

**Comment by dangowrt** [comment]
On Mon, Jun 22, 2015 at 12:59:16AM -0700, Himan2001 wrote:
> When only one asterisk-version is selected, why always all 3 versions 1,8 / 11 and 13
> are build ?
> 
> I see no real dependancys, when one selected version is build with success.

This is because the G.729 codec library is built for all three versions.
Deselecting G.729 support should fix that.
