### ISSUE TITLE
baresip fails on mips 4kec

### ISSUE THREAD

**Issue by neheb** [openwrt/telephony#730]
Maintainer: @jslachta 
Environment: mips 4kec

https://downloads.openwrt.org/snapshots/faillogs/mips_4kec/telephony/baresip/compile.txt

**Comment by micmac1** [comment]
Hi Rosen,

The problem is the missing AUDIO_SUPPORT on 4kec and then maybe with OpenWrt build system not propagating this dep from alsa to gstreamer to baresip. But we could add a depend on AUDIO_SUPPORT to the baresip gstreamer plugins as a workaround I suppose.

Regards,
Seb
