### ISSUE TITLE
pjproject: PJSIP new release version 2.12.x

### ISSUE THREAD

**Issue by jospezial** [openwrt/telephony#747]
Maintainer: @jslachta 

@micmac1 @dhewg 

https://github.com/pjsip/pjproject/releases/tag/2.12
https://github.com/pjsip/pjproject/releases/tag/2.12.1

**Comment by jospezial** [comment]
Asterisk will also switch soon their bundled pjproject to the new version.
https://gerrit.asterisk.org/c/asterisk/+/18075

**Comment by jospezial** [comment]
Asterisk has released x.x.1 versions with security patches for pjproject pjsip 2.10.

2.12 has all that fixed.

**Comment by jospezial** [comment]
Latest release of asterisk uses pjsip 2.12.
One of the next releases will use pjsip 2.12.1
https://gerrit.asterisk.org/c/asterisk/+/18536

**Comment by Neustradamus** [comment]
@jospezial: @micmac1 has done a PR here:
- https://github.com/openwrt/telephony/pull/776
