### ISSUE TITLE
freeswitch-mod-perl missing aarch64_cortex-a53

### ISSUE THREAD

**Issue by RetEECS** [openwrt/telephony#794]
Maintainer: @micmac1
Environment: aarch64_cortex-a53, OpenWrt 22.03.2

Description: aarch64_cortex-a53 is missing from the list of architectures for freeswitch-mod-perl.

The freeswitch-mod-perl package still exists in other architectures in OpenWrt 22.03.2. I updated my router from a Netgear WNDR3700v4 (mips_24kc, also OpenWrt 22.03.2) to a Linksys E8450 (aarch64_cortex-a53) and found that I could no longer install this package.

Actually compared to freeswitch itself, freeswitch-mod-perl is missing six architectures:
```
    aarch64_cortex-a53
    aarch64_cortex-a72
    aarch64_generic
    mips64_octeonplus
    powerpc_464fp
    powerpc_8540
```
Let me know if I can provide any further information, or if I can help test any fix!

**Comment by micmac1** [comment]
Hi there,

I'm afraid there's nothing I can do about that in the freeswitch package. freeswitch-mod-perl requires Perl with threads ("multiplicity"), see [1]. And the OpenWrt Perl package (from packages repo) only enables threads for certain targets, see [2]. The flag our package looks for in OpenWrt configuration is CONFIG_PERL_THREADS.

Maybe check if you can build the Perl package with threads for aarch64. Then freeswitch-mod-perl with become available in menuconfig automatically.

Kind regards,
Seb

[1] https://github.com/signalwire/freeswitch/blob/master/src/mod/languages/mod_perl/Makefile.am
[2] https://github.com/openwrt/packages/blob/master/lang/perl/Config.in

**Comment by RetEECS** [comment]
Thanks for that information, it now makes sense.

Do you happen to know if there is some good reason why the Perl package doesn't enable threads for the other targets?

Would it be worth me raising a request against Perl?

Kind regards,
Doug

**Comment by micmac1** [comment]
>Do you happen to know if there is some good reason why the Perl package doesn't enable threads for the other targets?
>

I don't know :-)


>Would it be worth me raising a request against Perl?

Sure. Might be best if you tried it out, confirmed on your router it works, and send a pull request to add aarch64 to the Perl package's Config.in. Just raising an issue in packages repo might not get picked up, as they have lots of open issues over there.

Kind regards,
Seb

**Comment by RetEECS** [comment]
> Might be best if you tried it out, confirmed on your router it works

Done and works for the (fairly trivial) Perl code that I am using. I did have to fix one minor error in wxe_wrapper_5.cpp before it would build though.

> and send a pull request 

I shall have to read up about how to do that!

Thanks for your help.

Kind regards,
Doug

P.S. Feel free to close this request now, or I can if that is preferred?

**Comment by micmac1** [comment]
No matter, will close it now.

Kind regards,
Seb
