### ISSUE TITLE
rtpengine doesn't start

### ISSUE THREAD

**Issue by r-vit** [openwrt/telephony#796]
Maintainer: Sebastian Kemper <sebastian_ml@gmx.net>
Environment: arch: ARMv8 Processor rev 4, model: Xiaomi Redmi Router AX6S, OpenWrt version: 22.03.2 r19803-9a599fee93

Description:
rtpengine doesn't start with an error "Error relocating /usr/bin/rtpengine: lws_get_ssl: symbol not found"

package version is 9.5.3.2-2

**Comment by micmac1** [comment]
Remove libwebsockets-mbedtls, install libwebsockets-full and report back, please.

**Comment by r-vit** [comment]
it does work with this library

**Comment by micmac1** [comment]
OK, will update the dependency.

**Comment by micmac1** [comment]
Thanks for the report @r-vit 

Closing as done.
