### ISSUE TITLE
Baresip was updated to 0.4.13 everything compiles.

### ISSUE THREAD

**Issue by xromansx** [openwrt/telephony#81]
Needed only to change this in Makefile...

PKG_NAME:=baresip
PKG_VERSION:=0.4.13
PKG_RELEASE:=2

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=http://www.creytiv.com/pub/
PKG_MD5SUM:=75f5533566a9af296c65e5ab2ae5d8b7

Is it possible to add dtmfio module to baresip ?
Thanks.

**Comment by jslachta** [comment]
Should be ok, baresip upgraded to 0.4.14.
