### ISSUE TITLE
The freeswitch dependency should modify libpcre to libpcre2

### ISSUE THREAD

**Issue by breeze303** [openwrt/telephony#870]
When installing freeswitch the following error occurs, which should be changed to libpcre2

Warning: the file “package/feeds/telephony/freeswitch/Makefile” depends on “libpcre” and “ libpcre” does not exist.

**Comment by dannil** [comment]
@Ansuel is trying to fix (and upstream) the change with https://github.com/openwrt/telephony/pull/841 but seems they aren't responding.

**Comment by BKPepe** [comment]
Fixed by merging https://github.com/openwrt/telephony/pull/841
