### ISSUE TITLE
Chaos Calmer 15.05 / asterisk13: no audio for G.722

### ISSUE THREAD

**Issue by madires** [openwrt/telephony#88]
A PJSIP endpoint supporting G.722 doesn't play any audio when calling another endpoint without G.722. Also no audio when calling the voicebox and so one. codec_g722.so is loaded and running. As soon as G.722 is disabled on the endpoint, audio is fine. G.722 works fine with Barrier Breaker 14.07 and asterisk11.

**Comment by madires** [comment]
Supplement: G.722 works fine using chan_sip with Barrier Breaker 14.07 and asterisk11

**Comment by madires** [comment]
I've done a little bit more testing:
- audio is one-way, i.e. the G.722 phone doesn't play audio but the other end does or voicemail can record the call.
- when I force the phone to use G.722 only, audio is fine

It looks like asterisk13 is using different codecs for both audio directions, when the phone supports multiple codecs. Or something like this. There are more users with the same problem (http://community.freepbx.org/t/fpbx13-rc-g722-and-1-way-audio-even-to-voicemail/31042/48). So it might be a bug in asterisk13.

**Comment by madires** [comment]
Another update: no audio issues with G.722 and chan_sip (Chaos Calmer 15.05 / asterisk13).

**Comment by micmac1** [comment]
Hello @madires 

Please try trunk (e.g. LEDE snapshots) and consider closing this issue.

Kind regards,
Sebastian

**Comment by madires** [comment]
Hi Sebatian!

Is #142 fixed already? Otherwise I wouldn't be able to recheck, since pjsip needs to be running.

Cheers,
 Markus

**Comment by micmac1** [comment]
Hi Markus,

res-pjproject was added in 4aac26a. So you can test it with a LEDE snapshot for instance.

Thanks,
Sebastian

Am 6. August 2017 14:12:59 MESZ schrieb madires <notifications@github.com>:
>Hi Sebatian!
>
>Is #142 fixed already? Otherwise I wouldn't be able to recheck, since
>pjsip needs to be running.
>
>Cheers,
> Markus

**Comment by madires** [comment]
Hi Sebastian!

I've installed the current LEDE snapshot and some modules seem to be missing:

`[Aug  7 20:26:16] Asterisk 13.17.0 built by buildbot @ builds-03.infra.lede-project.org on a 
x86_64 running Linux on 2017-08-07 06:08:41 UTC
[Aug  7 20:26:16] NOTICE[2500] cdr.c: CDR simple logging enabled.
[Aug  7 20:26:16] NOTICE[2500] loader.c: 108 modules will be loaded.
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_endpoint_identifier
_ip.so': Error relocating /usr/local/asterisk/modules/res_pjsip_endpoint_identifier_ip.so: ast_sip_cli_traverse_objects: symbol not found
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_send_to_voicemail.s
o': Error relocating /usr/local/asterisk/modules/res_pjsip_send_to_voicemail.so: ast_sip_sess
ion_remove_datastore: symbol not found
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_one_touch_record_in
fo.so': Error relocating /usr/local/asterisk/modules/res_pjsip_one_touch_record_info.so: ast_
sip_get_pjsip_endpoint: symbol not found
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_notify.so': Error r
elocating /usr/local/asterisk/modules/res_pjsip_notify.so: ast_sip_get_sorcery: symbol not fo
und
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_path.so': Error rel
ocating /usr/local/asterisk/modules/res_pjsip_path.so: ast_sip_get_sorcery: symbol not found
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_endpoint_identifier
_anonymous.so': Error relocating /usr/local/asterisk/modules/res_pjsip_endpoint_identifier_an
onymous.so: ast_sip_get_sorcery: symbol not found
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_authenticator_diges
t.so': Error relocating /usr/local/asterisk/modules/res_pjsip_authenticator_digest.so: ast_si
p_register_authenticator: symbol not found
[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module 'res_pjsip_session.so': Error 
relocating /usr/local/asterisk/modules/res_pjsip_session.so: ast_sip_create_dialog_uas: symbo
l not found`

... and a few lines more, just pjsip related modules. The non-standard path "/usr/local/asterisk/" is caused by moving asterisk to an USB stick. So we have to fix this first before I'm able to recheck the G.722 issue. 

Cheers,
 Markus

**Comment by micmac1** [comment]
Hi Markus,

How would we do that in the Makefile? There's no way to predict your particular module path. If you need to move the modules you should add the rpath yourself (should be possible).

Or maybe you can try to add your mod dir to LD_LIBRARY_PATH and export it (in init script) before starting asterisk?

Regards,
Sebastian

Am 7. August 2017 20:53:45 MESZ schrieb madires <notifications@github.com>:
>Hi Sebastian!
>
>I've installed the current LEDE snapshot and some modules seem to be
>missing:
>
>`[Aug  7 20:26:16] Asterisk 13.17.0 built by buildbot @
>builds-03.infra.lede-project.org on a 
>x86_64 running Linux on 2017-08-07 06:08:41 UTC
>[Aug  7 20:26:16] NOTICE[2500] cdr.c: CDR simple logging enabled.
>[Aug  7 20:26:16] NOTICE[2500] loader.c: 108 modules will be loaded.
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_endpoint_identifier
>_ip.so': Error relocating
>/usr/local/asterisk/modules/res_pjsip_endpoint_identifier_ip.so:
>ast_sip_cli_traverse_objects: symbol not found
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_send_to_voicemail.s
>o': Error relocating
>/usr/local/asterisk/modules/res_pjsip_send_to_voicemail.so:
>ast_sip_sess
>ion_remove_datastore: symbol not found
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_one_touch_record_in
>fo.so': Error relocating
>/usr/local/asterisk/modules/res_pjsip_one_touch_record_info.so: ast_
>sip_get_pjsip_endpoint: symbol not found
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_notify.so': Error r
>elocating /usr/local/asterisk/modules/res_pjsip_notify.so:
>ast_sip_get_sorcery: symbol not fo
>und
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_path.so': Error rel
>ocating /usr/local/asterisk/modules/res_pjsip_path.so:
>ast_sip_get_sorcery: symbol not found
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_endpoint_identifier
>_anonymous.so': Error relocating
>/usr/local/asterisk/modules/res_pjsip_endpoint_identifier_an
>onymous.so: ast_sip_get_sorcery: symbol not found
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_authenticator_diges
>t.so': Error relocating
>/usr/local/asterisk/modules/res_pjsip_authenticator_digest.so: ast_si
>p_register_authenticator: symbol not found
>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>'res_pjsip_session.so': Error 
>relocating /usr/local/asterisk/modules/res_pjsip_session.so:
>ast_sip_create_dialog_uas: symbo
>l not found`
>
>... and a few lines more, just pjsip related modules. The non-standard
>path "/usr/local/asterisk/" is caused by moving asterisk to an USB
>stick. So we have to fix this first before I'm able to recheck the
>G.722 issue. 
>
>Cheers,
> Markus

**Comment by micmac1** [comment]
Hi again, you can use patchelf to add an rpath. If you have the LEDE build system on you disk you should find it in there somewhere, ready for use.

Am 7. August 2017 21:02:09 MESZ schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>Hi Markus,
>
>How would we do that in the Makefile? There's no way to predict your
>particular module path. If you need to move the modules you should add
>the rpath yourself (should be possible).
>
>Or maybe you can try to add your mod dir to LD_LIBRARY_PATH and export
>it (in init script) before starting asterisk?
>
>Regards,
>Sebastian
>
>Am 7. August 2017 20:53:45 MESZ schrieb madires
><notifications@github.com>:
>>Hi Sebastian!
>>
>>I've installed the current LEDE snapshot and some modules seem to be
>>missing:
>>
>>`[Aug  7 20:26:16] Asterisk 13.17.0 built by buildbot @
>>builds-03.infra.lede-project.org on a 
>>x86_64 running Linux on 2017-08-07 06:08:41 UTC
>>[Aug  7 20:26:16] NOTICE[2500] cdr.c: CDR simple logging enabled.
>>[Aug  7 20:26:16] NOTICE[2500] loader.c: 108 modules will be loaded.
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_endpoint_identifier
>>_ip.so': Error relocating
>>/usr/local/asterisk/modules/res_pjsip_endpoint_identifier_ip.so:
>>ast_sip_cli_traverse_objects: symbol not found
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_send_to_voicemail.s
>>o': Error relocating
>>/usr/local/asterisk/modules/res_pjsip_send_to_voicemail.so:
>>ast_sip_sess
>>ion_remove_datastore: symbol not found
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_one_touch_record_in
>>fo.so': Error relocating
>>/usr/local/asterisk/modules/res_pjsip_one_touch_record_info.so: ast_
>>sip_get_pjsip_endpoint: symbol not found
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_notify.so': Error r
>>elocating /usr/local/asterisk/modules/res_pjsip_notify.so:
>>ast_sip_get_sorcery: symbol not fo
>>und
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_path.so': Error rel
>>ocating /usr/local/asterisk/modules/res_pjsip_path.so:
>>ast_sip_get_sorcery: symbol not found
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_endpoint_identifier
>>_anonymous.so': Error relocating
>>/usr/local/asterisk/modules/res_pjsip_endpoint_identifier_an
>>onymous.so: ast_sip_get_sorcery: symbol not found
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_authenticator_diges
>>t.so': Error relocating
>>/usr/local/asterisk/modules/res_pjsip_authenticator_digest.so: ast_si
>>p_register_authenticator: symbol not found
>>[Aug  7 20:26:17] WARNING[2500] loader.c: Error loading module
>>'res_pjsip_session.so': Error 
>>relocating /usr/local/asterisk/modules/res_pjsip_session.so:
>>ast_sip_create_dialog_uas: symbo
>>l not found`
>>
>>... and a few lines more, just pjsip related modules. The non-standard
>>path "/usr/local/asterisk/" is caused by moving asterisk to an USB
>>stick. So we have to fix this first before I'm able to recheck the
>>G.722 issue. 
>>
>>Cheers,
>> Markus

**Comment by madires** [comment]
Hi Sebastian!

My custom path is no problem at all. I'm already using LD_LIBRARY_PATH and it's working fine. I've noticed that res_pjsip_log_forwarder.so and res_pjsip_multihomed.so are missing. Might be a hint.

Cheers,
 Markus

**Comment by micmac1** [comment]
Ah, sorry, didn't read that right. OK, should be a no-brainer to sort that out. Let me check that out.

Am 7. August 2017 21:23:25 MESZ schrieb madires <notifications@github.com>:
>Hi Sebastian!
>
>My custom path is no problem at all. I'm already using LD_LIBRARY_PATH
>and it's working fine. I've noticed that res_pjsip_log_forwarder.so and
>res_pjsip_multihomed.so are missing. Might be a hint.
>
>Cheers,
> Markus

**Comment by micmac1** [comment]
Hi Markus,

Please try again. You need the new revisions of both pjproject and asterisk. They should be up on the mirrors soon.

Regards,
Seb

Am 7. August 2017 21:32:29 MESZ schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>Ah, sorry, didn't read that right. OK, should be a no-brainer to sort
>that out. Let me check that out.
>
>Am 7. August 2017 21:23:25 MESZ schrieb madires
><notifications@github.com>:
>>Hi Sebastian!
>>
>>My custom path is no problem at all. I'm already using LD_LIBRARY_PATH
>>and it's working fine. I've noticed that res_pjsip_log_forwarder.so
>and
>>res_pjsip_multihomed.so are missing. Might be a hint.
>>
>>Cheers,
>> Markus

**Comment by madires** [comment]
Hi Sebastian!

Thanks! I've just done a complete sysupgrade and G.722 is working fine now with the later asterisk version. During testing I've seen some new minor issues:
- One module is trying to load pjsip_wizard.conf which is missing.
- The snapshot from August 7 installed libresample.so.2 and libspeex.so.1.5.1 which aren't installed by today's snapshot. But I haven't found any problems with that.

Cheers,
 Markus

**Comment by micmac1** [comment]
Thanks for testing. I'll send a PR to Jiri for the conf file. libresample was dropped because we don't need it for asterisk (it has its own resampler). Speex dep was also dropped because it's also not used. pjproject is used by asterisk only for signalling, but not media. That it does by itself.

Please consider closing this issue and any other related issue you may have open.

Have a nice weekend!
Seb

Am 11. August 2017 16:56:44 MESZ schrieb madires <notifications@github.com>:
>Hi Sebastian!
>
>Thanks! I've just done a complete sysupgrade and G.722 is working fine
>now with the later asterisk version. During testing I've seen some new
>minor issues:
>- One module is trying to load pjsip_wizard.conf which is missing.
>- The snapshot from August 7 installed libresample.so.2 and
>libspeex.so.1.5.1 which aren't installed by today's snapshot. But I
>haven't found any problems with that.
>
>Cheers,
> Markus

**Comment by madires** [comment]
Hi Sebastian!

Ok, I see. 

Cheers and a nice WE to you too,
 Markus
