### ISSUE TITLE
Chaos Calmer 15.05 / asterisk13: res_adsi.so in two packages

### ISSUE THREAD

**Issue by madires** [openwrt/telephony#89]
# opkg install asterisk13-voicemail

Installing asterisk13-voicemail (13.4.0-3) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/packages/telephony/asterisk13-voicemail_13.4.0-3_ar71xx.ipk.
Installing asterisk13-res-adsi (13.4.0-3) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/packages/telephony/asterisk13-res-adsi_13.4.0-3_ar71xx.ipk.
Collected errors:
- check_data_file_clashes: Package asterisk13-res-adsi wants to install file /usr/lib/asterisk/modules/res_adsi.so
      But that file is already provided by package  \* asterisk13-voicemail
- opkg_install_cmd: Cannot install package asterisk13-voicemail.

**Comment by dangowrt** [comment]
Needs https://github.com/openwrt/telephony/pull/92

**Comment by micmac1** [comment]
Hello @dangowrt 

res_adsi.so is not installed by the voicemail package anymore. Can you please consider closing this issue?

Kind regards,
Sebastian

**Comment by micmac1** [comment]
Sorry, this comment was more meant toward @madires
