### ISSUE TITLE
Chaos Calmer 15.05 / asterisk13: missing audio files conf-*

### ISSUE THREAD

**Issue by madires** [openwrt/telephony#90]
The audio files for conference rooms are missing. They are neither in asterisk13-sounds, nor in asterisk13-app-confbridge.

**Comment by dangowrt** [comment]
Needs https://github.com/openwrt/telephony/pull/92

**Comment by micmac1** [comment]
Hello @madires 

Can you please try trunk snapshot and let me know if this is still an issue?

Thanks,
Sebastian
